### ISSUE TITLE
Command Line parsing truncates string parameters

### ISSUE THREAD

**Issue by sbrkopac** [vsg-dev/VulkanSceneGraph#100]
**Describe the bug**
Command Line parsing truncates string parameters

**To Reproduce**
```
#include <vsg/all.h>

int main(int argc, char** argv)
{
    // set up defaults and read command line arguments to override them
    vsg::CommandLine arguments(&argc, argv);
    auto test = arguments.value(std::string(), { "--test" });
    if (arguments.errors()) return arguments.writeErrorMessages(std::cerr);

    std::cout << test << std::endl;

    return 0;
}
```

Ran with the following:
```
foo.exe --test "C:\This\Is\A Path"
```

**Expected behavior**
```
EXPECTED: test == C:\This\Is\A Path
ACTUAL: test == C:\This\Is\A
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: master

**Comment by vsg-dev** [comment]
I am away from my dev system right now so can't test it under Linux, but will tomorrow.

Is the " around the results above something you've added or is it what you see on the console?  

With testing directly I can only speculate at this point, but first question would be could the Windows command line parser is treating the space in the file name as a parameter deliminator, ignoring the ".  Does this sounds possible?

The other possibility is the use of std::stringstream within CommandLine is not handling the " and is treat the space as a deliminator.

**Comment by sbrkopac** [comment]
> Is the " around the results above something you've added or is it what you see on the console?

Sorry, I shouldn't have added the quotes in the expected output. I've updated the original post to reflect that.

> The other possibility is the use of std::stringstream within CommandLine is not handling the " and is treat the space as a deliminator.

I did some more digging this morning and looks like [this](https://github.com/vsg-dev/VulkanSceneGraph/blob/3eae9e8633418fd72624d3283d63ae6bfe6e1c4f/include/vsg/utils/CommandLine.h#L70) call truncates it up to the space. I will open a PR to fix it.

**Comment by openscenegraph** [comment]
Just did a quick test and it fails under Linux as well.  I agree with the above conclusion that the culprit is the istringstream usage that is treating the space as a separate field.  The PR doesn't look suitable to me as it'll break with anything other than string parameters.

If I can think of quick fix this evening I'll check it in.  Shouldn't be working on the Saturday evening though!

**Comment by sbrkopac** [comment]
Added a new commit to the PR. I also updated my test program to the following

```
#include <vsg/all.h>

int main(int argc, char** argv)
{
    // set up defaults and read command line arguments to override them
    vsg::CommandLine arguments(&argc, argv);
    auto test = arguments.value(std::string(), { "--test" });
    auto f = arguments.value(1.0f, { "--float" });
    auto i = arguments.value(99, { "--int" });
    if (arguments.errors()) return arguments.writeErrorMessages(std::cerr);

    std::cout << test << std::endl;
    std::cout << f << std::endl;
    std::cout << i << std::endl;

    return 0;
}
```
The following parmas gave the expected output:

```
foo.exe --test "C:\This\Is\A Test" --float 5.2f --int 55

C:\This\Is\A Test
5.2
55
```

**Comment by vsg-dev** [comment]
Thanks for the detailed explanation and PR's the code I went with was:

https://github.com/vsg-dev/VulkanSceneGraph/commit/4f7b886d01a686e30647739aeff0ea6e50cc6060
