### ISSUE TITLE
msys2

### ISSUE THREAD

**Issue by Kojbs123** [vsg-dev/VulkanSceneGraph#1047]
![image](https://github.com/vsg-dev/VulkanSceneGraph/assets/152712153/6187230d-6b1f-4b8f-80c1-573ea1523032)
can't you help me? this picture my problem!

**Comment by robertosfield** [comment]
What does mpicc have to do the VulkanSceneGraph?  I'm closing this Issue as it doesn't have anything to do with the VulkanSceneGraph.

**Comment by Kojbs123** [comment]
> Apa yang harus dilakukan mpicc pada VulkanSceneGraph? Saya menutup Masalah ini karena tidak ada hubungannya dengan VulkanSceneGraph.

im sorry, i don't know this problem. i'm just doing college assignments and i've done everything to instal

**Comment by robertosfield** [comment]
Install what?  mpicc has nothing to do with the VulkanSceneGraph project. Supporting your colleague work isn't my responsibility, go ask your follow students or tutors.

**Comment by Kojbs123** [comment]
> Instal apa? mpicc tidak ada hubungannya dengan proyek VulkanSceneGraph. Mendukung pekerjaan rekan Anda bukan tanggung jawab saya, tanyakan pada siswa atau tutor yang Anda ikuti.

oh okey... im sorry, i use for msys2 and i run my program but text appear not command
