### ISSUE TITLE
Failed to render HeightField

### ISSUE THREAD

**Issue by x1244** [vsg-dev/VulkanSceneGraph#1056]
**Describe the bug**
When running the example `vsgdynamictexture--hf` with the commit `8feb4b7da3bd41544b392ee6dd01c490bd72244e`, rendering the HeightField fails. There has no node displacement is generated.
![001](https://github.com/vsg-dev/VulkanSceneGraph/assets/63945717/48006bf2-4340-4723-a84d-d93f98aec209)

**To Reproduce**
1. build vsg by `8feb4b7da3bd41544b392ee6dd01c490bd72244e`
2. build example `vsgdynamictexture`
3. run `vsgdynamictexture --hf`

**Expected behavior**
Replace `phong_ShaderSet.cpp` from commit `564ab7c0b4a084b1cd03df27a61b14e238a7b81a` and recompile vsg to produce the correct HeightField rendering.
![002](https://github.com/vsg-dev/VulkanSceneGraph/assets/63945717/d71d2163-f212-4e95-a32c-04a2f3f06561)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [chrome]
 - Version [vsg master]

**Comment by robertosfield** [comment]
The commits don't help much.

 Could you be specific about what change broke things, and what change fixes things?

**Comment by x1244** [comment]
I mean the source file `phong_ShaderSet.cpp` from commit `564ab7c0b4a084b1cd03df27a61b14e238a7b81a`  compatible with Heightfield, and the commit `8feb4b7da3bd41544b392ee6dd01c490bd72244e` not compatible with Heightfield.
There has two commit edited`phong_ShaderSet.cpp`.
```
> git log --stat --after="2023-10-20" -- */phong_ShaderSet.cpp
commit 7535f69e10760f1bc0c4dd23257d252b090d9f22
Author: Robert Osfield <robert@openscenegraph.com>
Date:   Fri Nov 10 15:25:54 2023 +0000

    Updated phong_ShaderSet

 src/vsg/utils/shaders/phong_ShaderSet.cpp | 2432 ++++++++++++++---------------
 1 file changed, 1213 insertions(+), 1219 deletions(-)

commit 82f4d27a12f0437e916e0185c7d0acf3da742198
Author: Robert Osfield <robert@openscenegraph.com>
Date:   Fri Nov 10 10:46:41 2023 +0000

    Updated build in ShaderSet

 src/vsg/utils/shaders/phong_ShaderSet.cpp | 3325 +++++++++++++++--------------
 1 file changed, 1671 insertions(+), 1654 deletions(-)
```
The `phong_ShaderSet.cpp` was coded by byte. Could you check for changes to this file?

**Comment by robertosfield** [comment]
Thanks for the extra info.  FYI, when referencing commits could you just specify them directly so github can link to them, adding decoration prevents GitHub from figuring a hash references a commit.

phong_ShaderSet.cpp is automatically created by the vsgshaderset utility program in vsgExamples, using the vsgExamples/data/shaders/standard.vert and standard_phong.frag.  My best guess at this point is something has gone astray in the passing of the height field or in the shader.

**Comment by x1244** [comment]
It should be the change of VSG_DISPLACEMENT_MAP layout set by vsgshaderset utility program. When make file standard.vert segment
```
#ifdef VSG_DISPLACEMENT_MAP
layout(binding = 6) uniform sampler2D displacementMap;
#endif
```
to
```
#ifdef VSG_DISPLACEMENT_MAP
layout(set = 1, binding = 6) uniform sampler2D displacementMap;
#endif
```
I get the height field curved surface.
There may be some code to be edit, I can't find it out.
I save the phong_ShaderSet to .vsgt file，find the setting
```
  name "displacementMap"
  define "VSG_DISPLACEMENT_MAP"
  set 1
  binding 6
```
I haven't mastered vsgshaderset yet, can you help fixed it.
Thanks.

**Comment by robertosfield** [comment]
Thanks to the pointer, that all makes sense, when I get the chance I'll update the associated code in vsgshaderset and then regenerated the built-in shaderset.

**Comment by robertosfield** [comment]
I have fixed the standard.vert shader:

[vsgExamples changes](https://github.com/vsg-dev/vsgExamples/commit/4ff9bede625e4628a85bb910ebde066cef4b3dae
)
And then updated the built-in ShaderSet:

[VSG changes](https://github.com/vsg-dev/VulkanSceneGraph/commit/486afff5a5da91416d36762158ed6b9638a8b403)

**Comment by robertosfield** [comment]
With these fixes vsgdynamictexture --hf now works reliable with VSG master.
