### ISSUE TITLE
LineIntersector segment regression after Animation merge

### ISSUE THREAD

**Issue by robertosfield** [vsg-dev/VulkanSceneGraph#1102]
### Discussed in https://github.com/vsg-dev/VulkanSceneGraph/discussions/1101

<div type='discussions-op-text'>

<sup>Originally posted by **rolandhill** February 26, 2024</sup>
Hi Robert,

I just updated all the VSG libraries today for the first time in a couple of months and found that my line intersectors are not working any more. I use MatrixTransforms to offset groups of vertices (OctTree), so the vertex and intersector data must be consistently either in local or in world coordinates. It used to all work in local coordinates, but now none of my intersections work and it looks like the vsg::LineSegmentIntersector::_lineSegmentStack is storing world coordinates. Is this the case? If so, is this a bug or an intended change? 

Apologies if I've missed a post about it.

Regards,
Roland
</div>

**Comment by robertosfield** [comment]
I have tracked down the regression to the previous use of default copy constructor, that's not possible when using CopyOp so I have implemented the copy constructor manually:

1380b6ab6cf079d2ae3ff1e2185cd07e258d7ac9

**Comment by rolandhill** [comment]
Thanks, Robert. I pulled the latest versions and everything is working again. Great support as always!

Regards,
Roland
