### ISSUE TITLE
Re-compiling always allocates minimumBufferSize (16MB) for new buffers

### ISSUE THREAD

**Issue by TP-David** [vsg-dev/VulkanSceneGraph#1139]
Additional calls to `BindIndex/VertexBuffers` are not re-using the memory blocks from the previous frame/compilation, causing the minimal size to be allocated for each of them (16MB as defined in MemoryBufferPools.h).

After investigation we localized the issue to a `MemoryBufferPools` being created each compilation in `Viewer::compile` (new `CompileTraversal`->new `Context`->new `CopyAndReleaseBuffer`->new `MemoryBufferPools`). A rudimentary workaround which solves the issue is:
1. Making `deviceResourceMap` a member field or static.
2. Adding `if (!deviceResources.compile)` before creating a new `CompileTraversal`

Here's a minimal example demonstrating the issue (and checking the frame commands in RenderDoc).
[vsgdraw.zip](https://github.com/vsg-dev/VulkanSceneGraph/files/14746325/vsgdraw.zip)

Would like some feedback on this issue and whether this is a design flaw of VSG, as creating new models on the fly and recompiling should not add a minimum of 16MB.

**Comment by robertosfield** [comment]
Thanks for the example, I can't test this right away, but will get to it in the next couple of days.

What I think should be happening is the vsg::Context managed by CompileManager should be sharing MemoryBufferPool per vsg::Device, rather creating a new one like it sounds like it is doing right now.

Perhaps assigning a MemoryBufferPool to vsg::Device would make sense.  Once I've tested the example provided against VSG master and investigated what is happening in CompileManager/CompileTraversals/Context I will ponder on what is the best way to ensure everything that can be shared is shared.

**Comment by robertosfield** [comment]
I have just created an compile-able test program using the attached CMakeLists.txt:

[CMakeLists.txt](https://github.com/vsg-dev/VulkanSceneGraph/files/14762148/CMakeLists.txt)

This creates an executable in bin/memoryissue.  When I run it it runs super slow which is strange, I have only just started investigating so don't have any conclusions.

The scene graph creation is odd though, it uses viewer->compile() repeatedly, viewer->compile() is meant to be called just once before the main loop starts.  The correct way to incremental compilation as you create new subgraphs is to do as the [vsgdynamicload](https://github.com/vsg-dev/vsgExamples/blob/master/examples/threading/vsgdynamicload/vsgdynamicload.cpp) example does and use the vsg::CompileManager to do the compile of the new subgraph.

**Comment by robertosfield** [comment]
I was perplexed why 100 subgraphs containing just 10,000 triangles each would be running at 4fps on my Geforce 2060 when it's just one triangle repeated, then it dawned on me that it's 100,000 triangles drawn on top of each other so the when the triangle is occupying most of the window it's got a massive level of over-draw.

Running the example with --st to open a small test 192x108 window with vsync off I get 675fps for the same dataset... So this particular test is mostly an overdraw test which rather takes away from the actual problem of interest - incremental compilation.

**Comment by TP-David** [comment]
Replacing the viewer->compile() with a compileManager in our frame loop appears to have solved the issue. Thanks!

I suppose it will make a difference, performance wise, between passing the scene root into the compileManager or only the affected objects that have been added. We will need to investigate this further on our side.

**Comment by robertosfield** [comment]
Yes it will improve performance:

1. Reducing memory usage because the vsg::DeviceMemoryPool is properly shared over subsequent compile calls.
2.  Just traversing the new subgraphs rather than whole scene graph
3. Creation once of all the resources to do compilation, then reuse on subsequent compiles

As well as calling compileManager->compile(..) you'll also use the vsg::CompileResult it returns to update the viewer so it knows about any additional resources/settings that the new subgraphs requires, you do this via the vsg::updateViewer(..) function.  Look at the vsgdynamicload example to see how this is done.
