### ISSUE TITLE
Memory issue about PageLod

### ISSUE THREAD

**Issue by zhuzhiyong8679** [vsg-dev/VulkanSceneGraph#1148]
Hello, when I read DSM data format using VSG, the memory usage keeps increasing as the viewport moves. Do you know where the problem might be? In OSG, nodes that are not visible in the PagedLOD are removed to release memory, but it seems VSG does not dynamically load and unload nodes.

**Comment by zhuzhiyong8679** [comment]
At the same time, when using vsgExample, the memory keeps increasing without releasing as the viewpoint moves, just like the case with PagedLOD example.

**Comment by robertosfield** [comment]
The vsg::DatabasePager that manages the loading/expiry of no longer required subgraphs as target number of PagedLOD's that it uses as a guide.  It'll keep loading new tiles until the target is hit then will expirty no PagedLODs that are no longer visible.

vsgviewer and vsgpagedlod examples have a --maxPagedLOD <target> command line parameter that you can use to set the target.  Programmatically it is )from vsgviewer.cpp):

~~~ cpp
task->databasePager->targetMaxNumPagedLODWithHighResSubgraphs = maxPagedLOD;
~~~

**Comment by zhuzhiyong8679** [comment]
> The vsg::DatabasePager that manages the loading/expiry of no longer required subgraphs as target number of PagedLOD's that it uses as a guide. It'll keep loading new tiles until the target is hit then will expirty no PagedLODs that are no longer visible.
> 
> vsgviewer and vsgpagedlod examples have a --maxPagedLOD command line parameter that you can use to set the target. Programmatically it is )from vsgviewer.cpp):
> 
> ```c++
> task->databasePager->targetMaxNumPagedLODWithHighResSubgraphs = maxPagedLOD;
> ```

Thank you for your answer. I will continue to try.

**Comment by zhuzhiyong8679** [comment]
> @zhuzhiyong8679 As a general note, generic reports of issues without a specific explanation of how to reproduce are fare less useful that specific instructions where we can run our own test to reproduce the issue.
> 
> Information about the hardware, OS, VSG version and the data used are also really helpful.



> @zhuzhiyong8679 As a general note, generic reports of issues without a specific explanation of how to reproduce are fare less useful that specific instructions where we can run our own test to reproduce the issue.
> 
> Information about the hardware, OS, VSG version and the data used are also really helpful.
    viewer->assignRecordAndSubmitTaskAndPresentation({ commandGraph });

    // compile all Vulkan objects and transfer image, vertex and primitive data to GPU
    viewer->compile();

    int maxPagedLOD = 5;
    if (maxPagedLOD > 0)
    {
       
        for (auto& task : viewer->recordAndSubmitTasks)
        {
            if (task->databasePager) task->databasePager->targetMaxNumPagedLODWithHighResSubgraphs = maxPagedLOD;
        }

    }
};

Hello, I just tried setting targetMaxNumPagedLODWithHighResSubgraphs. When the value is set low, memory growth is slow; when the value is set high, growth is fast. PagedLOD is indeed unloaded, but it seems that memory is still not fully released. The version of vsg I am using is 1.1.2-win11-vs2022. You can try it yourself and verify that memory is not being released completely.

> vsg::DatabasePager 管理不再需要的子图的加载/过期，作为它用作指导的 PagedLOD 的目标数量。它将继续加载新图块，直到命中目标，然后不再可见的 PagedLOD 就会过期。
> 
> vsgviewer 和 vsgpagedlod 示例有一个 --maxPagedLOD 命令行参数，您可以使用它来设置目标。从编程上来说，它是来自 vsgviewer.cpp）：
> 
> ```c++
> task->databasePager->targetMaxNumPagedLODWithHighResSubgraphs = maxPagedLOD;
> ```

Hello, I just tried setting targetMaxNumPagedLODWithHighResSubgraphs. When the value is set low, memory growth is slow; when the value is set high, growth is fast. PagedLOD is indeed unloaded, but it seems that memory is still not fully released. The version of vsg I am using is 1.1.2-win11-vs2022. You can try it yourself and verify that memory is not being released completely.I also set maxtargetMaxNumPagedLODWithHighResSubgraphs for pageLod in VSG_EXAMPLES examples. It is working, but memory still doesn't seem to be fully released.
<img width="942" alt="1712654245467" src="https://github.com/vsg-dev/VulkanSceneGraph/assets/100345032/687c2be0-9cfb-44fa-9dbc-ee8f6069d77a">

**Comment by zhuzhiyong8679** [comment]
> @zhuzhiyong8679 As a general note, generic reports of issues without a specific explanation of how to reproduce are fare less useful that specific instructions where we can run our own test to reproduce the issue.
> 
> Information about the hardware, OS, VSG version and the data used are also really helpful.
Hello, I just tried setting targetMaxNumPagedLODWithHighResSubgraphs. When the value is set low, memory growth is slow; when the value is set high, growth is fast. PagedLOD is indeed unloaded, but it seems that memory is still not fully released. The version of vsg I am using is 1.1.2-win11-vs2022. You can try it yourself and verify that memory is not being released completely.I also set maxtargetMaxNumPagedLODWithHighResSubgraphs for pageLod in VSG_EXAMPLES examples. It is working, but memory still doesn't seem to be fully released.
<img width="942" alt="1712654245467" src="https://github.com/vsg-dev/VulkanSceneGraph/assets/100345032/687c2be0-9cfb-44fa-9dbc-ee8f6069d77a">

**Comment by robertosfield** [comment]
The VSG caches GPU memory in the vsg::DeviceMemoryPool so it can be later reused so once that's allocated it'll be kept around.

The CPU memory will be released and then reused, but again there is the vsg::Allocator that does block allocation of memory for performance reasons.

The normal way to use paged databases is to set the MaxPagedLOD around 1000 to 2000 and let memory be used up and recycled as required. Modern systems can often even handle higher numbers of MaxPagedLOD.  The higher the number the more of the scene will be kept in memory and can be returned to without needing to repaging data back in.

Unless you have a specific memory over-use issue I would suggest not getting too worried about memory consumption, what should happen is as you move around the scene memory will be used up until the targets are hit then the VSG should use that as a limit and work with the memory it's already allocated.
