### ISSUE TITLE
Equivalent missing to osgUtil::PolytopeIntersector 

### ISSUE THREAD

**Issue by TP-David** [vsg-dev/VulkanSceneGraph#1152]
Hi Robert,
Our team has been using osgUtil::PolytopeIntersector, yet in VSG there's only vsg::LineSegmentIntersector.
We chose not to use LineSegmentIntersector in OSG because it didn't catch lines or points. Would you consider creating an equivalent in VSG for polytope or can we do it ourselves?

As an example of the issue, adding `state.wireframe=true` to the keyPress method in IntersectionHandler (vsgintersection) does not trigger hits on newly added shapes

Thanks,
David

**Comment by robertosfield** [comment]
An vsg::PolytopeInersector is something I've had in mind but it's just been a matter of scheduling such work with the other tasks that have filled my time since writing vsg::LineSegmentIntersector.

This is something that users could tackle ( & ideally open source :-), if they can't wait for me to tackle it.

**Comment by zhuzhiyong8679** [comment]
> 你好，Robert， 我们的团队一直在使用 osgUtil::PolytopeIntersector，但在 VSG 中只有 vsg::LineSegmentIntersector。 我们选择不在 OSG 中使用 LineSegmentIntersector，因为它无法捕获线或点。您是否会考虑在 VSG 中为多面体创建一个等效项，还是我们可以自己做？
> 
> 作为问题的一个示例，添加`state.wireframe=true`到 IntersectionHandler (vsgintersection) 中的 keyPress 方法不会触发对新添加的形状的点击
> 
> 谢谢， 大卫

Hello, I also encountered the same problem of picking points. How did you solve it.

**Comment by zhuzhiyong8679** [comment]
> Hi Robert, Our team has been using osgUtil::PolytopeIntersector, yet in VSG there's only vsg::LineSegmentIntersector. We chose not to use LineSegmentIntersector in OSG because it didn't catch lines or points. Would you consider creating an equivalent in VSG for polytope or can we do it ourselves?
> 
> As an example of the issue, adding `state.wireframe=true` to the keyPress method in IntersectionHandler (vsgintersection) does not trigger hits on newly added shapes
> 
> Thanks, David

Hello, I also encountered the same problem of picking points. How did you solve it.

**Comment by robertosfield** [comment]
vsg::PolytopeVisitor is now implemented : #1287.
