### ISSUE TITLE
Validation error: vkCmdCopyBufferToImage

### ISSUE THREAD

**Issue by TP-David** [vsg-dev/VulkanSceneGraph#1301]
Hello,
After the commit "Merge pull request #1279 from vsg-dev/Compile_Using_TransferData" on Sep 18 we have started getting this validation error when initializing VSG, originating from ImageView.cpp when calling Viewer::recordAndSubmit. Is this a known issue?

The width, height of the image data in question is 3x256 if that helps to know.

**VUID-vkCmdCopyBufferToImage-dstImage-07978(ERROR / SPEC): msgNum: -1680595593 - Validation Error: [ VUID-vkCmdCopyBufferToImage-dstImage-07978 ] Object 0: handle = 0x136ab1435e0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x88f3210000000302, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x9bd42577 | vkCmdCopyBufferToImage: pRegion[0] bufferOffset 0x2b02c2 must be a multiple 4 if using a depth/stencil format (VK_FORMAT_D32_SFLOAT). The Vulkan spec states: If pname:dstImage has a depth/stencil format, the bufferOffset member of any element of pRegions must be a multiple of 4 (https://vulkan.lunarg.com/doc/view/1.3.250.1/windows/1.3-extensions/vkspec.html#VUID-vkCmdCopyBufferToImage-dstImage-07978)
    Objects: 2
        [0] 0x136ab1435e0, type: 6, name: NULL
        [1] 0x88f3210000000302, type: 10, name: NULL**

**Comment by robertosfield** [comment]
I think this issue has probably been resolved, and as I've not had any feedback to the contrary I'm closing this Issue.

**Comment by TP-David** [comment]
Pulled VSG from Oct 17 (0edfbf10..) and error still occurs.
Have not been able to reproduce it in vsgExamples, it seems limited to our use case. We are delaying creating a Viewer, populating our Views first, admittedly it's a bit hacky and built on top of a legacy QT codebase.
WIll try to recreate in vsgExamples when I have the time.

**Comment by robertosfield** [comment]
I was about to tag the VulkanSceneGraph v-1.1.8 release but I don't want to push it out with a regression so any help you can provide on recreating this error would be appreciated.  Thanks.

**Comment by TP-David** [comment]
Was able to reproduce the error in vsgdraw.cpp. It is related to "stride" in Data::Properties. In our application, I found that the image with the stride of 16 is created in GpuLayoutTechnique when loading text (times.vsgt).

Replace the single texture on line 73 with the following and you'll see it:

```
   windowTraits->debugLayer = true;
   ...
    // create texture image and associated DescriptorSets and binding
    vsg::Data::Properties prop{ VK_FORMAT_R32G32B32A32_SFLOAT };
    prop.stride = 16;
    auto texture1 = vsg::DescriptorImage::create(vsg::Sampler::create(), vsg::ubvec4Array2D::create(1, 1, vsg::Data::Properties{ VK_FORMAT_R8G8B8A8_UNORM }));
    auto texture2 = vsg::DescriptorImage::create(vsg::Sampler::create(), vsg::ubvec4Array2D::create(1, 1, prop));

    auto descriptorSet = vsg::DescriptorSet::create(descriptorSetLayout, vsg::Descriptors{ texture1 ,texture2 });
```
texture1 sets "offset" to 4 which is not divisible by 16.

**Comment by robertosfield** [comment]
Great detective work.  Will recreate it and have a bash at fixing it.

**Comment by robertosfield** [comment]
I made the modification but the inconcistency between the Properties.dataType and the vsg::ubvec4::create() was a bit jarring so I changes the texture2 entry simply to:

~~~ cpp
    auto texture2 = vsg::DescriptorImage::create(vsg::Sampler::create(), vsg::vec4Array2D::create(1, 1, vsg::Data::Properties{ VK_FORMAT_R32G32B32A32_SFLOAT }));
~~~

And still see the Vulkan Validation error:

~~~ sh
$ vsgdraw -d
VUID-vkCmdCopyBufferToImage-dstImage-07975(ERROR / SPEC): msgNum: 902809310 - Validation Error: [ VUID-vkCmdCopyBufferToImage-dstImage-07975 ] Object 0: handle = 0x55aa70f29f40, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0xab64de0000000020, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x35cfc6de | vkCmdCopyBufferToImage(): pRegions[0].bufferOffset (4) must be a multiple of VK_FORMAT_R32G32B32A32_SFLOAT texel size (16). The Vulkan spec states: If dstImage does not have either a depth/stencil format or a multi-planar format, then for each element of pRegions, bufferOffset must be a multiple of the texel block size (https://vulkan.lunarg.com/doc/view/1.3.290.0/linux/1.3-extensions/vkspec.html#VUID-vkCmdCopyBufferToImage-dstImage-07975)
    Objects: 2
        [0] 0x55aa70f29f40, type: 6, name: NULL
        [1] 0xab64de0000000020, type: 10, name: NULL
~~~

I will now begin digging into what might need tweaking.

**Comment by robertosfield** [comment]
I have checked in a change to use the Data::stride() and this fixes the Vulkan Validation error: 8c6d1fb7dd9dc2716fb3b6e4b344f288835bc1b8

Could you test VSG master with your application and let me know how you get on. Thanks.

**Comment by TP-David** [comment]
Thanks for your quick patch!
Pulled your commit and the error appears fixed. I think this can be closed.

On another note, we have finished implementing the PolytopeIntersector and it works great, just had to re-implement our custom instancing transforms on the CPU side with a new ArrayState.

**Comment by robertosfield** [comment]
Thanks for the testing and positive feedback :-)
