### ISSUE TITLE
LunarG no longer offers the 1.3.224.1 Vulkan SDK used by CI

### ISSUE THREAD

**Issue by AnyOldName3** [vsg-dev/VulkanSceneGraph#1303]
LunarG no longer offers the 1.3.224.1 Vulkan SDK used by CI. This means that anyone who doesn't already have it in their fork's CI cache can't run the VSG's CI.

Changing the version requested will probably work, although I see that with 1.3.261.1, they switched the compression from `.gz` to `.xz`, so the Action we're using may need to be switched if we bump the version a long way and it turns out it makes assumptions about the extraction command to run.

**Comment by AnyOldName3** [comment]
Simply bumping the version apparently doesn't work. It's not just the change from `.gz` to `.xz` for the Linux SDK - MacOS has also changed from a `.dmg` to a `.zip`.

**Comment by robertosfield** [comment]
The automated builds all ran OK yesterday afternoon, how soon will we need to update our build scripts?

**Comment by AnyOldName3** [comment]
They work fine when it's you running them as they use your CI cache. When I run them, I don't have access to your cache (I guess at some point, mine expired and was purged, but it'd be like that for any new contributors, too), they fail immediately due to this.

**Comment by robertosfield** [comment]
I'm open to suggestions of how to resolve this issue.  I am happy to create a branch that could be experimented with.  I have quite a few tasks on my plate already so don't want to end up diverted down yet another rabbit hole that doesn't take me closer to get a dev release out and eventually back to tackle some client work.

**Comment by AnyOldName3** [comment]
The four sensible options would be:
* Create an issue report for the current Action at https://github.com/humbletim/install-vulkan-sdk and hope they get around to fixing it and make a new release.
* Use a different Action that's hopefully more up-to-date.
* Manually install the Vulkan SDK instead of using a premade Action.
* Install a newer version that the current premade Action can still handle.
They're not all the same amount of effort and won't all take the same amount of time to materialise. It's tempting to just report the problem and switch to a newer-but-still-old build in the meantime as that won't take much effort to make the immediate problem go away, and will hopefully make the long-term problem go away before it turns into a short-term one.

**Comment by AnyOldName3** [comment]
And I tried with 1.3.250.1, when the archive formats hadn't been switched yet, but it still fails on MacOS, complaining it can't mount a `.exe` as a `.dmg`, which is understandable, except the URL says `.dmg`.

**Comment by AnyOldName3** [comment]
It definitely looks like a `.dmg` image when I download and open it myself, even from Windows, so something's wonky there.

**Comment by AnyOldName3** [comment]
Looks like that's down to https://github.com/humbletim/install-vulkan-sdk/commit/413f03770abfddd5c78b40183e7f2acd5cab5732 not having made it into a release yet.

**Comment by AnyOldName3** [comment]
https://github.com/vsg-dev/VulkanSceneGraph/pull/1306

**Comment by robertosfield** [comment]
@AnyOldName3 I believe we can now close this issue?

**Comment by AnyOldName3** [comment]
Yes, this can now be closed.
