### ISSUE TITLE
shader link failure using glsl 15.0.0 when in/out variables are different name (same location)

### ISSUE THREAD

**Issue by theodoregoetz** [vsg-dev/VulkanSceneGraph#1344]
With the latest `main` branch of glslang on Linux (Fedora 41), as well as glslang's `15.0.0` tag, the shader programs fail to link when any vertex output variable does not have the exact same name as the associated fragment input variable (where the location is the same value).

Running the `vsgtriangles` example built against glslang 15 results in the following error:

```
Warning: Program failed to link.
Warning: glslang info log: ERROR: Linking vertex and fragment stages: Input 'color' in fragment shader has no corresponding output in vertex shader.
```

In that example, the vertex output variable `outColor` should be matched to the fragment input variable `color` but it is not. Changing the two variables to something like `vtxOutColor` in both shader stages allows glsl to link the program and continue correctly. The problem is that the name really shouldn't matter according to the documentation concerning the separate shader objects extension (see "Section 4.3.4" here: https://registry.khronos.org/OpenGL/extensions/ARB/ARB_separate_shader_objects.txt)

```glsl
#version 450
#extension GL_ARB_separate_shader_objects : enable
layout(push_constant) uniform PushConstants { mat4 projection; mat4 modelView; };
layout(location = 0) in vec3 vertex;
layout(location = 1) in vec4 color;
layout(location = 2) out vec4 outColor;       // <- VERTEX OUTPUT VARIABLE
out gl_PerVertex { vec4 gl_Position; };
void main()
{
    outColor = color;
    gl_Position = (projection * modelView) * vec4(vertex, 1.0);
}
```

```glsl
#version 450
#extension GL_ARB_separate_shader_objects : enable
layout(location = 2) in vec4 color;               // <- FRAGMENT INPUT VARIABLE
layout(location = 0) out vec4 outColor;
void main()
{
    outColor = color;
}
```

Additional information: There may be a bug in glslang or perhaps it's associated with the `GL_ARB_separate_shader_objects` extension and may also have problems on macOS as per https://github.com/KhronosGroup/SPIRV-Cross/issues/168 - as far I understand this extension it need only be enabled in the shader code itself and should allow in/out variables to have different names as long as the locations and types match.

I am not sure if glslang 15 now requires some additional step to really enable separate shader objects or not but using glsl version 14 still works as expected (the above shaders link just fine).

**Comment by robertosfield** [comment]
Could you generate a PR for this fix.  Thanks.

**Comment by theodoregoetz** [comment]
According to the glsl documentation, the shader code is correct and should link just fine. The "fix" of making the variables the same name should not be needed here and I consider that a workaround rather than a fix. I don't know if this a VSG bug (the way it's using glsl) or a glsl bug (introduced in 15.0.0) or a more strict compiler setting, and therefore I don't know where to fix it.

**Comment by robertosfield** [comment]
I also think the glsl is valid, but is less easy to follow having different names so I've tweaked the shaders to resolve this.  Tested with glslang-15 built from source: c27a5a8f86b2cbf9e28691d8dbe042afa592cfca
