### ISSUE TITLE
can't read .vsgt

### ISSUE THREAD

**Issue by yexiaoshen** [vsg-dev/VulkanSceneGraph#150]
auto loaded_scene = vsg::read_cast<vsg::Node>("E:\\WorkspaceC++\\vsgExamples\\data\\models\\teapot.vsgt", options);
this code return null. I track code，at line 120 in “AsciiInput.cpp”，       
 if (auto itr = objectIDMap.find(id); itr != objectIDMap.end())
        {
            //std::cout<<"Returning existing object "<<itr->second.get()<<std::endl;
            return itr->second;
       }
this code "return itr->second;"  can executed，but return null！ What's the reason？
thanks！

**Comment by vsg-dev** [comment]
I recently changed the file format but didn't get around to updating this file, I'll hunt down the original file and regenerate it. I wrote about this change last Friday:

    https://groups.google.com/forum/#!topic/vsg-users/DZE0L67cEcU

**Comment by vsg-dev** [comment]
I have just checked in a fix for the problem loading teapot.vsgt:

    https://github.com/vsg-dev/vsgExamples/commit/c191172c1179115f05554b6b77c304f2ca044c8e

Could you update to vsgExamples master.

**Comment by yexiaoshen** [comment]
ok，Thanks a million！
