### ISSUE TITLE
Threading issue with OperationThreadQueue::Latch

### ISSUE THREAD

**Issue by mp3butcher** [vsg-dev/VulkanSceneGraph#160]
**Describe the bug**
MT Freeze (Latch stays locked after count reach 0)

**To Reproduce**
[video](https://streamable.com/gsqyld)(vgssubpass exhibits same issue)
The bug emerged when i used Latch in vsg-dev:subpass_threading branch...
Hard to reproduce, but launching lot of instances of the **vsgexecutecommandbuffers** example yield application freeze in some windows 
(launch 6 instances and swap between windows seems to be a good way to provoke the bug)

**Desktop**
 - OS: Ubuntu 18.04.1

**Additional context**
The issue might affect DataPager but harder to reproduce
I fix it locally with https://github.com/vsg-dev/VulkanSceneGraph/commit/b4429c414c0fa10bc81e92e89dcbdec53dabda14 using a mutex instead of a condition_variable

**Comment by robertosfield** [comment]
The way you test multi-threading is my running multiple threads within a single application, not by running lots of separate programs.  See a problem behavior when you are thrashing your window manager is a stress test of completely different kind.  It could be that you are hitting a window manager issue, or a driver issue, or CPU bug or a memory bug.

The way to create a stress test for the VSG threads is to write a single application with multiple threads that contend over the same resources.

I'm closing this "Issue" as it's a dubious test, on an experimental branch that has no relevance to master.  Any of the work that may make in from the experimental branch will be thoroughly vetted.  If then we find problems we need to establish it with a single application. multi-threaded test.

**Comment by mp3butcher** [comment]
If it was a driver bug or a window manager issue my fix wouldn't work. 
But it does... You're bad faith

**Comment by robertosfield** [comment]
Threading problems are often a very difficult to pin down and fix.  Some
"fixes" can just avoid a race condition but aren't fixes at all.  In this
instance you "fixes" are sledge hammer hacks that change the conditions
without actual pinpointing and fixing the actual bug if an actual bug
actually exists.

What you are reading as bad faith is years of experience of dealing with
threading problems and how it's most effective to deal with them.  Me
saying you aren't helping progress things forward on this is not some
random statement.  You are doing stuff that it's clear you don't yet have
the experience and insight to tackle.
