### ISSUE TITLE
window creation error on ubuntu 20 lts

### ISSUE THREAD

**Issue by neshume** [vsg-dev/VulkanSceneGraph#177]
event not handled, response_type = 0 returned when window is created on ubuntu 20 LTS

**Comment by robertosfield** [comment]
?
You'll need to give us more information about the circumstances of the error such as how to go about reproducing it ourselves. As things stand it's too cryptic to be able to relate it to anything in particular.  

Was this issue one generated when running one of the vsgExamples like vsgdraw?  What is it with your own application?  What was the console output.  Does it crash?  If so what's the stack trace.

**Comment by neshume** [comment]
This error is generated in window init in vsgDraw in vsgExamples of course on master vsg branch. same version works perfectely on both ubuntu 18.04 and 19.
I will investigate further to understand where this cryptic error comes from. I suspect window creation :o)

**Comment by robertosfield** [comment]
Which window manager are you using?

Could you try another?

**Comment by robertosfield** [comment]
On Wed, 13 May 2020 at 19:46, Robert Osfield <robert.osfield@gmail.com>
wrote:

> Could you try another?
>

I suggest this to help characterise the problem better, it's obviously not
a solution :-)

Would also be worth looking at the version of X11, Xcb on the different
versions of Ubuntu.

**Comment by neshume** [comment]
using standard ubuntu unmodified. not even the problematic wayland. will try to change. investigating further...

**Comment by robertosfield** [comment]
Does the window work at all?  Or is it just a new warning?

**Comment by neshume** [comment]
the mystery is now solved. It seems that upgrade to ubuntu 20 messed up the graphics drivers and reinstall of the drivers (nvidia) did not help. What did help is delete the intel_icd.x86_64.json from /usr/share/vulkan/icd.d    . vulkan nvidia now works perfectely and window is created. The issue was vulkan implementation on ubuntu 20 that got broken and gave no error messages including vulkaninfo. so It's an ubuntu + nvidia issue.

**Comment by robertosfield** [comment]
Did other vulkan applications work before your fix?

I will be upgrading to 20.04 LTS but not this week, need to get threading working fully first :-)

**Comment by neshume** [comment]
I checked initialization only not visual but it seems that vulkan was broken regarding window surface but did not report it as an error. Be carefull with the upgrade and good luck. backup before!!
