### ISSUE TITLE
the visitor can't traverse statecamands

### ISSUE THREAD

**Issue by wadivision** [vsg-dev/VulkanSceneGraph#195]
**Is your feature request related to a problem? Please describe.**
Hi, Rebort!
I would like to replace the shader that in vsgt file with my shader while the program is running. So, I created a FindShaderVisitor class inherited from class vsg::Visitor. The object of class vsg::ShaderStage wasn't found！It looks like vsg doesn`t trasverse the vsg::StateCommand!

Is that your intention or  a miss？

My code is here

``` c++
 class FindShaderVisitor : public vsg::Visitor
    {
    public:
        FindShader(VkShaderStageFlagBits shaderType) :
            m_vkShaderType(shaderType) {}

      
        virtual void apply(vsg::ShaderStage& ss) override
        {
 //  ####### can't step into here
            if (ss.getShaderStageFlagBits() == m_vkShaderType)
            {
                vsg::ref_ptr<vsg::ShaderModule> shaderModule = vsg::ShaderModule::read("./myShader.vert.spv");
                ss.setShaderModule(shaderModule);
                ss.setEntryPointName(std::string("main"));
                return;
            }
            else
            {
                ss.traverse(*this);
            }
        }
        
        virtual void apply(vsg::StateCommand& cmd) override
        {
            cmd.traverse(*this);
        }

        virtual void apply(vsg::StateGroup& node) override
        {
            node.traverse(*this);
        }

        virtual void apply(vsg::Node& node) override
        {
            node.traverse(*this);
        }

    private:
        VkShaderStageFlagBits m_vkShaderType;
    };
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by robertosfield** [comment]
Presently the VSG visits StateCommands and it's up to subclasses to decide whether to Traverse.  Currently the BindGraphicsPipeline StateCommand doesn't implement a traverse, and The GraphicsPipeline that it holds doesn't implement traverse.

I haven't yet got a feel for how far we should push traversing/support for visitors into the lower level classes, if it's something that is often useful then it's something that it should be included, if it's used rarely then it is probably inappropriate to add extra code to support niche usage as long as there is some other reasonable means to achieve what the users desires.

The way I have tackled things so far is to not implement things till we have a concrete usage case that justifies it's existence, once we come across cases then it;s a matter of weighing up how come a usage case and the work required in the core VSG vs user space to implement that usage case.

At present you'd need to implement a apply(vsg::BindGraphicsPipeline&) and then get it's GraphicsPipeline then traverse through it's children.

As small note on on your example code above.  It's sufficient to implement a apply(vsg::Node& node) { node.traverse(*this); } then you won't need to implement the rest of the apply() except a BindGraphicsPipeline).

If we decide that it's worthwhile implementing BindGraphicsPipeline::traverse() and GraphicsPipeline::traverse() then you could simplify it further.

For general info, a StateCommand is a leaf node in the scene graph, while children of StateCommand aren't nodes, but properties of those children.  So far it's mostly just the nodes that I've implemented traverse() for as these are the elements are actively traversed in normal operation.

**Comment by wadivision** [comment]
Thanks for your reply,Robert!

I still can't step into `apply(vsg::BindGraphicsPipeline&)`  , but I can step into ‘apply(vsg::StateGroup&)’. And then I got BindGraphicsPipeline , GraphicsPipeline, ShaderStage ...

I will close this issue! Thank you very much！

**Comment by robertosfield** [comment]
On Fri, 12 Jun 2020 at 08:48, wadivision <notifications@github.com> wrote:

> Thanks for your reply,Robert!
>
> I still can't step into apply(vsg::BindGraphicsPipeline&) , but I can
> step into ‘apply(vsg::StateGroup&)’. And then I got BindGraphicsPipeline ,
> GraphicsPipeline, ShaderStage ...
>
I was about to suggest that the UpdatePipeline visitor in RenderGraph.cpp
illustrates what to do assuming that the StateGroup's StateCommand were
being traversed but now I see that it manually does it.  I'll contemplate
whether we should add the traversal of the StateCommands to the
StateGroup::traverse().  It's might not always want to traverse the
StateCommands so it's not a clear cut decision.

For reference, the usage I was thinking of is in:

https://github.com/vsg-dev/VulkanSceneGraph/blob/master/src/vsg/viewer/RenderGraph.cpp

**Comment by wadivision** [comment]
> On Fri, 12 Jun 2020 at 08:48, wadivision ***@***.***> wrote: Thanks for your reply,Robert! I still can't step into apply(vsg::BindGraphicsPipeline&) , but I can step into ‘apply(vsg::StateGroup&)’. And then I got BindGraphicsPipeline , GraphicsPipeline, ShaderStage ...
> I was about to suggest that the UpdatePipeline visitor in RenderGraph.cpp illustrates what to do assuming that the StateGroup's StateCommand were being traversed but now I see that it manually does it. I'll contemplate whether we should add the traversal of the StateCommands to the StateGroup::traverse(). It's might not always want to traverse the StateCommands so it's not a clear cut decision. For reference, the usage I was thinking of is in: https://github.com/vsg-dev/VulkanSceneGraph/blob/master/src/vsg/viewer/RenderGraph.cpp

Oh，I got it. Thanks！
