### ISSUE TITLE
vec4.h operator != typo bug

### ISSUE THREAD

**Issue by dchristopherfennell** [vsg-dev/VulkanSceneGraph#198]
Hello,

vsg/maths/vec4.h has a typo bug with the **!=** operator.

return lhs[0] == rhs[0] || lhs[1] != rhs[1] || lhs[2] != rhs[2] || lhs[3] != rhs[3];

should be

return lhs[0] **!=** rhs[0] || lhs[1] != rhs[1] || lhs[2] != rhs[2] || lhs[3] != rhs[3];

And now that I look at it, so does vec2.h, vec3.h

Thanks,
DC

**Comment by robertosfield** [comment]
Ooops. Classic copy and paste error duplicated three times.

Thanks for spotting the error.  I've just checked in a fix:

https://github.com/vsg-dev/VulkanSceneGraph/commit/441cd339c92bf1d26d748c678c56597a6120191a
