### ISSUE TITLE
[Question] Integration with QML or other non-VSG rendering setups

### ISSUE THREAD

**Issue by target-san** [vsg-dev/VulkanSceneGraph#211]
Hello!

I am looking for ways to integrate VSG with external GUI layout system, namely QML. In particular, I want VSG to render scene in a framebuffer which will be then drawn as part of control rendering.
According to QML examples, one is able to obtain VkInstance, VkPhysicalDevice, VkDevice and VkCommandBuffer. Unfortunately, VSG seems to be not designed to plug in with existing raw Vulkan setup. At least I see no way to construct vsg::Device and similar objects from existing handles.

Can anyone please advice on where should I look for?

Thanks

**Comment by robertosfield** [comment]
I'm not familiar with with QML so can't comment on the specifics of integration.  The vsg-users forum is the best place to ask questions as it'll be a higher profile place for discussion and more likely to get feedback with users with Qt experience, and will serve as a better place for others to learn from.

**Comment by target-san** [comment]
Sorry, I guess I missed forum link somehow. Thanks for help!
