### ISSUE TITLE
Validation error upon vkCreateImage when windowTraits->samples != VK_SAMPLE_COUNT_1_BIT

### ISSUE THREAD

**Issue by franciszhi** [vsg-dev/VulkanSceneGraph#219]
**Describe the bug**
When `windowTraits->samples` is set to a value more than VK_SAMPLE_COUNT_1_BIT, validation error [ VUID-VkImageCreateInfo-usage-00963 ] is reported:
```
VUID-VkImageCreateInfo-usage-00963(ERROR / SPEC): msgNum: 1665303278 - Validation Error: 
[ VUID-VkImageCreateInfo-usage-00963 ] Object 0: handle = 0x55c743cd2b10, type = 
VK_OBJECT_TYPE_DEVICE; | MessageID = 0x634282ee | vkCreateImage(): Transient attachment 
image with incompatible usage flags set. The Vulkan spec states: If usage includes 
VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT, then bits other than 
VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT, and 
VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT must not be set 
(https://vulkan.lunarg.com/doc/view/1.2.148.0/linux/1.2-extensions/vkspec.html#VUID-VkImageCreateInfo-usage-00963)
    Objects: 1
        [0] 0x55c743cd2b10, type: 3, name: NULL
```

**To Reproduce**
1. In repo https://github.com/vsg-dev/vsgExamples
2. Go to Desktop/vsgdraw/vsgdraw.cpp
3. After line 11 `windowTraits->apiDumpLayer`, add `windowTraits->samples = VK_SAMPLE_COUNT_2_BIT;`
4. Modify line 69 from `vsg::MultisampleState::create(),` to `vsg::MultisampleState::create(VK_SAMPLE_COUNT_2_BIT),`
5. Compile and run `vsgdraw --debug`
6. You shall see validation error [ VUID-VkImageCreateInfo-usage-00963 ]

**Comment by robertosfield** [comment]
Thanks for the note.  The vsgviewer example has support for enabling multi-sampling, so to test the issue I ran vsgviewer as below with the debug layer enabled and got the same error.

vsgviewer data/models/teapot.vsgt --samples 4 -d
VUID-VkImageCreateInfo-usage-00963(ERROR / SPEC): msgNum: 1665303278 - Validation Error: [ VUID-VkImageCreateInfo-usage-00963 ] Object 0: handle = 0x55936c2b03e0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x634282ee | vkCreateImage(): Transient attachment image with incompatible usage flags set. The Vulkan spec states: If usage includes VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT, then bits other than VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT, and VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT must not be set (https://vulkan.lunarg.com/doc/view/1.2.154.0/linux/1.2-extensions/vkspec.html#VUID-VkImageCreateInfo-usage-00963)
    Objects: 1
        [0] 0x55936c2b03e0, type: 3, name: NULL

I have had a quick look at the PR and this gives me a clue to what might need fixing, but the actual fix feels pretty clunky so I'll need to have a deep dive into the topic and see how to resolve it more cleanly.

**Comment by robertosfield** [comment]
A quick update. I'm currently assessing the places that Image::usage is set in the VSG and it looks likely that just moving where the values are so that the vsg::Image::compile(..) implementation no longer overrides the values is the appropriate fix.

**Comment by robertosfield** [comment]
Fixed :-)

I removed the override of the Image::usage and move the setting into the vsg::Image setup code inside DescriptImage. #221

**Comment by franciszhi** [comment]
@robertosfield, thanks for the fix, I like this fix as `info.usage` in `Image::compile` is reflecting `Image::usage` without modification.

**Comment by robertosfield** [comment]
On Fri, 13 Nov 2020 at 14:34, Francis Z Chong <notifications@github.com>
wrote:

> @robertosfield <https://github.com/robertosfield>, thanks for the fix, I
> like this fix as info.usage in Image::compile is reflecting Image::usage
> without modification.
>
This is really what I had in mind when I did the refactor of vsg::Image to
mirror the VkImageCreateInfo settings, the code was evolving away from
hardwired presets, but I hadn't yet completed the job... Today I think this
subtask is now complete :-)
