### ISSUE TITLE
Keyboard Issues

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/VulkanSceneGraph#224]
**Describe the bug**
Want I want: use key strokes to start functions in an VSG application. A simple handler has been written. Its only function is to give a response to key stroke 'i'. It is part of the example program 'KeyboardIssue'.

**To Reproduce**
1. Build the example program
2. Start it from a terminal window
3. Hit key 'i'

**Expected behavior**
On all operation systems I expect for one key hit exactly one response line in the terminal window.

**Screenshots**
![DoubleResponseOnSingleKeyHit_MacOS11](https://user-images.githubusercontent.com/31243285/99872348-855c8080-2be1-11eb-98f5-13e893a944c7.jpg)
On MacOS one key hit leads to two responses.
On Windows any key hit leads no response.
On Linux the key hit leads to one response, as it should be.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.0.1 X86_64
 - OS: Windows 10 Home 20H2
 - OS: Linux latest Ubuntu Desktop Intel 20.10
[KeyboardIssue.zip](https://github.com/vsg-dev/VulkanSceneGraph/files/5577309/KeyboardIssue.zip)

**Comment by robertosfield** [comment]
Thanks for the detailed report and test program.  Unfortunately, I don't
personally have access to Windows or macOS so will have to defer to others
for testing/help resolving platform specific issues on these OS's.  I'll
ping the vsg-users later if a quick resolution isn't possible,

Doe the window having focus make any difference to the results for you?

Could you add code to your test program that reports both the
KeyEvent::keyModified, keyBase and keyModified values so we can see what is
happening for all key presses.  For instance It may be that 'i' is a
modified 'I' under Windows.

It might also be useful to have keyPress and keyRelease tracked.

Perhaps it would be best for me to create a vsgExample to output these
values.  I'm currently working on implementing dynamic text so this might
be a good place to add UI test as well.

**Comment by rainergericke** [comment]
On Mac and Windows the VSG window has to have the focus. I added some lines to track also keyRelease events. They are not recognized on the Mac. On Windows neither keyPress events nor keyRelease events can be seen. 
I'm not a great expert in deep MacOS programming, but it could be the the keyRelease event that makes the second output, not correctly recognized as keyRelease event. Let the experts look at it.

The other method is to ask for keyEvents and report it. There is a difference between Mac and Windows:
On the Mac modifiers are only recognized together with a printing key like 'I'.
On Windows modifiers are recognized as single keystrokes. Printing keys to double events like on the Mac.
[KeyboardIssue2.zip](https://github.com/vsg-dev/VulkanSceneGraph/files/5577968/KeyboardIssue2.zip)

**Comment by robertosfield** [comment]
@tomhog does any of these Windows/macOS issues ring any bells?

**Comment by ahoarau** [comment]
@robertosfield Hello Robert, github actions could allow to easily test on all platforms

**Comment by robertosfield** [comment]
On Sat, 21 Nov 2020 at 18:01, Antoine Hoarau <notifications@github.com>
wrote:

> @robertosfield <https://github.com/robertosfield> Hello Robert, github
> actions could allow to easily test on all platforms
>

I'm not familiar with github actions.  Does it support interactive vulkan
applications?  That's what we'd need in this instance.

**Comment by ahoarau** [comment]
Sorry robert I misunderstood the issue + you already setup the ci.

**Comment by robertosfield** [comment]
@rainergericke I've now wrapped up the work on dynamic text so will now create a vsgExample that outputs the keyboard and mouse values, perhaps along the lines of the old osgkeyboard example.

First up I've run your KeyboardIssue example and confirm that it's working under Linux but without Windows or macOS that's all I can do in terms of testing.  To help find out what might be happening with the events I've extended the AppKeyboardHandler to test of 'I' and well as 'i', and test keyBase and keyModified:

class AppKeyboardHandler : public vsg::Inherit<vsg::Visitor, AppKeyboardHandler>
{
public:
    AppKeyboardHandler(vsg::Viewer* viewer)
        : m_viewer(viewer)
    {
    }
    void apply(vsg::KeyPressEvent& keyPress) override
    {
        if(keyPress.keyBase == 'i') {
            std::cout << "keyBase 'i' pressed " << ++m_i_keyBase_counter << " times.\n";
        }
        if(keyPress.keyModified == 'i') {
            std::cout << "keyModified 'i' pressed " << ++m_i_keyModified_counter << " times.\n";
        }
        if(keyPress.keyBase == 'I') {
            std::cout << "keyBase 'I' pressed " << ++m_I_keyBase_counter << " times.\n";
        }
        if(keyPress.keyModified == 'I') {
            std::cout << "keyModified 'I' pressed " << ++m_I_keyModified_counter << " times.\n";
        }
    }

private:
    size_t m_i_keyBase_counter = 0;
    size_t m_i_keyModified_counter = 0;
    size_t m_I_keyBase_counter = 0;
    size_t m_I_keyModified_counter = 0;
    vsg::observer_ptr<vsg::Viewer> m_viewer;
};

When I press 'i' then add the shift key and press i again for 'I' I get the follow results under Linux:
$ bin/KeyboardIssue 
keyBase 'i' pressed 1 times.
keyModified 'i' pressed 1 times.
keyBase 'i' pressed 2 times.
keyModified 'I' pressed 1 times.

Which is what I would expect.  I'm wondering if Windows and macOS have the meaning flipped.  FYI, I wrote the Linux Xcb support, while @tomhog wrote the Windows and macOS support so we may have ended up with different interpretations of what is meant by keyBase and ketModified.

**Comment by robertosfield** [comment]
@rainergericke I have been reviewing the Linux (Xcb_Window.cpp +.h) and the Windows (Win32_Window.cpp +.h) and it looks to me like in Xcb the unmodified 'i' key reports 'i', while under Windows the unmodified 'i' reports 'I'.  

At a guess I'd think that perhaps Windows keyModified will report 'i' when you press the 'i' key.  Could you test this as I can't as I don't have a Windows machine to test against.

I haven't looked at macOS, but am wondering if it's a similar story - the default unmodified might be 'I' and modified is 'i'.

If the above is correct then we are left with a decision to make about whether we standardize all keyBase values to work in the same case, or just leave it as the native value.  For portability of code I think it would best if keyBase behaved the same for all platforms, even if that means us changing it from the native interpretation.

**Comment by rainergericke** [comment]
I tested your code changes, to my surprised, it worked also on windows, but it's a good surprise. As you proposed, I started the program and pressed 'i' one time and then 'I' one time.  Here is the windows response:
![KeyboardIssue3Win10](https://user-images.githubusercontent.com/31243285/100465236-3c1f9b80-30cf-11eb-9770-1931146d0125.png)

On the Mac I get this, everything seems to be doubled:
<img width="844" alt="KeyboardIssue3MacOS" src="https://user-images.githubusercontent.com/31243285/100465340-6709ef80-30cf-11eb-9baa-3a46e64496f1.png">

**Comment by robertosfield** [comment]
Thanks for the testing.  This starts to make the picture clearer.  I would like to have the VSG work the same on each platform as much as possible so it would make sense to standardize the interpretation of what keyBase would be.  Modified vs unmodified keys would normally be interpreted as the keycode you get when press shift to get 'A' ad unmodified i.e. no shift you'd get 'a' - which is what I'm getting with Xcb and what your assumption was.

I'm curious, what made you assume 'i' would be the keyBase rather than 'I'?

I haven't looked at the MacOS side yet, t don't want to confuse my little brain too much with different combinations of problems at once.  I will look at the next.

**Comment by robertosfield** [comment]
I have checked in the beginnings of vsginput example that will report event data.  Right now it just outputs keyboard and mouse events to the console. It's get near end of working day so I wont' be able to do too much more.

    https://github.com/vsg-dev/vsgExamples/tree/Input

**Comment by rainergericke** [comment]
Sorry for this lack of clearness, I wanted to write lowercase I plus shift, but my browser messes up my input!

**Comment by robertosfield** [comment]
I have started looking into the double reporting of events in macOS and haven't spotted an obvious reason why [VulkanSceneGraph/src/vsg/platform/macos/MacOS_Window.mm](https://github.com/vsg-dev/VulkanSceneGraph/blob/master/src/vsg/platform/macos/MacOS_Window.mm) would issue two events for each key press/release.

I can't think of anything more I can do for macOS side, the only way to work out what is going on is to put a break point in and use a debugger to figure how the code behaves in repose to user events, or put some debugging into the bool MacOS_Window::handleNSEvent(NSEvent* anEvent) method to see how often each part of the switch gets called.  

Do you know if mouse events are also getting double handled?

**Comment by rainergericke** [comment]
I have found the problem and the solution.
<img width="1034" alt="VsgMacSolutio" src="https://user-images.githubusercontent.com/31243285/100514860-5eb9bf00-3178-11eb-9b3d-d2dae6ce6dc0.png">
Could you please apply this change?

What happened? VSG got wrong event information. A keyRelease event was marked as a keyPress event. With my proposed change the program response seem to be correct.

**Comment by robertosfield** [comment]
@rainergericke Well spotted.  Could you generate a PR for this fix? Thanks.

**Comment by rainergericke** [comment]
Seems, I don't have sufficient rights to it.

**Comment by robertosfield** [comment]
On Sat, 28 Nov 2020 at 13:31, Rainer Gericke <notifications@github.com>
wrote:

> Seems, I don't have sufficient rights to it.
>
Anyone should be able to generate a PR, it's only directly writing to a
repository that requires special permission.  If you are struggling then if
you point me at your repo I should be able to merge the specific commit.

**Comment by robertosfield** [comment]
I'm now at my dev system and couldn't spot any relevant commits to your fork of VSG so I just applied the fix myself and checked it in. #fc60936ad3110e08e7ac80468fc51f5f70fe7748

This is now merge with Input branch and master.  The differing value for keyBase does concern me though.  I haven't yet decided how best to handle it.

**Comment by robertosfield** [comment]
Opps turns out that I implemented the fix with a typo and broken the macOS build.  A fix is now checked in.
