### ISSUE TITLE
win32_window getButtonEventDetail only for button down,but for vsg::ButtonReleaseEvent need passing button up.

### ISSUE THREAD

**Issue by simwangrui** [vsg-dev/VulkanSceneGraph#227]
**Describe the bug**
void ImGuiEventHandler::apply(ButtonReleaseEvent& buttonRelease)
{
     buttonRelease.button value is wrong.
}

**Comment by robertosfield** [comment]
We'll need to create a test program to illustrate this.  When you say the button value is wrong, what buttons are you pressing and what result are expecting?

**Comment by simwangrui** [comment]
Whether I press the left, right, or middle button of the mouse, in the function "void ImGuiEventHandler::apply(ButtonReleaseEvent& buttonRelease)", I get the buttonRelease.button is 0.
I try to change getButtonEventDetail function to getButtonUpEventDetail and pass it to vsg::ButtonReleaseEvent() function,the expect value is ok.
int getButtonUpEventDetail(UINT buttonMsg)
    {
        return buttonMsg == WM_LBUTTONUP ? 1 : (buttonMsg == WM_MBUTTONUP ? 2 : buttonMsg == WM_RBUTTONUP ? 3 : (buttonMsg == WM_XBUTTONUP ? 4 : 0)); 
    }

**Comment by robertosfield** [comment]
On Fri, 27 Nov 2020 at 11:18, simwangrui <notifications@github.com> wrote:

> Whether I press the left, right, or middle button of the mouse, in the
> function "void ImGuiEventHandler::apply(ButtonReleaseEvent&
> buttonRelease)", I get the buttonRelease.button is 0.
> I try to change getButtonEventDetail function to getButtonUpEventDetail
> and pass it to vsg::ButtonReleaseEvent() function,the expect value is ok.
> int getButtonUpEventDetail(UINT buttonMsg)
> {
> return buttonMsg == WM_LBUTTONUP ? 1 : (buttonMsg == WM_MBUTTONUP ? 2 :
> buttonMsg == WM_RBUTTONUP ? 3 : (buttonMsg == WM_XBUTTONUP ? 4 : 0));
> }
>

I'm not the author of the Win32_Window.h code, and am not familiar with
Windows API's so am having to figure out what you mean by searching code
and trying to guess at what you mean.  I'd be useful if you code be clearer
in what code you are referring to when.

For instance ImGuiEventHandler isn't part of the VSG/vsgExamples so I
presume this is your own code.  Is this publicly available?  If so a link
would be useful.

Doing a search in the VSG code base the getButtonUpEventDetail() method
looks to be from include/vsg/platform/Win32_Window.h.  The original code
looks for OK for button down but given you code change it fails to work for
button release because it's checking for WM_LBUTTONDOWN etc, rather than
WM_LBUTTONUP.

If I am reading things correctly then your code change would fix the
ButtonReleaseEvent handling but break the ButtonPressEvent handling.

Follow on from this, it looks like a single method getButtonEventDetail(UINT
buttonMsg) is not sufficient, we need one for button press and another for
button release.  Given this code is just used once in both cases it would
probably be better to just put the code locally in the Win32_Window.cpp and
remove this function.

Does this sound appropriate?

**Comment by simwangrui** [comment]
Yes,you are right. Sorry ,my english is not good.
Think you very much! Best wishes！

**Comment by simwangrui** [comment]
`#ifndef __IMGUI_EVENT_HANDLER_h__
#define __IMGUI_EVENT_HANDLER_h__
#include <vsg/ui/PointerEvent.h>
#include <vsg/traversals/CompileTraversal.h>
#include <vector>
#include "resource_builder.h"

using namespace vsg;

class ImGuiDrawCallback
{
public:
	ImGuiDrawCallback() {}

	virtual void operator()() = 0;
};

struct ImGuiGrpahicsPipleLine
{
	vsg::ref_ptr<vsg::DescriptorSetLayout> descriptorset_layout;
	vsg::ref_ptr<vsg::GraphicsPipeline>    graphics_pipeline;
};

class ImGuiEventHandler : public Inherit<Visitor, ImGuiEventHandler>
{
public:
	ImGuiEventHandler(vsg::ref_ptr<vsg::Camera> camera, vsg::ref_ptr<ResourceBuilder> builder);
	~ImGuiEventHandler();

	void apply(ButtonPressEvent& buttonPress) override;
	void apply(ButtonReleaseEvent& buttonRelease) override;
	void apply(MoveEvent& moveEvent) override;
	void apply(ConfigureWindowEvent& confWindowEvent) override;
	void apply(FrameEvent& frameEvent) override;

	void draw(void);

	void addDrawCallback(ImGuiDrawCallback* call_back);

	vsg::ref_ptr<vsg::StateGroup> getSceneGraph(void);

	ImGuiGrpahicsPipleLine getGrpahicsPipleLine(void);

protected:
	void createPipleline(void);
	void initImGui(void);
	void createFontResource(void);
	void unInitImgui();
	void initScene();

protected:
	vsg::vec2  m_mouse_pos;
	bool       m_mouse_left_down;
	bool       m_mouse_mid_down;
	bool       m_mouse_right_down;
	float      m_display_width;
	float      m_display_height;
private:
	vsg::ref_ptr<vsg::DescriptorSetLayout> m_descriptor_set_layout;
	vsg::ref_ptr<vsg::GraphicsPipeline>    m_graphics_pipeline;

	vsg::ref_ptr<vsg::StateGroup>          m_scene_graph;
	
	std::vector<ImGuiDrawCallback*>        m_draw_callbacks;

	time_point                             m_pre_frame_time_point;
	float                                  m_detla_time;
	vsg::ref_ptr<vsg::Camera>              m_camera;
	vsg::ref_ptr<vsg::ResourceBuilder>     m_builder;

};


#endif`

`#include "ImGui_EventHandler.h"
#include "imgui.h"
#include <vsg/all.h>
#include <iostream>
#include "DrawImguiCommand.h"
#include "resource_builder.h"
#include "BindResource.h"

ImGuiEventHandler::ImGuiEventHandler(vsg::ref_ptr<vsg::Camera> camera, vsg::ref_ptr<ResourceBuilder> builder)
	: m_camera(camera)
	, m_builder(builder)
	, m_mouse_pos(0.0, 0.0)
	, m_mouse_left_down(false)
	, m_mouse_mid_down(false)
	, m_mouse_right_down(false)
	, m_display_width(960.0)
	, m_display_height(480.0)
	, m_detla_time(0)
{
	initImGui();
	initScene();
	createPipleline();
	createFontResource();
}

ImGuiEventHandler::~ImGuiEventHandler()
{
	unInitImgui();
}

void ImGuiEventHandler::createPipleline(void)
{
	const std::string shader_path = "../data/shader/";
	vsg::Paths searchPaths = { shader_path };

	auto vertexShader = vsg::ShaderStage::read(VK_SHADER_STAGE_VERTEX_BIT, "main", vsg::findFile("vsg_imgui.vert", searchPaths));
	auto fragmentShader = vsg::ShaderStage::read(VK_SHADER_STAGE_FRAGMENT_BIT, "main", vsg::findFile("vsg_imgui.frag", searchPaths));
	if (!vertexShader || !fragmentShader)
	{
		std::cout << "Could not create shaders." << std::endl;
		return;
	}

	vsg::VertexInputState::Bindings vertexBindingsDescriptions
	{
		VkVertexInputBindingDescription{0, sizeof(ImDrawVert), VK_VERTEX_INPUT_RATE_VERTEX}
	};

	vsg::VertexInputState::Attributes vertexAttributeDescriptions
	{
		VkVertexInputAttributeDescription{0, 0, VK_FORMAT_R32G32_SFLOAT, offsetof(ImDrawVert, pos)},     // vertex data
		VkVertexInputAttributeDescription{1, 0, VK_FORMAT_R32G32_SFLOAT, offsetof(ImDrawVert, uv)},      // uv data
		VkVertexInputAttributeDescription{2, 0, VK_FORMAT_R8G8B8A8_UNORM, offsetof(ImDrawVert, col)},    // color data
	};

	auto inputAssembly_state = vsg::InputAssemblyState::create(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, VK_FALSE);

	auto rasterization_state = vsg::RasterizationState::create();
	rasterization_state->cullMode = VK_CULL_MODE_NONE;
	rasterization_state->polygonMode = VK_POLYGON_MODE_FILL;

	VkPipelineColorBlendAttachmentState blendAttachmentState;
	blendAttachmentState.blendEnable = VK_TRUE;
	blendAttachmentState.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
	blendAttachmentState.srcColorBlendFactor = VK_BLEND_FACTOR_SRC_ALPHA;
	blendAttachmentState.dstColorBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
	blendAttachmentState.colorBlendOp = VK_BLEND_OP_ADD;
	blendAttachmentState.srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
	blendAttachmentState.dstAlphaBlendFactor = VK_BLEND_FACTOR_ZERO;
	blendAttachmentState.alphaBlendOp = VK_BLEND_OP_ADD;


	vsg::ColorBlendState::ColorBlendAttachments blend_attachments
	{
		blendAttachmentState
	};

	auto blend_state = vsg::ColorBlendState::create(blend_attachments);


	auto depth_stencil_state = vsg::DepthStencilState::create();
	depth_stencil_state->depthTestEnable = false;
	depth_stencil_state->depthWriteEnable = false;
	depth_stencil_state->depthCompareOp = VK_COMPARE_OP_ALWAYS;
	depth_stencil_state->back.compareOp = VK_COMPARE_OP_ALWAYS;

	vsg::GraphicsPipelineStates pipelineStates
	{
		vsg::VertexInputState::create(vertexBindingsDescriptions, vertexAttributeDescriptions),
		inputAssembly_state,
		rasterization_state,
		vsg::MultisampleState::create(),
		blend_state,
		depth_stencil_state,
	};


	vsg::DescriptorSetLayoutBindings descriptorBindings
	{
		{0, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1, VK_SHADER_STAGE_FRAGMENT_BIT, nullptr}
	};

	m_descriptor_set_layout = vsg::DescriptorSetLayout::create(descriptorBindings);


	vsg::PushConstantRanges pushConstantRanges
	{
		{VK_SHADER_STAGE_VERTEX_BIT, 0, 128}
	};
	auto pipelineLayout = vsg::PipelineLayout::create(vsg::DescriptorSetLayouts{ m_descriptor_set_layout }, pushConstantRanges);
	m_graphics_pipeline = vsg::GraphicsPipeline::create(pipelineLayout, vsg::ShaderStages{ vertexShader, fragmentShader }, pipelineStates);
	auto bindGraphicsPipeline = vsg::BindGraphicsPipeline::create(m_graphics_pipeline);

	m_scene_graph->add(bindGraphicsPipeline);
}

void ImGuiEventHandler::initImGui(void)
{
	ImGui::CreateContext();
	ImGuiStyle& style = ImGui::GetStyle();
	style.Colors[ImGuiCol_WindowBg] = ImVec4(0.0f, 0.0f, 0.0f, 0.2f);
}

void ImGuiEventHandler::initScene()
{
	m_scene_graph = vsg::StateGroup::create();

	auto imgui_cmd = vsg::DrawImGuiCommand::create();

	m_scene_graph->addChild(imgui_cmd);

	//添加DrawImGuiCommand子节点
	m_pre_frame_time_point = vsg::clock::now();

}

void ImGuiEventHandler::unInitImgui()
{
	ImGui::DestroyContext();
}

void ImGuiEventHandler::createFontResource(void)
{
	ImGuiIO& io = ImGui::GetIO();
	io.FontGlobalScale = 1.0;

	io.BackendFlags |= ImGuiBackendFlags_HasMouseCursors;         // We can honor GetMouseCursor() values (optional)
	io.BackendFlags |= ImGuiBackendFlags_HasSetMousePos;          // We can honor io.WantSetMousePos requests (optional, rarely used)
	


	int texWidth, texHeight;

	const std::string filename = "../data/fonts/Roboto-Medium.ttf";
	io.Fonts->AddFontFromFileTTF(filename.c_str(), 16.0f);

	// Create font texture
	unsigned char* fontData = NULL;
	io.Fonts->GetTexDataAsRGBA32(&fontData, &texWidth, &texHeight);
	VkDeviceSize uploadSize = texWidth * texHeight;

	auto font_image = vsg::ubyteArray2D::create(texWidth, texHeight, fontData, vsg::Data::Layout{ VK_FORMAT_R8G8B8A8_UNORM, 4, 1 });
	
	auto texture = vsg::DescriptorImage::create(vsg::Sampler::create(), font_image, 0, 0, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER);

	auto descriptorSet = vsg::DescriptorSet::create(m_descriptor_set_layout, vsg::Descriptors{ texture });
	auto bindResource = vsg::BindResource::create(VK_PIPELINE_BIND_POINT_GRAPHICS, m_graphics_pipeline->layout, 0, descriptorSet);
	
	m_builder->compile(bindResource);

	m_scene_graph->add(bindResource);
	
	io.Fonts->TexID = (ImTextureID)(intptr_t)(bindResource->getVkDescriptorSet());
}

void ImGuiEventHandler::apply(ButtonPressEvent& buttonPress)
{
	if (1 == buttonPress.button)
	{
		m_mouse_left_down = true;
	}
	
	if (2 == buttonPress.button)
	{
		m_mouse_mid_down = true;
	}

	if (3 == buttonPress.button)
	{
		m_mouse_right_down = true;
	}
	
	m_mouse_pos = vsg::vec2((float)buttonPress.x, (float)buttonPress.y);
	
}

void ImGuiEventHandler::apply(ButtonReleaseEvent& buttonRelease)
{

	if (1 == buttonRelease.button)
	{
		m_mouse_left_down = false;
	}

	if (2 == buttonRelease.button)
	{
		m_mouse_mid_down = false;
	}

	if (3 == buttonRelease.button)
	{
		m_mouse_right_down = false;
	}
	
	m_mouse_pos = vsg::vec2((float)buttonRelease.x, (float)buttonRelease.y);
}

void ImGuiEventHandler::apply(MoveEvent& moveEvent)
{
	m_mouse_pos = vsg::vec2((float)moveEvent.x, (float)moveEvent.y);
}

void ImGuiEventHandler::apply(ConfigureWindowEvent& confWindowEvent)
{
	m_display_width = static_cast<float>(confWindowEvent.width);
	m_display_height = static_cast<float>(confWindowEvent.height);

	auto projection = vsg::Orthographic::create(0.0f, m_display_width, 0, m_display_height, 0.0, 5.0);

	m_camera->setProjectionMatrix(projection);
}

void ImGuiEventHandler::apply(FrameEvent& frameEvent)
{
	time_point now_time_point = frameEvent.frameStamp->time;

	m_detla_time = std::chrono::duration<float, std::chrono::seconds::period>(now_time_point - m_pre_frame_time_point).count();

	auto projection = vsg::Orthographic::create(0.0f, m_display_width, 0, m_display_height, 0.0, 5.0);

	m_camera->setProjectionMatrix(projection);

	draw();

	m_pre_frame_time_point = now_time_point;
}

void ImGuiEventHandler::addDrawCallback(ImGuiDrawCallback* call_back)
{
	m_draw_callbacks.emplace_back(call_back);
}

void ImGuiEventHandler::draw(void)
{
	ImGuiIO& io = ImGui::GetIO();

	io.DisplaySize = ImVec2(m_display_width, m_display_height);
	io.DeltaTime = m_detla_time;
	
	io.MousePos = ImVec2(m_mouse_pos.x, m_mouse_pos.y);
	io.MouseDown[0] = m_mouse_left_down;
	io.MouseDown[1] = m_mouse_right_down;
	io.MouseDown[2] = m_mouse_mid_down;
	
	io.DisplayFramebufferScale = ImVec2(1.0, 1.0);
	
	ImGui::NewFrame();

	for (auto itor  = m_draw_callbacks.begin(); 
		      itor != m_draw_callbacks.end(); itor++)
	{
		(**itor)();
	}

	ImGui::EndFrame();

	ImGui::Render();

}

vsg::ref_ptr<vsg::StateGroup> ImGuiEventHandler::getSceneGraph(void)
{
	return m_scene_graph;
}

ImGuiGrpahicsPipleLine ImGuiEventHandler::getGrpahicsPipleLine(void)
{
	ImGuiGrpahicsPipleLine pl;

	pl.descriptorset_layout = m_descriptor_set_layout;
	pl.graphics_pipeline = m_graphics_pipeline;

	return pl;
}`

**Comment by robertosfield** [comment]
I've used your getButtonUpEventDetail() and changed the original getButtonEventDetail() to getButtonDowEventDetail().  I created an Input branch for it so it can be used for testing:

   https://github.com/vsg-dev/VulkanSceneGraph/tree/Input

The commit is #063c1b46c6069fca89ba1af07096f573f404df6f 

Could you test it and if it works I'll merge with master.

**Comment by robertosfield** [comment]
The automated builds picked up an build error on my first commit above. I've checked in a fix so head of the Input branch should work now.

**Comment by simwangrui** [comment]
I've tested the input branch and the mouse down and release response works ok now !   Thank you very much!
