### ISSUE TITLE
Quick build instructions for Unix from the command line do not work

### ISSUE THREAD

**Issue by slipch** [vsg-dev/VulkanSceneGraph#263]
Ubuntu 18.04.5 LTS
cmake version 3.10.2
gcc version 7.5.0 

cmake ends with errors

VulkanSceneGraph$ cmake .
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR) 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Failed to find glslang
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'xcb'
--   Found xcb, version 1.13
-- Configuring done
CMake Error at src/vsg/CMakeLists.txt:240 (add_library):
  Target "vsg" links to target "Vulkan::Vulkan" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at src/vsg/CMakeLists.txt:240 (add_library):
  Target "vsg" links to target "Vulkan::Vulkan" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

-- Generating done
-- Build files have been written to: /home/slipch/develop/3dedit/Vulkan/code/VulkanSceneGraph

subsequent call to make fails with 
/home/slipch/develop/3dedit/Vulkan/code/VulkanSceneGraph/include/vsg/core/Data.h:18:10: fatal error: vulkan/vulkan.h: No such file or directory
 #include <vulkan/vulkan.h>

**Comment by robertosfield** [comment]
Hi,

> -- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR)
>
CMake is suggesting that it can't find Vulkan headers.

Have you installed Vulkan header and libs?  If so which ones and how did
you install them?  Where are they installed?

I use Xubuntu 18.04 for all my dev work, and the VulkanSDK from LunarG.  I
use the VULKAN_SDK env var to point the CMake Vulkan find scripts to in the
VUlkanSDK.

Cheers,
Robert.

**Comment by slipch** [comment]
Hi,

No, I haven't installed Vulkan header and libs. I couldn't. The steps from the instruction for installation are failing.
I do not use VULKAN_SDK env var but is not mentioned in the instruction. 
Where exactly should it point given that I've just cloned the repository?

Regards,
Konstantin

**Comment by robertosfield** [comment]
Hi Konstantin,

On Wed, 17 Mar 2021 at 08:57, slipch ***@***.***> wrote:

> No, I haven't installed Vulkan header and libs. I couldn't. The steps from
> the instruction for installation are failing.
>

Sorry, it's so long since I touched those instructions, I hadn't realized
that dependencies info is missing.

> I do not use VULKAN_SDK env var but is not mentioned in the instruction.
> Where exactly should it point given that I've just cloned the repository?
>
I think it's possible to install vulkan headers from the Ubuntu repo but
the last time I tried it they were a bit too out of date. That might have
changed now.  FYI, I use Xubuntu 18.04 as my dev system.

My recommendation would be to use the VulkanSDK from LunarG:
https://vulkan.lunarg.com/sdk/home

I just place the VulkanSDK into a directory in my home directory then point
the Vulkan CMake find script to to use the VULKAN_SDK env var. i.e.

$ export | grep VULKAN
declare -x VULKAN_SDK="/home/robert/3rdParty/VulkanSDK/1.2.162.0/x86_64"

The use of the VulkanSDK is a pretty standard way to work with Vulkan and
something you'd use across platforms.

Cheers,
Robert.

**Comment by slipch** [comment]
Thanks, Robert
That works. Also I could find setup-env.sh to set the environment, and a different instruction to set up the SDK.
After that I was able to use the steps from
https://github.com/vsg-dev/VulkanSceneGraph
to build the master.
But I think that instruction should be updated. 
It won't work until Vulkan SDK is set.

Konstantin

**Comment by robertosfield** [comment]
On Wed, 17 Mar 2021 at 21:48, slipch ***@***.***> wrote:

> Thanks, Robert
> That works. Also I could find setup-env.sh to set the environment, and a
> different instruction to set up the SDK.
> After that I was able to use the steps from
> https://github.com/vsg-dev/VulkanSceneGraph
> to build the master.
> But I think that instruction should be updated.
> It won't work until Vulkan SDK is set.
>
Thanks for the feedback. I'll update the docs tomorrow.

**Comment by robertosfield** [comment]
I have put in a short explanation about downloading the VulkanSDK and setting the VULKAN_SDK env var,  Could you have a read through the "Quick Guide to building the VSG"  section to check that it makes sense.  Thanks.

    README.md)[](https://github.com/vsg-dev/VulkanSceneGraph/blob/master/README.md)

**Comment by slipch** [comment]
I have read. That should work. Perhaps, that would be be better to have steps for building Vulcan from sources without the dependency on the SDK that is probably created from the the same sources of another version. But that makes sense.
