### ISSUE TITLE
Qt support

### ISSUE THREAD

**Issue by zhangchao321** [vsg-dev/VulkanSceneGraph#269]
VulkanSceneGraph whether can provide a Qt libraries or example of support

**Comment by robertosfield** [comment]
The core VulkanSceneGeaph won't directly provide Qt support, but the windowing support is designed to extensible so you can add it.

An example of Qt +VulkanSceneGRaph integration:

[https://github.com/anormann1974/vsgQtViewer](https://github.com/anormann1974/vsgQtViewer)

Thread on vsg-users about it:
[https://groups.google.com/g/vsg-users/c/h4Y8g8D8aLU/m/k5e5_FDsBgAJ](https://groups.google.com/g/vsg-users/c/h4Y8g8D8aLU/m/k5e5_FDsBgAJ)

**Comment by robertosfield** [comment]
I have added a link to vsgQtViewer to the VulkanSceneGraph/README.md to make it easier to find.

**Comment by zhangchao321** [comment]
Thank you very much for the qt vsg example

**Comment by robertosfield** [comment]
@zhangchao321 We now have a dedicated vsgQt library : 

    [https://github.com/vsg-dev/vsgQt](https://github.com/vsg-dev/vsgQt)
