### ISSUE TITLE
errors under ubuntu using "cmake ."

### ISSUE THREAD

**Issue by zhangfq-chemistry** [vsg-dev/VulkanSceneGraph#285]
/home/zhangfq/vulkan/VulkanSceneGraph/include/vsg/vk/Context.h:40:65: error: ‘VkAccelerationStructureBuildGeometryInfoKHR’ does not name a type; did you mean ‘VkBindAccelerationStructureMemoryInfoKHR’?

**Comment by robertosfield** [comment]
VulkanSceneGraph master now depends upon Khronos ray tracing extension that
requires VulkanSDK 1.2.162.0 or later.
