### ISSUE TITLE
vector divde

### ISSUE THREAD

**Issue by HowellDong** [vsg-dev/VulkanSceneGraph#290]
```c++
vsg::uivec2 uint_vec2(4, 6);
uint_vec2 /= 3;		//expect(1, 2)
std::cout << "(" << uint_vec2.x << ", " << uint_vec2.y << ")" << std::endl;	//but print (0, 0)
```

**Comment by robertosfield** [comment]
Thanks for reporting this bug.  I've done a quick have to vec2.h that confirms that the optimization used is only appropriate for non integer numbers:

        inline t_vec2& operator/=(value_type rhs)
        {
#if 1 // works
            value[0] /= rhs;
            value[1] /= rhs;
#else // only works with floating point types.
            value_type div = static_cast<value_type>(1.0) / rhs;
            value[0] *= div;
            value[1] *= div;
#endif
            return *this;
        }
    };

I will see if I can get C++ to use the different code paths for different types.

**Comment by robertosfield** [comment]
I have introduced use of constexpr (constexpr (std::is_floating_point_v<value_type>) to help avoid use of the floating point division optimization:

a55a08a28b11b51dc329c538e46a84e1ee5abb8b
