### ISSUE TITLE
init a plane with normal and a point on the plane

### ISSUE THREAD

**Issue by HowellDong** [vsg-dev/VulkanSceneGraph#292]
```c++
constexpr t_plane(const normal_type& position, const normal_type& normal) :
            value{normal.x, normal.y, normal.z, position * normal} {}
```

I think the formula you mean is : `dot(normal, any_point - position) = 0`

so the `value` should be initialized with `{normal.x, normal.y, normal.z, -position * normal}`, you forgot  to add the negative sign?

**Comment by robertosfield** [comment]
You are correct, this is a bug.  I've checked in a fix for this.
