### ISSUE TITLE
Incorrect install locations for shared libraries and cmake files on 64bit linux

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/VulkanSceneGraph#301]
**Describe the bug**
Installing a binary build generated from this source on a linux x86_64 host uses incorrect install locations for shared libraries and cmake files (missing 64 suffix)

**To Reproduce**
1. build VulkanSceneGraph on the mentioned host according to the build information from https://github.com/vsg-dev/VulkanSceneGraph#command-line-build-instructions
2. inspect installed files; you will see that shared libraries and cmake files has been installed in the associated location for 32bit files

**Expected behavior**
The shared libraries should be installed into the location for 64 bit libraries and cmake files

**Desktop (please complete the following information):**
 - OS: openSUSE Leap
 - Version 15.2 (64 bit)

**Comment by robertosfield** [comment]
On Mon, 23 Aug 2021 at 08:23, Ralf Habacker ***@***.***>
wrote:

> *Describe the bug*
> Installing a binary build generated from this source on a linux x86_64
> host uses incorrect install locations for shared libraries and cmake files
> (missing 64 suffix)
>
What suffix is appropropriate varies across OS's and over different
variants of it.  For instance Ubuntu I'm using right now installs almost
all libs into /usr/lib, a small number in /usr/lib32 and just one in
/usr/lib64.   Just make the lib prefix for 64bit linux mix it for Suse bit
would break from the Debian convention, as a default the later would work
better out of the box for most users.

Looking at VulkanSceneGraph/CMakeLists.txt, the place where output lib is
set is:

    set(OUTPUT_LIBDIR ${PROJECT_BINARY_DIR}/lib)

This doesn't make this variable user editable though, which doesn't give
users an option to override the default when they aren't happy with it.  So
this is something we could change.

Or perhaps look into relying upon CMake defaults more.  Will have a look at
that.  My initial look I've come across:

    https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html

Robert.

**Comment by rhabacker** [comment]
The associated pull request uses GNUInstallDirs to use the cmake default settings and also let the user override the setting by specifing  -DCMAKE_INSTALL_LIBDIR on the cmake configure line, which is used by distributions. See for example https://build.opensuse.org/package/view_file/openSUSE:Factory/cmake/cmake.macros?expand=1.

**Comment by robertosfield** [comment]
On Mon, 23 Aug 2021 at 09:03, Ralf Habacker ***@***.***>
wrote:

> The associated pull request uses GNUInstallDirs to use the cmake default
> settings and also let the user override the setting by specifing
> -DCMAKE_INSTALL_LIBDIR on the cmake configure line, which is used by
> distributions. See for example
> https://build.opensuse.org/package/view_file/openSUSE:Factory/cmake/cmake.macros?expand=1
> .
>
I'm not clear on what you want to highlight to me with this link.

--

Looking fuhrer into the VSG's CMake build the install is set up with the
lines on VulkanSceneGraph/src/vsg/CMakeLists.txt:

install(TARGETS vsg EXPORT vsgTargets
        LIBRARY DESTINATION lib
        ARCHIVE DESTINATION lib
        RUNTIME DESTINATION bin
        INCLUDES DESTINATION include
)

So this is more likely where we'll need to adjust rather than the
OUTPUT_LIBDIR setting.

FYI, the CMake that I put together for the CMake config and install was
based on CMake examples elsewhere, these are also then used as templates in
the VSG sibling projects vsgXchange etc.

I haven't tried the above install line without explicitly setting the
LIBRARY and ARCHIVE DESTINATION.  Might be worth seeing what might be
possible.

**Comment by rhabacker** [comment]
That the cmake variable CMAKE_INSTALL_LIBDIR is used in the %cmake macro. 
```
%cmake \
...
  -DCMAKE_INSTALL_LIBDIR:PATH=%{_lib} \\\
```

The macro is used to build rpm packages that use cmake on openSUSE.

**Comment by robertosfield** [comment]
Thanks.  I'm now testing your PR.  Will the PR help things under Windows?

**Comment by rhabacker** [comment]
Not complete. This commit introduces the cmake variable INSTALL_TARGETS_DEFAULT_FLAGS, which is modified to setup the correct location for Windows in a following pr, after this has pr is merged. 

Do you want to have the Windows fix included into this pr ?

**Comment by robertosfield** [comment]
Testing far looks good.  I still get the same Debian style defaults as before and now have the ability to overrde the lib path extension - even works with a nod to a space odyssey:

-- Installing: /home/robert/NewInstall/lib2001/cmake/vsg/vsgTargets.cmake
-- Installing: /home/robert/NewInstall/lib2001/cmake/vsg/vsgTargets-release.cmake
-- Installing: /home/robert/NewInstall/lib2001/cmake/vsg/vsgConfig.cmake
-- Installing: /home/robert/NewInstall/lib2001/cmake/vsg/vsgConfigVersion.cmake

Does this PR work out the box for Suse now?

Any fixes for Windows would be best kept as a  separate PR.

**Comment by rhabacker** [comment]
> Does this PR work out the box for Suse now?

yes

**Comment by robertosfield** [comment]
I have applied similar changes to vsgXchange, @rhabacker could you check this changes?

    https://github.com/vsg-dev/vsgXchange/commit/9ba6b41715b020ef30c2ebeba4ca0c1f6a84dee1

**Comment by robertosfield** [comment]
vsgImGui now updated with InstallChanges branch:

[https://github.com/vsg-dev/vsgImGui/commit/84b113f975bcdea96061b2829f5ff87cc48cd09d](https://github.com/vsg-dev/vsgImGui/commit/84b113f975bcdea96061b2829f5ff87cc48cd09d)

**Comment by robertosfield** [comment]
vsgGIS now updated with InstallChanges branch:

[https://github.com/vsg-dev/vsgGIS/commit/bbe7be4b3d53f97bf658c3a016266f66cdf5ecbe](https://github.com/vsg-dev/vsgGIS/commit/bbe7be4b3d53f97bf658c3a016266f66cdf5ecbe)

**Comment by robertosfield** [comment]
It doesn't look vsgUnity or vsgExamples, MyFirstVsgApplcation will need updating.  I will next check vsgFramework to see whether it might need updating.

@rhabacker Could you let me know if the InstallChanges branches on vsgGIS, vsgXchange, vsgUmGui are working for you.  If they are then I'll merged these with master.

**Comment by rhabacker** [comment]
With the mentioned patches applied and running 

```
 mkdir -p ../vsg<component>-build
 cd ../vsg<component>-build
 cmake  ../vsg<component>  -DBUILD_SHARED_LIBS=1 -DCMAKE_INSTALL_PREFIX=/home/xxx/src/vsg-install/usr/local -DCMAKE_PREFIX_PATH=/home/x/src/vsg-install/usr/local
make
make install
```
for <component> I get

vsgGIS
...
-- Installing: /home/xxx/src/vsg-install/user/local/lib64/libvsgGIS.so.0.0.0
...
-- Installing: /home/xxx/src/vsg-install/user/local/lib64/cmake/vsgGIS/vsgGISTargets.cmake

vsgXchange
...
-- Installing: /home/xxx/src/vsg-install/usr/local/lib64/libvsgXchange.so.0.0.1
...
-- Installing: /home/xxx/src/vsg-install/usr/local/lib64/cmake/vsgXchange/vsgXchangeTargets.cmake

vsgImGui
...
-- Installing: /home/xxx/src/vsg-install/usr/local/lib64/libvsgImGui.so.0.0.0
...
-- Installing: /home/x/src/vsg-install/usr/local/lib64/cmake/vsgImGui/vsgImGuiTargets.cmake

**Comment by robertosfield** [comment]
What are you expecting as the correct install behiavor with the different
CMAKE_INSTALL_PREFIX and CMAKE_PREFIX_PATH?

> cmake ../vsg<component> -DBUILD_SHARED_LIBS=1
-DCMAKE_INSTALL_PREFIX=/home/xxx/src/vsg-install/usr/local
-DCMAKE_PREFIX_PATH=/home/x/src/vsg-install/usr/local

vsgImGui is only one of three your report that puts the .cmake into
the CMAKE_PREFIX_PATH,
is this only one you think is correct, or is the one wrong?

**Comment by rhabacker** [comment]
All packages uses the same prefix path. This was simply an editing issue, which I corrected in the above comment - sorry for confusion.

**Comment by robertosfield** [comment]
On Mon, 23 Aug 2021 at 15:29, Ralf Habacker ***@***.***>
wrote:

> All packages uses the same prefix path. This was simply an editing issue,
> which I corrected in the above comment - sorry for confusion.
>
So are we good to merge the InstallChanges branches with the respective
masters?

**Comment by rhabacker** [comment]
yes, except the spelling error in commit message of  https://github.com/vsg-dev/vsgXchange/commit/9ba6b41715b020ef30c2ebeba4ca0c1f6a84dee1 
```
Merdge changess in install paths from VulkanSceneGraph to vsgXchange …
```
while both other commits uses `Applied changes to install paths from VulkanSceneGraph`.

**Comment by robertosfield** [comment]
Thanks for the testing. I've now merged the changes to vsgImGui, vsgGIS and vsgXchange the respective masters.

**Comment by rhabacker** [comment]
Thanks for your support.
