### ISSUE TITLE
Incorrect install location for shared libraries on Windows

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/VulkanSceneGraph#303]
**Describe the bug**
Installing a binary build generated from this source on a windows host uses incorrect install locations for the shared libraries

**To Reproduce**
1. build VulkanSceneGraph on the mentioned host according to the build information from https://github.com/vsg-dev/VulkanSceneGraph#command-line-build-instructions
2. inspect installed files; you will see that shared libraries has been installed in the 'lib' sub directory of the selected installation root

**Expected behavior**
The shared libraries should be installed into the 'bin' location

**Desktop:**
 - OS: Windows
 - Version 10

**Comment by robertosfield** [comment]
Could you list out the paths that libs and dll's are installed in by
default, and what the directories where you expect them to be installed.

**Comment by rhabacker** [comment]
Current
.exe files -> <install-root>/bin
shared libraries  -><install-root>/lib
static libraries  -><install-root>/lib

Expected
.exe files -> <install-root>/bin
shared libraries  -><install-root>/bin
static libraries  -><install-root>/lib

**Comment by robertosfield** [comment]
Will this have any effect on an issue reported about finding vsg_glslang.cmake?

   []https://github.com/vsg-dev/vsgExamples/issues/84(https://github.com/vsg-dev/vsgExamples/issues/84)

**Comment by robertosfield** [comment]
Once the install path is settled for Windows I'll review the install code in vsgXchange. vsgGIS, vsgImGui and vsgExamples as they will all inherit the same behaviour.

**Comment by robertosfield** [comment]
Thanks @rhabacker, all merged now.  I'll look at updating all the sibling projects now.

Any thoughts on the effect on the issue of find vsg_glslang.cmake?

**Comment by rhabacker** [comment]
> Will this have any effect on an issue reported about finding vsg_glslang.cmake?

This patch has no effect, as it only covers shared libraries, not the installed cmake support files.

The installation location of cmake support files on Windows can be affected by https://github.com/vsg-dev/VulkanSceneGraph/pull/302 as now the location of CMAKE_INSTALL_LIBDIR can be changed on the cmake command line, but in my experience with mingw builds on Windows the path remains 'lib'.

For proceeding I added an additional hint to vsg-dev/vsgExamples#84
