### ISSUE TITLE
Reduction of cmake code duplication

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/VulkanSceneGraph#305]
**Does your feature request relate to a problem? Please describe it.**
The cmake buildsytem in every git repo in the vsg-dev project contains duplicated code, such as providing maintainer options, setting installation targets, setting library postfixes, and so on. Changes to this have to be manually added to all other repos (see for example https://github.com/vsg-dev/VulkanSceneGraph/issues/301), which could be done better and easier.

**Describe the solution you want**.
I suggest adding a cmake file vsgMacros.cmake to the VulkanSceneGraph repo that contains common definitions and macros that can be used by all repos. 
This file is installed with the VulkanSceneGraph repo when building/installing it, and is automatically available to the cmake buildsystem to all other repos. 

**Additional Context**.
Required steps:
1. create the vsgMacros.cmake file.
2. install the vsgMacros.cmake file in `${CMAKE_INSTALL_LIBDIR}/cmake/vsg`
3. in src/vsg/vsgConfig.cmake.add the line `include("${CMAKE_CURRENT_LIST_DIR}/vsgMacros.cmake")`

After that, common cmake code can be transferred to the vsgMacros.cmake file.

**Comment by robertosfield** [comment]
An interesting idea.  I have plenty of other tasks to get on with so can't take this right away, but if you fancy experimenting I'm happy to support it.

**Comment by robertosfield** [comment]
I'm going to close this Issue now as I think job done now it's all merged with the respective masters :-)

**Comment by robertosfield** [comment]
@rhabacker I have just run make cppcheck and now see a lot of output that wasn't there before.  I am not sure it's related to updates to cppcheck now that I'm using Ubuntu 21.04 or whether the new vsgMarcos.cmake is missing the list of suppressions of false positives found in VulkanSceneGraph/build/cppcheck-suppression-list.txt.

Thoughts?

**Comment by rhabacker** [comment]
In the build dir you may run 
```
make cppcheck VERBOSE=1
``` 
to see the cppcheck command line.

On openSUSE Leap 15.2 I get 
```
cd /home/xxx/src/VulkanSceneGraph && /usr/bin/cppcheck -j 12 --quiet --enable=style --language=c++ --suppressions-list=/home/xxx/src/VulkanSceneGraph/build/cppcheck-suppression-list.txt /home/xxx/src/VulkanSceneGraph/include/vsg/*/*.h /home/xxx/src/VulkanSceneGraph/src/vsg/*/*.cpp -I /home/xxx/src/VulkanSceneGraph/include/
[/home/xxx/src/VulkanSceneGraph/include/vsg/core/Exception.h:22]: (style) struct member 'Exception::result' is never used.
[/home/xxx/src/VulkanSceneGraph/include/vsg/maths/vec3.h:117]: (error) syntax error
[/home/xxx/src/VulkanSceneGraph/include/vsg/maths/vec2.h:112]: (error) syntax error
[/home/xxx/src/VulkanSceneGraph/include/vsg/maths/vec4.h:122]: (error) syntax error
```
The mentioned file 
```
$ ls /home/xxx/src/VulkanSceneGraph/build/cppcheck-suppression-list.txt
/home/xxx/src/VulkanSceneGraph/build/cppcheck-suppression-list.txt
``` 
is present and seems to be loaded.

Install version of cppcheck is
```
$ cppcheck --version
Cppcheck 1.82
```

**Comment by rhabacker** [comment]
> [/home/xxx/src/VulkanSceneGraph/include/vsg/maths/vec3.h:117]: (error) syntax error

Looking at the mentioned source line shows
```
117:  if constexpr (std::is_floating_point_v<value_type>)
```
which probably should be 
```
117:  if (constexpr (std::is_floating_point_v<value_type>))
```

**Comment by robertosfield** [comment]
On Tue, 7 Sept 2021 at 16:34, Ralf Habacker ***@***.***>
wrote:

> [/home/xxx/src/VulkanSceneGraph/include/vsg/maths/vec3.h:117]: (error)
> syntax error
>
> Looking at the mentioned source line shows
>
> 117:  if constexpr (std::is_floating_point_v<value_type>)
>
> which probably should be
>
> 117:  if (constexpr (std::is_floating_point_v<value_type>))
>
>
That's a false positive, the code is correct and standard usage for if
constexpr.

    https://en.cppreference.com/w/cpp/language/if


$ cppcheck --version
cppcheck: Symbol `_ZTVN8tinyxml210XMLPrinterE' has different size in shared
object, consider re-linking
Cppcheck 2.3

I ran with VEROBSE=1 and it would look to be picking up the suppression
list.  Looks like I'll need to add a few new entries in the suppression
list.  Frustrating when valid and correct code is flagged up because just
in some cases users might misuse a language feature.

Robert.

**Comment by robertosfield** [comment]
I think it's now safe to close this Issue as the new vsgMacros.cmake look to be working pretty smoothly.
