### ISSUE TITLE
Missing support to detect supported Vulkan SDK version

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/VulkanSceneGraph#312]
**Does your feature request relate to a problem? Please describe it.
vsg does not recognize the version of the Vulkan SDK being used, which would prevent version-related issues such as those reported at https://github.com/vsg-dev/VulkanSceneGraph/issues/311.

**Describe the solution you want**.
vsg should specify the minimum required version when finding the Vulkan SDK, which can be specified by an additional argument to the call to cmake find_package():
```
...
set(Vulkan_MIN_VERSION 1.2.162.0)
...
find_package(Vulkan ${Vulkan_MIN_VERSION} REQUIRED)
```
which causes cmake to report any problems finding the required version. 

**Additional context**.
Unfortunately, the currently available cmake module for finding [Vulkan libraries](https://github.com/Kitware/CMake/blob/86ee38d75678d68bb1a79b9fa443b42723b09f23/Modules/FindVulkan.cmake#L68) does not include version support.

**Comment by robertosfield** [comment]
Gven the Vulcan cmake support doesn't support version requirement, perhaps we could add a check to the VSG's build to check the VK_HEADER_VERSION value found in include/vulkan/vulkan_core.h.  Equal or great than 162 should be sufficient.

**Comment by robertosfield** [comment]
First hack at whether we can check the header version from CMake and I have:

if (VULKAN_FOUND)
    set(VULKAN_CORE_H ${Vulkan_INCLUDE_DIRS}/vulkan/vulkan_core.h)
    file(STRINGS  ${VULKAN_CORE_H} VulkanHeaderVersionLine REGEX "^#define VK_HEADER_VERSION ")
    string(REGEX MATCHALL "[0-9]+" VulkanHeaderVersion "${VulkanHeaderVersionLine}")
    message("VulkanHeaderVersion " ${VulkanHeaderVersion})
endif()

This correctly reports:

VulkanHeaderVersion 182

On  my system.

**Comment by robertosfield** [comment]
I've refined the cmake version check to:

 if (VULKAN_FOUND)
    set(VULKAN_CORE_H ${Vulkan_INCLUDE_DIRS}/vulkan/vulkan_core.h)
    set(VK_HEADER_VERSION_MINIMUM 192)
    file(STRINGS  ${VULKAN_CORE_H} VulkanHeaderVersionLine REGEX "^#define VK_HEADER_VERSION ")
    string(REGEX MATCHALL "[0-9]+" VulkanHeaderVersion "${VulkanHeaderVersionLine}")
    if (${VulkanHeaderVersion} STRLESS ${VK_HEADER_VERSION_MINIMUM})
        message(FATAL_ERROR
            "\nFound Vulkan but VK_HEADER_VERSION is below minimum required value of " ${VK_HEADER_VERSION_MINIMUM}
            "\nDetected VK_HEADER_VERSION is " ${VulkanHeaderVersion} ", in header " ${VULKAN_CORE_H})
    endif()
endif()

This outputs:



CMake Error at CMakeLists.txt:41 (message):
  

  Found Vulkan but VK_HEADER_VERSION is below minimum required value of 192

  Detected VK_HEADER_VERSION is 182, in header
  /home/robert/3rdParty/VulkanSDK/1.2.182.0/x86_64/include/vulkan/vulkan_core.h

--

I just used 192 to break the test, rather than it being the actual min version (which I think is 162 given the Khronos ray tracing extensions.)

@rhabacker  thoughts?  I'm think that this would be reasonable addition to vsgMacros.cmake.

**Comment by robertosfield** [comment]
I've checked in these experiments in a VulkanVersion branch:

[VulkanVersion](https://github.com/vsg-dev/VulkanSceneGraph/tree/VulkanVersion)

**Comment by rhabacker** [comment]
> I'm think that this would be reasonable addition to vsgMacros.cmake.

Yes, I made an associated pr, see #339

**Comment by rhabacker** [comment]
> see #339

I have made two adjustments:
1. i always show the detected version as additional information.
2. i used Vulkan_FOUND, which is defined by the FindVulkan.cmake module (see /usr/share/cmake/Modules/FindVulkan.cmake) instead of VULKAN_FOUND. 

As an extension I think that in case of `NOT Vulkan_FOUND` a fatal error should be triggered, because finding Vulkan is mandatory for this.

**Comment by robertosfield** [comment]
On Wed, 29 Sept 2021 at 07:50, Ralf Habacker ***@***.***>
wrote:

> see #339 <https://github.com/vsg-dev/VulkanSceneGraph/pull/339>
>
> I have made two adjustments:
>
>    1. i always show the detected version as additional information.
>    2. i used Vulkan_FOUND, which is defined by the FindVulkan.cmake
>    module (see /usr/share/cmake/Modules/FindVulkan.cmake) instead of
>    VULKAN_FOUND.
>
> As an extension I think that in case of NOT Vulkan_FOUND a fatal error
> should be triggered, because finding Vulkan is mandatory for this.
>
I'll go ahead and merge as this was what I had in mind.

I am considering changing the name to vsg_check_min_vulkan_header_version
to better reflect the variable being checked.

Another future step might be to just create our own find package for Vulkan
that has versioning support.

**Comment by rhabacker** [comment]
> I am considering changing the name to vsg_check_min_vulkan_header_versionto better reflect the variable being checked.

Do you know if github provides similar support for "Allow commits from members who can merge to the target branch" as it does [gitlab](https://gitlab.kitware.com/help/user/project/merge_requests/allow_collaboration). Then small changes like this could be added as a fixup commit within the pull request.

**Comment by robertosfield** [comment]
On Thu, 30 Sept 2021 at 13:56, Ralf Habacker ***@***.***>
wrote:

> I am considering changing the name to
> vsg_check_min_vulkan_header_versionto better reflect the variable being
> checked.
>
> Do you know if github provides similar support for "Allow commits from
> members who can merge to the target branch" as it does gitlab
> <https://gitlab.kitware.com/help/user/project/merge_requests/allow_collaboration>.
> Then small changes like this could be added as a fixup commit within the
> pull request.
>
I'm not sure whether it's the same thing, but occasionally I modify PR's
manually via the github web interface.  Whether l use it depends upon that
type of modification being made.  If there is any chance of breaking the
build I'll check out the PR as a branch and do testing/fixes.

Ideally github would allow us to grant write permission for individual
branches but unfortunately it's an all or nothing affair.  I feel it's
important that I'm aware of all the changes being merged to the code base
so plan to remain the "guardian of the source", at least until 1.0.
