### ISSUE TITLE
ShaderCompiler can not resolve includes

### ISSUE THREAD

**Issue by Lachei** [vsg-dev/VulkanSceneGraph#330]
**Describe the bug**
For shaders which should be compiled with the vsg::ShaderCompiler and have #includes the included file can not be resolved

**To Reproduce**
See the raygen.rgen shader in https://github.com/Lachei/VulkanPBRT/tree/josef/shaders . The #include "generla.glsl" could not be resolved

 - OS: Ubuntu 20.10

**My Solution**
Change Line https://github.com/vsg-dev/VulkanSceneGraph/blob/c894bfebf89b6afbce8519d63b74db8c7afd3ce1/src/vsg/vk/ShaderCompiler.cpp#L545
std::ifstream fin(foundFile, std::ios::ate);

**Comment by robertosfield** [comment]
I've checked your suggestion into VSG master, could you test it out and let me know how you get on.

#be3c78794a1c604a13239db6e235655fcff69562

**Comment by Lachei** [comment]
Perfect, it works now. Thanks for the quick update.
