### ISSUE TITLE
MatrixTransformProxy, good idea or bad?

### ISSUE THREAD

**Issue by wangii** [vsg-dev/VulkanSceneGraph#337]
**Is your feature request related to a problem? Please describe.**
It is often the case that two or more meshes share same MatrixTransform parent node but requires to be in different shaders. It is possible to manually synchronize the matrix value but could be error prone.

**Describe the solution you'd like**
Therefore, I think a MatrixTransformProxy whose matrix point to an existing MatrixTransform would solve the problem.

**Describe alternatives you've considered**
Two possible solutions:
- manually synchronize values, which is error prone.
- A template solution that could cover all cases of Group + somekind of attribute.

**Comment by robertosfield** [comment]
I can't help feel that what you are asking for is not what you need.  However, I don't have a clear understanding of the usage case that you are struggling with, as you can already mix and match different shaders with the MatrixTransform by placing the StateGroup above the MatrixTransform, or having the different stats in different subraphs below the MatrixTransform,

**Comment by wangii** [comment]
it's entirely possible to solve the shader-matrixtransform mixture with existing facilities. I'm looking for a more shader centric approach to organize the graph. besides, my understanding is that there is a performance penalty switching shaders often.

**Comment by robertosfield** [comment]
On Fri, 24 Sept 2021 at 11:33, Linan Wang ***@***.***> wrote:

> it's entirely possible to solve the shader-matrixtransform mixture with
> existing facilities. I'm looking for a more shader centric approach to
> organize the graph. besides, my understanding is that there is a
> performance penalty switching shaders often.
>
> There is a penalty in switching various state, the pipeline being a big
one.  However, that doesn't change my high level question about needing to
understand what you are trying to achieve, as the solution you've proposed
will have it's own pitfalls, and may not even be the best way to solve the
problem.  As I don't know enough about your specific application usage case
I really can't provide any insight and what solution is best.

Creating a example that others can compile up and test first hand would be
a good way of providing the problem you are trying to solve more
efficiently while avoiding any ambiguity or confusion that can arise from
written word.

>
