### ISSUE TITLE
vec arithmetic operators don't allow casting of float to double

### ISSUE THREAD

**Issue by sbrkopac** [vsg-dev/VulkanSceneGraph#353]
**Describe the bug**
When trying to use arithmetic operators and vectors, VSG won't implicitly convert a double to a float.

**To Reproduce**
[vsg-vec-issue (1).txt](https://github.com/vsg-dev/VulkanSceneGraph/files/7457626/vsg-vec-issue.1.txt)

**Expected behavior**
Program should compile with a conversion from double to float warning.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version master

**Additional context**

I didn't have a chance to dig deep but slapping this directly into ```t_vecX``` allows it to compile.

```
inline t_vec3 operator*(value_type rhs)
{
       return t_vec3(value[0] * rhs, value[1] * rhs, value[2] * rhs);
}
```

**Comment by robertosfield** [comment]
Now I have a bit more time to focus on pure open source work on the VSG I'd like to work through outstanding reported Issues.  For this particular item I'm not clear on what your expectations are.  In general I'm preferring explicit typing to catch errors.

The vsg-vec-issue (1).txt example you provide has some arithmatic that I can't figure out what you intended by them.  Comments added below:

    vsg::vec2 vec2;

    auto v2a = vec2 + 1.0;  // no idea what this is meant to do, pretty sure we shouldn't allow this
    auto v2b = vec2 * 1.0; // scaler multiplication of (float, float, float) * double, should it return a (double, double, double)
    auto v2c = vec2 / 1.0; // scalar division of (float, float, float) . double, again what would the return type be?
    auto v2c = vec2 - 1.0; // just like for + 1.0, this really doesn't have  any normal meaning, so shouldn't be allowed


What is important me is users write clear and reliable code with the VSG, at times this may mean forcing more explicit types.

**Comment by sbrkopac** [comment]
Thanks for the notes and the feedback. You are correct with the use cases. I believe my original use case that spotted some of this was multiplication of a vector and a matrix. I had to cast something to a double in order to prevent it from erroring. I wrote this up before I left for vacation and will have to review my notes. I will update my dev environment to master and get back to you.
