### ISSUE TITLE
Build failure on Xubuntu 18.04/Cmake 3.10.2

### ISSUE THREAD

**Issue by robertosfield** [vsg-dev/VulkanSceneGraph#364]
I just tried the build of VulkanSceneGraph master on Xubuntu 18.04 with CMake 3.10.2 and get a build failure due to the new vsgMarcros.cmake related to JOIN sub-command.  The output of running cmake is below:

@rhabacker do you have any thoughts?

------- cmake console output:

-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Reading 'vsg_...' macros from /home/robert/Dev/VulkanSceneGraph/cmake/vsgMacros.cmake - look there for documentation
-- Using Vulkan version check embedded in vsg
CMake Error at cmake/vsgMacros.cmake:367 (list):
  list does not recognize sub-command JOIN
Call Stack (most recent call first):
  cmake/FindVulkan.cmake:21 (vsg_check_min_vulkan_header_version)
  CMakeLists.txt:35 (find_package)

CMake Error at cmake/vsgMacros.cmake:370 (message):
  Could NOT find Vulkan: Found unsuitable version "", but required is at
  least "1.2.162" (found
  /home/robert/3rdParty/VulkanSDK/1.2.176.1/x86_64/lib/libvulkan.so)
Call Stack (most recent call first):
  cmake/FindVulkan.cmake:21 (vsg_check_min_vulkan_header_version)
  CMakeLists.txt:35 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/robert/Dev/VulkanSceneGraph/CMakeFiles/CMakeOutput.log".

**Comment by robertosfield** [comment]
Looking at CMake docs, the JOIN sub-command is 3.12 or later, so won't work with Ubuntu 18,04: [cmake list documentation](https://cmake.org/cmake/help/latest/command/list.html)

**Comment by sbrkopac** [comment]
I think we need to do a bit of a realignment on cmake and the way we take advantage of it. I've been working on the CI integration for vsgFramework but it's been clunky. Currently the way the macros work is I can't just run a stand-alone configure or ExternalProject on VSG. I will try to get to a write up this week.

**Comment by sbrkopac** [comment]
I've opened a draft PR that forces CI to use CMake Version 3.7. Please see the actions logs for the kick-outs. We definitely have to bump the version to at least support the latest visual studio generators.

**Comment by robertosfield** [comment]
Thanks for thoughts @sbrkopac.  

I've checked in this fix to  CMake_JOIN_fix branch: c2348804b44a9cefba31f659fa4b0d8cf6c882af

I have built under 18.04 and 21.04 and it all works fine for me.

**Comment by robertosfield** [comment]
@sbrkopac I see the PR has failed, not looked into the details yet.  Why did you choose 3.7.x?  Simply because I used the in the cmake_minimum_required() in the VulkanSceneGraph/CMakeLists.txt?

I don't recall the exact reason why I chose 3.7, will need to look back through the logs, in my original checkin for VulkanSceneGraph/CMakeLists.txt I used 3.5 as the minimum version, but must have updated that when I introduced the cmake configure support.

I would like to make sure the VSG still builds with out of box dependencies on Ubuntu 18.04 where possible, so this would imply a min of cmake-3.10.x, but there may be reason to go back further if it can make life easier for a wider range of users without seriously compromising what we can achieve in our cmake scripts.

**Comment by robertosfield** [comment]
I have start looking at the CMake errors #365 and to start off it looks like the use of DESCRIPTION on the project(vsg...) entry in VulkanSceneGraph/CMakeLists.txt is a problem in anything before 3.8...

Note sure how best to resolve all the possible problems.  Create a branch for CMake 3.7 compatible build?   Another for 3.8, Another for 3.9, 3.10 etc?   Perhaps it's worth starting with 3.10 and then working backwards to see what we have to change to get things compiling.

Thoughts?

I'm wrapping up open source work now, I'll be working with clients for the rest of the week.  I'll be fully available again for open source work from Thursday next week.

**Comment by sbrkopac** [comment]
@robertosfield Yes, I picked 3.7 because that is what is defined as our minimum. I would think it would make sense to track the Vukan ecosystem but it looks like some of their repos go back early versions of 3 which definitely isn't ideal. For reference [here](https://cliutils.gitlab.io/modern-cmake/chapters/intro/newcmake.html) is some very light documentation on CMake upgrades.

We could definitely take that approach - I'm not sure if there is a matrix handy that gives us Operating System releases and their CMake installation version. Since VSG is a cpp17 project (except for filesystem) that is a good baseline to understand which operating systems it can and can't support out of the box.

I think a major goal prior to 1.0 should be to make sure that VSG can be imported into upstream projects via FetchContent and AddExternalProject [docs](https://www.scivision.dev/cmake-fetchcontent-vs-external-project/).

**Comment by robertosfield** [comment]
I'm closing this issue as I've merged a fix for the Xubuntu 18.04 build issue.
