### ISSUE TITLE
Glsl file reading adds null characters on windows

### ISSUE THREAD

**Issue by Lachei** [vsg-dev/VulkanSceneGraph#377]
**Describe the bug**
On windows when glsl files are read, the string size of the returned source is longer than the actual c-string it contains. The rest of the string has null characters as fill.
This is a problem when one is having `#include` in the shader source code as after the first include the shader compiler thinks the whole shader code is already done resulting in an incomplete shader.

**To Reproduce**
Easiest is to compile and start the vulkanPBRT project at commit https://github.com/Lachei/VulkanPBRT/pull/17/commits/d234626ecbca3ae449ab1ab82e68dafecbcb5317 under windows.

**Expected behavior**
Each shader source loaded should be a valid string without multiple null characters at the end.

**Additional context**
This bug does not exist on Linux!
Most likely this behaviour is becuase of the same reason this error occurs: https://stackoverflow.com/q/2641639.
If so, i would suggest to use the solution  mentioned by https://stackoverflow.com/a/15691006.
Also more information about the bug including screenshots can be seen here https://github.com/Lachei/VulkanPBRT/pull/17#issuecomment-993661650.

**Comment by robertosfield** [comment]
@Lachei  Does this look like the appropriate fix for vsgXchange?

diff --git a/src/glsl/glsl.cpp b/src/glsl/glsl.cpp
index 661de3f..91fa900 100644
--- a/src/glsl/glsl.cpp
+++ b/src/glsl/glsl.cpp
@@ -53,7 +53,7 @@ vsg::ref_ptr<vsg::Object> glsl::read(const vsg::Path& filename, vsg::ref_ptr<con
 
         std::string source;
 
-        std::ifstream fin(found_filename, std::ios::ate);
+        std::ifstream fin(found_filename, std::ios::ate | std::ios::binary);
         size_t fileSize = fin.tellg();
 
         source.resize(fileSize);

**Comment by robertosfield** [comment]
I have created a vsgXchange branch for this change: [WindowsGLSLFix](https://github.com/vsg-dev/vsgXchange/tree/WindowsGLSLFix)

**Comment by Lachei** [comment]
Yes, bug fixed with these changes.

**Comment by robertosfield** [comment]
Thanks, I've merged the changes with vsgXchange master.
