### ISSUE TITLE
Compilation vsg\maths\transform generated transform.obj covered vsg\nodes\Transform on platform windows.

### ISSUE THREAD

**Issue by simwangrui** [vsg-dev/VulkanSceneGraph#383]
Describe the bug:
Windows file names are case insensitive.Compilation vsg\maths\transform generated transform.obj covered vsg\nodes\Transform generated Transform.obj on platform windows. leaded to a link error in the compiled vsgconv project.

**Comment by robertosfield** [comment]
Wow, what a heap of crap Visual Studio is.  Two different .obj files with two different paths and filenames and it still gets confused, it's 2021, not 1971.  Arrgggg...

 My best guess for a solution would be to renamed src/vsg/maths/transform.cpp to something different.  Do you think thisb hack might work?

**Comment by simwangrui** [comment]
I try rename  vsg/maths/transform.cpp to vsg/maths/transform2.cpp,compile other projects without link errors，it is work ok.

**Comment by robertosfield** [comment]
OK, I'll decide upon a new name for transform.cpp and check this in.

**Comment by sbrkopac** [comment]
If changing the file names is not appropriate then changing the output on visual studio to have relative object file names instead via cmake.

I'll look at this in the morning.

**Comment by robertosfield** [comment]
On Tue, 21 Dec 2021 at 10:02, Sam Brkopac ***@***.***> wrote:

> If changing the file names is not appropriate then changing the output on
> visual studio to have relative object file names instead via cmake.
>
> I'll look at this in the morning.
>
>  i think it'll be simpler to just rename the file, at least it'll be the
same across all platforms.

**Comment by robertosfield** [comment]
I have renamed src/maths/transform.cpp to src/maths/maths_transform.cpp: 0b60c6b8801ce9aa133e3e4fce6c2d42f6901099
