### ISSUE TITLE
3d scene show lighting differences compared with osg

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/VulkanSceneGraph#385]
**Describe the error**
Loading the file attached to #308 with vsgviewer, you can see drawing problems on the right side in the attached screenshot. The illuminations looks different.

**Reproduce**
1. checkout git repo from vsg-dev/vsgFramework unter src
2. run 
```
cmake -B ~/src/vsgFramework-build -S ~/src/vsgFramework -DBUILD_OpenSceneGraph=1 -DBUILD_SHARED_LIBS=1
cmake --build ~/src/vsgFramework-build
```
3. unpack the zip file attached to vsg-dev/VulkanSceneGraph#308 in ~/src
4. run `LD_LIBRARY_PATH=~/src/vsgFramework-build/lib64 VSG_FILE_PATH=~/src/vsgFramework-build/src/vsgExamples/data ~/src/vsgFramework-build/bin/vsgviewer ~/src/demo.osgt`.
5. see error

**Expected behavior**
The viewer should display similar illuminations as the reference image created with osgviewer on the left.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/602903/147080130-ce8c3ebc-76fc-4269-b719-34bc36c7b9c2.png)

**Desktop (please fill in the following information):**
 - Operating system: openSUSE Linux
 - version 15.2

**Additional context**
Vulkan 1.2.189 has been installed

**Comment by robertosfield** [comment]
The vsgXchange OSG loaders doesn't yet support lines or text.

Could you move this Issue to vsgXchange as this is where the limitation lines as the VSG itself support both lines and text, it's just the vsgXchage OSG loader that is not mapping things across at this point.

**Comment by rhabacker** [comment]
There seems to be support for moving an issue https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository, but I cannot see the related  option - may be a maintainer can do this ?

**Comment by rhabacker** [comment]
> Could you move this Issue to vsgXchange 

Done and updated this ticket to point out another issue. I also used vsgFramework when building to get more easily reproducible builds, which still needs https://github.com/vsg-dev/vsgFramework/pull/4.

**Comment by robertosfield** [comment]
Thanks for moving the ticket, was too busy chasing up awkward Assimp build problems yesterday to come up for air.  I'll now close this Issue.

**Comment by rhabacker** [comment]
I filed https://github.com/vsg-dev/VulkanSceneGraph/issues/388 for the recognized lighting issue.
