### ISSUE TITLE
why not  support ios?

### ISSUE THREAD

**Issue by qianqians** [vsg-dev/VulkanSceneGraph#387]
do we have a plan support ios?
MoltenVk is also support ios!

**Comment by robertosfield** [comment]
Technically it should be possible.  Personally I only have Linux machines to work with, no Apple devices or expertise iOS support will be to the community.

Back in April 2021 @rollastre asked the same question on [vsg-users](https://groups.google.com/g/vsg-users) and said he would create a fork to attempt a port.  I haven't heard a progress report so assume the porting effort has stalled.  [vsg-users "What about iOS?"](https://groups.google.com/g/vsg-users/c/v0Aoh8YJFOo/m/xSLjqa9XCwAJ) thread.

While I can't help with direct porting work for iOS I'm happy to help out where I can.  Joining the vsg-users google group would a helpful for coordinating work.
