### ISSUE TITLE
Ability to decompose a matrix

### ISSUE THREAD

**Issue by sbrkopac** [vsg-dev/VulkanSceneGraph#397]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to decompose scale, orientation, or translation (I believe this is just the vsg::matrix[3][0]/[1]/[2]).

**Describe the solution you'd like**
Something similar to how glm lets you decompose: https://glm.g-truc.net/0.9.6/api/a00204.html

**Comment by robertosfield** [comment]
Progress so far: [decompose branch](https://github.com/vsg-dev/VulkanSceneGraph/compare/decompose)

Tomorrow I'll implement a simpler one that just provides translation, orientations and scale.

**Comment by robertosfield** [comment]
I have decided to go with a similar variants of vsg::decompose() so have diverged from the GLM version, The changes are now merged with master: #415
