### ISSUE TITLE
Wrong dynamic state's sType

### ISSUE THREAD

**Issue by simwangrui** [vsg-dev/VulkanSceneGraph#398]
**Describe the bug**
DynamicState.cpp 

void DynamicState::apply(Context& context, VkGraphicsPipelineCreateInfo& pipelineInfo) const
{
    auto dynamicState = context.scratchMemory->allocate<VkPipelineDynamicStateCreateInfo>();

    dynamicState->sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
                                           //here should be VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
    dynamicState->pNext = nullptr;
    dynamicState->flags = 0;
    dynamicState->dynamicStateCount = static_cast<uint32_t>(dynamicStates.size());
    dynamicState->pDynamicStates = dynamicStates.data();

    pipelineInfo.pDynamicState = dynamicState;
}

**Comment by robertosfield** [comment]
Thanks for spotting the error - an example of copy and paste bug.  I've checked in a fix for this to VSG master:

   #930b95b624eb4016220c1b9f3c358ac78618e56f
