### ISSUE TITLE
VR support

### ISSUE THREAD

**Issue by VTaredi** [vsg-dev/VulkanSceneGraph#402]
Any plans for support OpenVR\OpenXR?

**Comment by robertosfield** [comment]
@geefr has written a prototype [vsgVR](https://github.com/geefr/vsgvr) project integrating OpenVR with the VSG.

[vsg-users OpenVR/XR thread](https://groups.google.com/g/vsg-users/c/BAXxwuPpbgc)

[youtube video](https://www.youtube.com/watch?v=ZA7syEMAIMo)
