### ISSUE TITLE
Ability to pass a BoundingBox/Sphere to Builder

### ISSUE THREAD

**Issue by sbrkopac** [vsg-dev/VulkanSceneGraph#410]
**Describe the solution you'd like**
It would be very handy to be able to take ```vsg::bbox``` or ```vsg::sphere``` and be able to pass it to ```vsg::Builder``` to get a visualization.

**Comment by robertosfield** [comment]
As quick experiment I've added vsg::GeometryInfo consturctors and set methods that take vsg::box and vsg::sphere:

[Builder_box_sphere](https://github.com/vsg-dev/VulkanSceneGraph/tree/Builder_box_sphere)

I've hacked vsgintersection to use this and I'm not yet getting the results I expected for the sphere so will need to so investigate what is going on.  This is just a quick end of day hack, I'll return to it and complete it over the weekend.

**Comment by robertosfield** [comment]
I've now settled the implementation and checked in support for setting vsg::GeometryInfo using either vsg::box or vsg::sphere, this allows you to use the shorthand:

  builder->createSphere(vsg::GeometryInfo(vsg::dsphere(center, radius)));

Changes are now merged with VSG master: #413
