### ISSUE TITLE
Design rationale of Nodes ?

### ISSUE THREAD

**Issue by nyue** [vsg-dev/VulkanSceneGraph#419]
I am looking at this

https://github.com/vsg-dev/VulkanSceneGraph/blob/2a12449a305d9b1c1abf066174ae76b4bc0c3738/include/vsg/nodes/Node.h#L20

and wondering if it is suitable for my use case of a geometry pipeline with interactive 3d graphics.

Is there some high level cook/update/evaluate trigger that will evaluate the DAG ? I am thinking of connecting some slider bar even to update the frame number (hence equivalent time) to update the nodes. One use case would be animated cache.

Another use case would be a custom node e.g. Scale node, as the user update the scale value, the DAG gets evaluated so all the connected nodes down stream of a node having it's geometry updated will cascade to all to downstream nodes.

Are the Nodes in VSG for such purposes ?

Cheers

**Comment by robertosfield** [comment]
Hi Nicholas,

I don't know how to answer your question as I don't feel like it's actually a question about the design rationale of vsg::Node, but a wider question about how one implements dynamic scene graph elements, but even that I'm not clear on.

What experience with scene graphs do you have?  This will help us pitch the level of answer.

When you talking about a slider, do you mean a slider bar in a GUI element?  Are you thinking of ImGui, Qt, 3d geometric representation?

In terms of scaling, the usually way to do this with a scene graph is decorate the subgraph you want to transform/scale with a vsg::Transform node, typically a vsg::MatrixTransform but you could subclass from vsg::Transform to create your own custom way of generating a transformation matrix. 

It is aso possible to modify the geometry data to scale the scene but this is very expensive compared to using a transform node, one would only modify the geometry directly as a one off, or if there is some non uniform transformation you'd want to use - something like a particle system.

The best place for questions like this is the [vsg-users google group](https://groups.google.com/g/vsg-users) rather the the Issue tracker which is based used for reporting bugs.

Cheers,
Robert.

**Comment by robertosfield** [comment]
Hi Nicholas,

I don't know how to answer your question as I don't feel like it's actually
a question about the design rationale of vsg::Node, but a wider question
about how one implements dynamic scene graph elements, but even that I'm
not clear on.

What experience with scene graphs do you have?  This will help us pitch the
level of answer.

When you talking about a slider, do you mean a slider bar in a GUI
element?  Are you thinking of ImGui, Qt, 3d geometric representation?

In terms of scaling, the usually way to do this with a scene graph is
decorate the subgraph you want to transform/scale with a vsg::Transform
node, typically a vsg::MatrixTransform but you could subclass from
vsg::Transform to create your own custom way of generating a transformation
matrix.

It is aso possible to modify the geometry data to scale the scene but this
is very expensive compared to using a transform node, one would only modify
the geometry directly as a one off, or if there is some nonuniform
transformation you'd want to use - something like a particle system.

Cheers,
Robert.
