### ISSUE TITLE
Unable to Cmake on Windows, Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR)

### ISSUE THREAD

**Issue by jaguardo** [vsg-dev/VulkanSceneGraph#428]
**Describe the bug**
Followed the directions here:
https://vsg-dev.github.io/VulkanSceneGraph/INSTALL.html#detailed-instructions-for-setting-up-your-environment-and-building-for-microsoft-windows

```
The VSG has one dependency, the Vulkan SDK itself. LunarG provides a convenient installer for the Vulkan SDK and runtime on Windows.

[Vulkan Downloads](https://vulkan.lunarg.com/sdk/home#windows)

From there download and install the Vulkan SDK (1.1 or later) and the Vulkan runtime. Once installed we need to let CMake know where to find the Vulkan SDK. The VSG uses the VULKAN_SDK environment variable to find the Vulkan SDK so go ahead and add it.

VULKAN_SDK = C:\VulkanSDK\1.1.85.0

So now we have the Vulkan SDK installed and findable by CMake so we can go ahead and build VSG. Below are simple instructions for downloading the VSG source code, generating a Visual Studio project using CMake and finally building and installing VSG onto your system.

git clone https://github.com/vsg-dev/VulkanSceneGraph.git
cd VulkanSceneGraph
cmake . -G "Visual Studio 15 2017 Win64"

After running CMake open the generated VSG.sln file and build the All target. Once built you can run the install target. If you are using the default CMake install path (in Program Files folder), ensure you have started Visual Studio as administrator otherwise the install will fail.

It’s recommended at this point that you add the VSG install path to you CMAKE_PREFIX_PATH, this will allow other CMake projects, like the vsgExamples project to find your VSG installation. CMAKE_PREFIX_PATH can be set as an environment variable on you system.

CMAKE_PREFIX_PATH = C:\Program Files\VSG
```

**To Reproduce**
When I include VSG in another project, I receive this error:
```
Reading 'vsg_...' macros from C:/Program Files/vsg/lib/cmake/vsg/vsgMacros.cmake - look there for documentation
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR)
  (Required is at least version "1.2.162.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindVulkan.cmake:99 (find_package_handle_standard_args)
  C:/Program Files/vsg/lib/cmake/vsg/FindVulkan.cmake:18 (find_package)
  C:/Program Files/vsg/lib/cmake/vsg/vsgConfig.cmake:5 (find_package)
```
I downloaded and installed 1.3.204.1 and set the env variables:

![image](https://user-images.githubusercontent.com/28798269/163461732-4ac16db5-a43f-4aea-8cbd-189f1ae27cee.png)

and

![image](https://user-images.githubusercontent.com/28798269/163461757-389f5c7e-2684-467c-81d1-6cda07efb6d9.png)

**Expected behavior**
Cmake should complete, as it appears that it found vsg?

**Desktop (please complete the following information):**
 - Win10, VS code (but didn't get that far!)

I looked at the vsgMacros.cmake, but the verbiage from cmake didn't precisely match the verbiage in that file... so I'll have to see if I can find where that error code is coming from.

**Comment by sbrkopac** [comment]
Hey @jaguardo,

I just checked on my build settings and what you should be sufficient. I also uninstalled my current version of Vulkan, cleared my environmental variables, re-installed Vulkan, cleared my CMake cache, and everything configured as expected. Did you make sure to close your cmake-gui after the installation? Restart explorer.exe? Or just do a restart? I'm also on CMake 3.20.

**Comment by jaguardo** [comment]
Thanks... I had restarted everything except a full reboot, but somehow must have missed something... not sure what but a full restart worked. Thanks!
