### ISSUE TITLE
Following quasi-example code in renderpass.cpp code (line 341+) get error trying to make same calls on Windows

### ISSUE THREAD

**Issue by jaguardo** [vsg-dev/VulkanSceneGraph#430]
**Describe the bug**
Build errors:

```
no instance of constructor "std::vector<_Ty, _Alloc>::vector [with _Ty=vsg::SubpassDependency, _Alloc=std::allocator<vsg::SubpassDependency>]" matches the argument list
```
 
and
```
'initializing': cannot convert from 'initializer list' to 'std::vector<vsg::SubpassDependency,std::allocator<vsg::SubpassDependency>>' 
```

On a previous version of VSG (granted it was on linux), was able to compile the following code:

```
    VkSubpassDependency dependency = {};
    dependency.srcSubpass = VK_SUBPASS_EXTERNAL;
    dependency.dstSubpass = 0;
    dependency.srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    dependency.srcAccessMask = 0;
    dependency.dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    dependency.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    vsg::RenderPass::Dependencies dependencies{dependency};
```

as it was shown in renderpass.cpp at the time (prior to commit: [2d9cf67]?)

**To Reproduce**
we now try to run the same code with recent build and get those errors.

Attempted to modify the code to match that which is now in renderpass.cpp

```
    vsg::SubpassDependency dependency = {};
    dependency.srcSubpass = VK_SUBPASS_EXTERNAL;
    dependency.dstSubpass = 0;
    dependency.srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    dependency.srcAccessMask = 0;
    dependency.dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    dependency.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    vsg::RenderPass::Dependencies dependencies{dependency};
```

and get a error from "xmemory" (within MSVC):
```
'vsg::AttachmentReference::AttachmentReference(const vsg::AttachmentReference &)': cannot convert argument 1 from '_Ty' to 'const vsg::AttachmentReference 
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS Code, VS 2019 x64

**Additional context**
probably something simple I'm missing in the correct call to the functions

**Comment by robertosfield** [comment]
It's hard to know what might be going based on code fragments and the
explanation.  Is this a build error or a runtime error?

If a runtime error could you provide a stack trace?

Do any of the vsgExamples have this issue?

Could you provide a compilable application that illustrates the issue?

**Comment by jaguardo** [comment]
Its a build error.  I'll try the vsgExamples, thanks!

**Comment by jaguardo** [comment]
From within vsgExamples, looks like vsgsubpass has the same verbiage for the call to vsg::subpassDependency, 
https://github.com/vsg-dev/vsgExamples/blob/d1866a7588141b42395588e9cb102ffea441b792/examples/viewer/vsgsubpass/vsgsubpass.cpp#L72

and it builds (windows, 2019, debug only) - release build has a lnk2038 error:
```
 error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in vsgsubpass.obj
 ```
 Within the debug build, the demo doesn't make it past loading the shaders, exits here:
 https://github.com/vsg-dev/vsgExamples/blob/d1866a7588141b42395588e9cb102ffea441b792/examples/viewer/vsgsubpass/vsgsubpass.cpp#L103
 
Unfortunately, I'm only building a release version on my project, so I'm unable to duplicate it building in Debug to match yet...  However, since it at least builds with the debug version, there must be something else wrong with the way I'm approaching it and I'll open another issue/update this if I am able to find it.

**Comment by robertosfield** [comment]
I don't use Windows so can't help with VIsualStudio specific issues.  As far as I can tell all the code is valid.  My best guess is that there is some build inconsistency on your system such that VisualStudio is messing up linking.
