### ISSUE TITLE
Can VSG run on a browser based on the webassembly?

### ISSUE THREAD

**Issue by flyskyosg** [vsg-dev/VulkanSceneGraph#438]
Can VSG run on a browser based on the webassembly?

I plan to develop a new project, not based on WebGL, that can create earth scenes and local small scenes。

**Comment by robertosfield** [comment]
On Thu, 5 May 2022 at 04:28, flyskyosg ***@***.***> wrote:

> Can VSG run on a browser based on the webassembly?
>
No, not at this point.  I have briefly looked at WebGPU does have some
overlap with Vulkan capabilities, but when I looked at it it was still in
the proposal stage, I haven't attempted to build anything for it let alone
the full VSG.

My focus right now is to get the VSG to 1.0 on the desktop.  The next port
would likely be the new safety critical version of Vulkan.  A port to
WebGPU might be possible, but I have no idea how much work this would be,
or whether it's even technically possible.

> I plan to develop a new project, not based on WebGL, that can create earth
> scenes and local small scenes。
>
Best of luck,
Robert.

**Comment by flyskyosg** [comment]
Thank you for your reply, I'll try it here first, and discuss it if I have any questions.
