### ISSUE TITLE
VSG does not compile with MinGW gcc on Windows

### ISSUE THREAD

**Issue by PaulObermeier** [vsg-dev/VulkanSceneGraph#443]
To compile current trunk with MinGW gcc 7.2 on Windows I had to add several `__MINGW32__` statements in files FileSystem.cpp and Path.h.  
I also changed file Export.h, so that the "#pragma warning" statement is only functional, when compiling with MSC to avoid lots of warnings from gcc.

[MinGW.zip](https://github.com/vsg-dev/VulkanSceneGraph/files/8686433/MinGW.zip)

**Comment by robertosfield** [comment]
Could you generate a Pull Request with these changes? Thanks.

**Comment by PaulObermeier** [comment]
Sorry, no GIT installed.

**Comment by robertosfield** [comment]
I have downloaded your MinGW.zip and  am reviewing the changes.   

I wonder if the problem defined(WIN32) usage in the Path.h and FIleSystem.cpp would be better to changes to 
defined(_MSC_VER) rather than having blocks like:

#if defined(WIN32) && !defined(__CYGWIN__) && !defined(__MINGW32__)

Thoughts?

--

Your change in the makeDiectory(..) function that has a code path specifically for __MINGW32__  but the code is almost identical to the POSIX code path, just looks like a 0755 parameter is not passed.  Is the a difference to POSXI mkdir?

**Comment by robertosfield** [comment]
As a general guide, I'd like to keep the platform specific differences and checks as minimal and unobtrusive as we can get them. So if we can use a simpler #if declaration or unify code paths while still maintaining correct code then I'll be happy bunny.

**Comment by robertosfield** [comment]
I've merged the pragma change to include/vsg/core/Export.h.  I'm holding back on the others in case we can come up with an more minimal approach to the #if's.

**Comment by PaulObermeier** [comment]
The replacement with only #if defined(_MSC_VER) works for me with VS and gcc, see attached file.

Regarding mkdir: The MinGW envrionment only supplies the mkdir() function without the flags parameter

[FileSystem.zip](https://github.com/vsg-dev/VulkanSceneGraph/files/8689147/FileSystem.zip)
.

**Comment by robertosfield** [comment]
Thanks for the changes.  I looks to me like you've changed some places to use _MSC_VER but not all the places that might be possible.  

What is the situation with path separators in MinGW and CYGWIN? Are they Posix or Windows?

**Comment by robertosfield** [comment]
I'm currently think that it would be worth making a branch of the VSG for MinGW and Cygwin builds so we can look at al the changes together to help us keep track of patterns of changes and try out different combinations.

**Comment by PaulObermeier** [comment]
I'm only working with VisualStudio and MinGW, so don't know about the differences between Cygwin and MinGW.

**Comment by vsg-dev** [comment]
I only have Linux here so appreciate help with other platforms. I'm away from my dev system now, but once I return I'll see if I can figure out who contributed Cygwin code and see if they can check things.

**Comment by robertosfield** [comment]
I have had a bash at simplifying the Windows #if defined blocks to hopefully handle the needs of VisualStudio/MinGW/Cygwin better.  These changes are checked in the branch: (MinGW_Cywin)[https://github.com/vsg-dev/VulkanSceneGraph/tree/MinGW_Cywin]

@PaulObermeier could you test these changes out on MinGW?

**Comment by PaulObermeier** [comment]
Changes build fine with MinGW and VS.

**Comment by vsg-dev** [comment]
That's great news.  I'll go ahead and merge with master  I'll also do a call for testing under Cygwin.
