### ISSUE TITLE
Built-in Lightsource in VSG (since new serialization implementation)

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/VulkanSceneGraph#477]
**Describe the bug**
I have a little 3D scene. It is illuminated by two light sources (ambient and directional with absolute transform). There are no other light sources in my scene graph. After updating application to the new VSG I see a strange effect: instead of one reflection spot I get two and the brightness has doubled. The reflection spot itself seems to be color saturated due to too much brightness.

By modifying the light direction it turns out, that only one of the spots is moving (my one). Switching off my light sources, the scene is still illuminated by the mysterious light source.

Tested on Mac and Windows with Vulkan 1.3.216.

My light sources switched off:
![screenshot_nolightsource](https://user-images.githubusercontent.com/31243285/177263157-c2ada981-80bf-4999-b2cb-7c26fd5db894.png)

My light sources switched on:
![screenshot_with_lightsource](https://user-images.githubusercontent.com/31243285/177263183-b49ae691-81ee-4aa0-996b-6564dae4d85f.png)

What might be the reason for this behavior?

**Comment by robertosfield** [comment]
Hi Rainer,

I don't have your scene graph and viewer setup to know specifically what
might be going on.  I would be surprised if there is a correlation to the
clean up of serialization as this shouldn't touch upon any of the code
relating to shaders and lighting, so at this point I'd guess it's just
coincidence.

Given the description of the behavior you are seeing my guess is that a
default headlight is being assign to the vsg::View when you are
constructing your viewer, while another light is being assigned to the
scene graph.  The modern (last few months) lighting support built into the
shaders that vsg::Builder and the vsgXchange::Assimp use work support
dynamic lighting, you many or no lights in your scene on a per frame
basis.  Prior to the new lighting support the vsg::Builder/Assimp shaders
relied upon a single hardwired headlight direction.

The default headlight is something you can switch off when you set up your
viewer.  The two helper methods for constructing ComamndGraph + Rendergraph
have a bool for whether to add the head light or not, they both default to
adding the headlight:

    /// convenience function that sets up RenderGraph inside primary
CommandGraph to render the specified scene graph from the specified Camera
view
    extern VSG_DECLSPEC ref_ptr<CommandGraph>
createCommandGraphForView(ref_ptr<Window> window, ref_ptr<Camera> camera,
ref_ptr<Node> scenegraph, VkSubpassContents contents =
VK_SUBPASS_CONTENTS_INLINE, bool assignHeadlight = true);


    /// Convenience function that sets up RenderGraph and associated View
to render the specified scene graph from the specified camera view.
    /// Assigns the WindowResizeHandler to provide basic window resize
handling.
    extern VSG_DECLSPEC ref_ptr<RenderGraph>
createRenderGraphForView(ref_ptr<Window> window, ref_ptr<Camera> camera,
ref_ptr<Node> scenegraph, VkSubpassContents contents =
VK_SUBPASS_CONTENTS_INLINE, bool assignHeadlight = true);

My guess is you just need to add an extra ",
VK_SUBPASS_CONTENTS_INLINE,false" to your
createCommandGraphForView/createRenderGraphForView() calls.

Cheers,
Robert.

**Comment by rainergericke** [comment]
Thanks for the explanation. After implementing the changes, my software acts as expected again. I have another question about setting transparency. I know how to get transparent shapes and want to activate depth sorting now. This is my code snippet:

    if (phongMat->value().alphaMask < 1.0) {
        auto bounds = vsg::visit<vsg::ComputeBounds>(scenegraph).bounds;
        vsg::dvec3 center = (bounds.max + bounds.min) * 0.5;
        double radius = vsg::length(bounds.max - bounds.min) * 0.5;
        vsg::dsphere boundSphere;
        boundSphere.set(center[0], center[1], center[2], radius);
        auto depthSorted = vsg::DepthSorted::create(0,boundSphere,stateGroup);
        transform->addChild(depthSorted);
    } else {
        transform->addChild(stateGroup);
    }

When transparency is demanded this code crashes, when not set it runs. Do I am thinking the wrong way?

**Comment by robertosfield** [comment]
Hi Rainer,

On Tue, 5 Jul 2022 at 12:09, Rainer Gericke ***@***.***>
wrote:

> Thanks for the explanation. After implementing the changes, my software
> acts as expected again. I have another question about setting transparency.
> I know how to get transparent shapes and want to activate depth sorting
> now. This is my code snippet:
>
> if (phongMat->value().alphaMask < 1.0) {
>     auto bounds = vsg::visit<vsg::ComputeBounds>(scenegraph).bounds;
>     vsg::dvec3 center = (bounds.max + bounds.min) * 0.5;
>     double radius = vsg::length(bounds.max - bounds.min) * 0.5;
>     vsg::dsphere boundSphere;
>     boundSphere.set(center[0], center[1], center[2], radius);
>     auto depthSorted = vsg::DepthSorted::create(0,boundSphere,stateGroup);
>     transform->addChild(depthSorted);
> } else {
>     transform->addChild(stateGroup);
> }
>
> When transparency is demanded this code crashes, when not set it runs. Do
> I am thinking the wrong way?
>
> One of the performance tricks that the VSG uses to keep the RecordTraversl
as fast as possible is to avoid doing conditionals and container
reallocations during the traversal, instead relying upon the application
developer to make sure the appropriate containers are pre-allocated.  The
vsg::Viewer::compile(..) method analyses the scene graph you pass it and
allocates the required containers all for you. but if you add stuff after
the initial viewer.compile() then you'll need to handle allocation/resize
later as well.

One of these containers used by the RecordTraverall is the vsg::View's bins
container.  By adding the vsg::DepthSorted node you are adding a
requirement for a vsg::Bin to drop the subgraphs that need to be sorted in.

In the recent work on improving the dynamic scene graph support in the VSG
I added a vsg::updateViewer() function:


https://github.com/vsg-dev/VulkanSceneGraph/blob/master/include/vsg/viewer/Viewer.h#L146-L147

This is most implemented by the vsg::updateTasks(..) function:


https://github.com/vsg-dev/VulkanSceneGraph/blob/master/src/vsg/viewer/RecordAndSubmitTask.cpp#L210-L231

The vsgdynamicload thread on vsg-user goes into details of this work:

   https://groups.google.com/g/vsg-users/c/k9XBUYDu8fg/m/OB9wbkvCCQAJ

**Comment by rainergericke** [comment]
Thanks, I understand the basic idea behind it now.
