### ISSUE TITLE
Ability to compile without VulkanSDK

### ISSUE THREAD

**Issue by WSSDude420** [vsg-dev/VulkanSceneGraph#481]
Probably related to #480 as I found this out during it.

Project I wanted to use this with uses SDL and GLAD2. Wanted to move from custom renderer to some more robust one and stumbled upon issues right away with SDK. I include glslang along with SPIRV-Tools separately as part of my CMake project. I was unable to just add_subdirectory and have this project as submodule due to hard SDK requirement although I effectively include everything VSG would need already. GLAD2 provides Vulkan headers and loader, glslang is included as well via CMake project.

I had to remove hard-coded Vulkan requirement and change what it links to when I included this in my project and I dont know how much #480 relates to this issue because of it. Could be I did some replacement wrongly.

Using VulkanSDK is not possible with this project.

Anything I could do about this as a whole? There seems to be need of some CMakeLists rewrite honestly for this to work in some way properly from within add_subdirectory and for it to recognize custom loader+headers+glslang.

Maybe allowing to set custom library along with includes to link against via some CMake option could resolve this in some cleaner way.

**Comment by robertosfield** [comment]
You can use the VSG without VulkanSDK, you just need to install the Vulkan libs and headers, and have glslang and SPIRV-Tools available if you want to be able to compile GLSL->SPIR-V automaticity.

There is a vsgSDL project developed by a member of the VSG community, so use with SDL is not a problem.  GLAD2 is new to be so I really don't have any idea what it provides for you and why you'd want to use it instead of just linking to vulkan.

**Comment by WSSDude420** [comment]
Project this would be used with has its own VulkanSDK you could say. It is a submodule which includes parts of the SDK. SDK is compiled via custom CMakeLists file, it adds library targets things link against. Vulkan::Vulkan is not therefore available and it fails to link. What is available in my case is glad2_vulkan. SDL is abstracted in other module, API is used for input and windowing stuff from it. 

I looked at vsgSDL, managed to make some implementation with it yesterday but had trouble using GLAD2 mainly. SDL was not that big of an issue to include.

In my current setup and my VSG fork, VSG is built statically and linked against glad2_vulkan + I changed some other things related to building on Windows platform as I also encountered issues with that (will make PR probably for this in particular, issue with UNICODE being defined)

I managed to use the loader finally now this way so this is dealt with I guess. Only problem still is that I have quite different CMakeLists now compared to origin which would definitely show in the future.
I could install VulkanSDK for this, but there would be library disparity between things that way.

It would be really nice to have some option to override Vulkan include and link library at least if nothing else definitely.
What also seems to be causing issue, particularly with SDL2 is uninstall target, as SDL2 defines it also and when included via add_subdirectory, it yields two of those targets and fails to continue CMake configure.

**Comment by WSSDude420** [comment]
Should have probably mention it, but this seems to be an issue with find_package in general for the specified usecase (included inside other CMake project directly, which already includes targets find_package searches for)

So this affect glslang as well as was previously mentioned, but that in particular is not that big of an issue as we use custom shader compiler anyway and we did not wanted to replace it.

**Comment by WSSDude420** [comment]
Made those PRs I mentioned somewhere in here related to Windows compilation with UNICODE and one related to CMake paths when including in another CMake.

**Comment by remoe** [comment]
I'm able to compile VSG 1.0.6 with vulkan-headers and vulkan-loaders. It doesn't need the full vulkan-sdk ?
