### ISSUE TITLE
Crash in CompileManager due to null context

### ISSUE THREAD

**Issue by rolandhill** [vsg-dev/VulkanSceneGraph#490]
Hi Robert,

I got a crash in CompileManager due to a NULL context. CompileManager was being called from DatabasePager. Please refer to the annotated code below.

During compile(), "ref_ptr<View> view = context->view;" is called with context = 0x00. Inspecting compileTraversal shows that there is only 1 context and it's not NULL. The only thing I can think of is that another thread is manipulating the contexts in compileTraversal at the same time - is this a possibility? It all worked perfectly paging tiles for several minutes before the crash.

Sorry, I can't put together example code to demonstrate this. I'm using the stock DatabasePager implemented via a merge operation as per your examples.

Regards,
Roland

CompileResult CompileManager::compile(ref_ptr<Object> object, ContextSelectionFunction contextSelection)
{
    CollectResourceRequirements collectRequirements;
    object->accept(collectRequirements);

    auto& requirements = collectRequirements.requirements;
    auto& binStack = requirements.binStack;

    CompileResult result;
    result.maxSlot = requirements.maxSlot;
    result.containsPagedLOD = requirements.containsPagedLOD;
    result.views = requirements.views;

    auto compileTraversal = compileTraversals->take_when_available();

    // if no CompileTraversals are available abort compile
    if (!compileTraversal) return result;

    std::list<ref_ptr<Context>> contexts;
    if (contextSelection)
    {
        for (auto& context : compileTraversal->contexts)
        {
            if (contextSelection(*context)) contexts.push_back(context);
        }
    }
    else
    {
        contexts = compileTraversal->contexts;
    }

    compileTraversal->contexts.swap(contexts);

    for (auto& context : compileTraversal->contexts) **<------ at time of crash compileTraversal contains 1 context, which is not NULL**
    {
        ref_ptr<View> view = context->view;                    **<------------ Context 0x00**
        if (view && !binStack.empty())
        {
            if (auto itr = result.views.find(view.get()); itr == result.views.end())
            {
                result.views[view] = binStack.top();
            }
        }

        context->reserve(requirements);
    }

    object->accept(*compileTraversal);

    //debug("Finished compile traversal ", object);

    compileTraversal->record(); // records and submits to queue
    compileTraversal->waitForCompletion();

    debug("Finished waiting for compile ", object);

    compileTraversals->add(compileTraversal);

    compileTraversal->contexts.swap(contexts);

    result.result = VK_SUCCESS;
    return result;
}

from

void DatabasePager::start()
{
    int numReadThreads = 4;

    //
    // set up read thread(s)
    //
    auto read = [](ref_ptr<DatabaseQueue> requestQueue, ref_ptr<ActivityStatus> status, DatabasePager& databasePager) {
        debug("Started DatabaseThread read thread");

        while (status->active())
        {
            auto plod = requestQueue->take_when_available();
            if (plod)
            {
                uint64_t frameDelta = databasePager.frameCount - plod->frameHighResLastUsed.load();
                if (frameDelta > 1 || !compare_exchange(plod->requestStatus, PagedLOD::ReadRequest, PagedLOD::Reading))
                {
                    // debug("Expire read request");
                    databasePager.requestDiscarded(plod);
                    continue;
                }

                auto subgraph = vsg::read_cast<vsg::Node>(plod->filename, plod->options);

                if (subgraph && compare_exchange(plod->requestStatus, PagedLOD::Reading, PagedLOD::Compiling))
                {
                    {
                        std::scoped_lock<std::mutex> lock(databasePager.pendingPagedLODMutex);
                        plod->pending = subgraph;
                    }

                    // compile plod
                    if (auto result = databasePager.compileManager->compile(subgraph)) **<----------- called from here**
                    {
                        plod->requestStatus.exchange(PagedLOD::MergeRequest);

                        // move to the merge queue;
                        databasePager._toMergeQueue->add(plod);
                    }
                    else
                    {
                        debug("Failed to compile ", plod, " ", plod->filename);
                        databasePager.requestDiscarded(plod);
                    }
                }
                else
                {
                    debug("Failed to read ", plod, " ", plod->filename);
                    databasePager.requestDiscarded(plod);
                }
            }
        }
        debug("Finished DatabaseThread read thread");
    };

    for (int i = 0; i < numReadThreads; ++i)
    {
        _readThreads.emplace_back(read, std::ref(_requestQueue), std::ref(_status), std::ref(*this));
    }
}

**<--------------------- Inspection of compileTraversal at crash ----------------------->**
_ptr:
0x7fffedce77d0
vsg::Inherit<vsg::Visitor, vsg::CompileTraversal> (base):
vsg::Inherit<vsg::Visitor, vsg::CompileTraversal>
contexts:
{...}
[0]
_ptr:
0x7fffedce7810

**Comment by robertosfield** [comment]
I yet don't have enough info to start looking into it.  Which VSG examples would be a suitable starting place?

Are you able to recreate problems with the stock vsgviewer loading models/openstreetmap.vsgt?

`   vsgviewer models/openstreetmap.vsgt
`
Or

`   vsgpagedload --osm
`

**Comment by robertosfield** [comment]
I re-read you Issue report and still can't figure out how I might create the problem without something I can run and test to recreate it.

The only odd things I can glean from your description is "I'm using the stock DatabasePager implemented via a merge operation as per your examples."  This seams a bit odd as when using the DatabasePager you shouldn't need to do any merge operation as this will be done automatically for you by the Viewer/DatabasePager links that are provided by default.  

The merge operation is only something I'd expect users to need if they don't use the DatabasePager, instead use their own read threads like the vsgdynamicload example does.

The DatabasePager is just written to handle PagedLOD databases.

**Comment by rolandhill** [comment]
Hi Robert,

I meant the PagedLOD was added as a subgraph using the merge operation.
From there, the database pager took over.

Don't spend any more time on this. I repulled all the libraries today and
rebuilt everything and the crash hasn't happened again. I don't know if
there was a change in one of the VSG libraries or if I just got things out
of synch. Hopefully the problem doesn't come back.

Thanks for thinking about it.

Regards,
Roland

**Comment by robertosfield** [comment]
With threading issues like this it's easy for issues to appear and disappear with little notice.  Fingers crossed it was just a build/older VSG issue.  I'll close this Issue for now, if the problem reappears and it looks related we can repoen this Issue.
