### ISSUE TITLE
Dynamic CommandGraphs secne： when adding new CommandGraph,then re-setupThreading main thread will block on submissionCompletedBarrier->arrive_and_wait()

### ISSUE THREAD

**Issue by simwangrui** [vsg-dev/VulkanSceneGraph#493]
Hi，
I am learning VSG multithreading record and submit. this part of the code is designed very skillfully, which is an excellent work, and I like it very much.
I encountered a small issues when testing dynamic commandgraphs.When adding new CommandGraph,then re-setupThreading main thread will block on submissionCompletedBarrier->arrive_and_wait().
I tracked the code and found that stopthreading called status->set (false); However, when re-setupthreading, status->set (true) is not called, causing other threads to exit the thread when the while loop  judging:
 while (data->frameBlock->wait_for_change(frameStamp)) 
{
    ......
}
 Because the number of fences is less than 1 + numvalidtasks, the main thread will block in_ submissionCompleted->arrive_ and_ wait().

I'm calling status->set (true) before creating frameblock, and it works very well.

 _threading = true;
status->set(true); //adding this line
_frameBlock = FrameBlock::create(status);
 _submissionCompleted = Barrier::create(1 + numValidTasks);

Best wishes

**Comment by robertosfield** [comment]
Would it be possible to provide an example that illustrates this usage case so I can reproduce the problem and test the workaround.  

I can then ponder on how best to handle this usage case, and potentially tweak the VSG interface/implementation.

Thanks.

**Comment by simwangrui** [comment]
Hi,
I modified the vsgwindows example to reproduce this issues. The program creates three commandgraphs and enables multithreading. After running 1000 frames, the thread is re-established, which will also reproduce the issues I encountered.

Best wishe
[vsg_threading_test.zip](https://github.com/vsg-dev/VulkanSceneGraph/files/9247757/vsg_threading_test.zip)
s

**Comment by robertosfield** [comment]
On Wed, 3 Aug 2022 at 04:41, simwangrui ***@***.***> wrote:

> I modified the vsgwindows example to reproduce this issues. The program
> creates three commandgraphs and enables multithreading. After running 1000
> frames, the thread is re-established, which will also reproduce the issues
> I encountered.
>

Thanks, I'm able to reproduce the bug with this example.  I'll be digging
into the issue this morning.

**Comment by robertosfield** [comment]
I've now reviewed the example, the related code and agree that right solution is to reset the status to true.  I've added this and checked it into VSG master:

7054a2e76c155e705e1593b435c527bf4f36323a

With this the test program works fine after the second Viewer::setupThreading() call.  Thanks for the help resolving this bug.
