### ISSUE TITLE
Can Viewer's deviceWaitIdle function include devices that are not associated with vsg local windows?

### ISSUE THREAD

**Issue by simwangrui** [vsg-dev/VulkanSceneGraph#494]
Hi,
Now Viewer's deviceWaitIdle function only enum devices associated width vsg local window,

void Viewer::deviceWaitIdle() const
{
    std::set<VkDevice> devices;
    for (auto& window : _windows)
    {
        if (window->getDevice()) devices.insert(*(window->getDevice()));
    }

    for (auto& device : devices)
    {
        vkDeviceWaitIdle(device);
    }
}

sometime I  am using docking imgui with glfw window.I am using vsg rendering 3D scene to RTT,which creating the device not associate with vsg local window.so l must call vkDeviceWaitIdle instead.
Can Viewer's deviceWaitIdle function include devices that are not associated with vsg local windows?

Best wishes

**Comment by robertosfield** [comment]
I have made the Viewer::deviceWaitIdle() and a few other Viewer methods virtual to allow users to override them if they require.  

I have also added checking of the RecordAndSubmitTasks's CommandGraph's Device when assembling the list of devices to do a vkDeviceWaitIdle(device) call.  This ensures that the wait idle includes headless or compute on only command graphs.  

I have checked these changes in #495.

For applications that have other devices that you need to wait for then you can even subclass from Viewer and override deviceWaitIdle() or just call idle on these additional devices.
