### ISSUE TITLE
incompatible C-linkage specification

### ISSUE THREAD

**Issue by psi29a** [vsg-dev/VulkanSceneGraph#515]
**Describe the bug**
On macOS, it seems like LLVM is spitting out a lot of warnings as vsg/core/Version.h is specifying an incompatible C linkage.

```
/Users/bret/Workspace/private/VulkanSceneGraph/cmake-build-relwithdebinfo/include/vsg/core/Version.h:40:43: warning: 'vsgGetVersion' has C-linkage specified, but returns user-defined type 'struct VsgVersion' which is incompatible with C [-Wreturn-type-c-linkage]
    extern VSG_DECLSPEC struct VsgVersion vsgGetVersion();
                                          ^
1 warning generated.
```

This gets generated almost for every .o file that is produced.

**Comment by psi29a** [comment]
It seems that initialising the struct members in the header is not "allowed". That initialisation needs to occur on the cpp side.

**Comment by robertosfield** [comment]
Thanks for figuring this out.
