### ISSUE TITLE
Github workflow Cygwin build failing

### ISSUE THREAD

**Issue by robertosfield** [vsg-dev/VulkanSceneGraph#534]
I have just manually run the windows-mingw-cygwin action and MinGW succeeds, but Cywin fails:

[https://github.com/vsg-dev/VulkanSceneGraph/actions/runs/3337513716](https://github.com/vsg-dev/VulkanSceneGraph/actions/runs/3337513716)

@sbrkopac It looks like it's failing due to the setup of Cywin rather than the build of the VSG itself.  As I don't have any expertise in this area I don't know where to start with resolving the problem so would appreciate help.

**Comment by sbrkopac** [comment]
I've been looking into this but not sure how to solve it yet.

**Comment by robertosfield** [comment]
Looks like we aren't alone: https://github.com/egor-tensin/setup-cygwin/issues/9

I am now thinking that we may just have to disable to cygwin test.

**Comment by sbrkopac** [comment]
Glad to see this is an upstream problem. I've tried a few fixes but it really blows out the code. It looks like there is a workaround that I'll try to get to very early next week.
