### ISSUE TITLE
Workflow build-docs fails

### ISSUE THREAD

**Issue by robertosfield** [vsg-dev/VulkanSceneGraph#535]
I noticed that build-docs workflow hasn't been running as it was tracking the "main" branch that doesn't exist for the VSG, so I tweaked the build-docs.yml to allow it to be manually invoked, so it now runs but fails:

[https://github.com/vsg-dev/VulkanSceneGraph/actions/runs/3337673549](https://github.com/vsg-dev/VulkanSceneGraph/actions/runs/3337673549)

With the message:

     Path does not exist /home/runner/work/VulkanSceneGraph/VulkanSceneGraph/html

@sbrkopac You originally wrote this .yml file, does the error ring any bells?

**Comment by sbrkopac** [comment]
Not sure why this decided to break now. I also see some other issues with it. I'll dig into this a bit later in the day today.

**Comment by robertosfield** [comment]
Any progress?

**Comment by sbrkopac** [comment]
Hey Robert, taking a look at this - I don't really even remember the purpose of this? It doesn't seem to do much. Do you remember if this was originally meant to run doxygen and publish the docs to master?

**Comment by robertosfield** [comment]
On Wed, 2 Nov 2022 at 07:47, Sam Brkopac ***@***.***> wrote:

> Hey Robert, taking a look at this - I don't really even remember the
> purpose of this? It doesn't seem to do much. Do you remember if this was
> originally meant to run doxygen and publish the docs to master?
>
> I didn't even recall it was there!

I presume the role would be build and publish the docs, I can't see any
other reason for it.

**Comment by rhabacker** [comment]
I'm currently extending the vsg_add_target_xxx to support submodule/fetchcontent builds, see https://github.com/rhabacker/VulkanSceneGraph/tree/fix-cmake-features

**Comment by rhabacker** [comment]
And here https://github.com/vsg-dev/VulkanSceneGraph/issues/565

**Comment by robertosfield** [comment]
@rhabacker We are getting very close to a release now so I'm not looking to merge any more significant changes, once 1.0 is out we can consider more extensive changes.

Do your changes resolve the Issue highlighted into this thread?  If so then could you point out what is required to fix the immediate problem and we can review this.  Thanks.

**Comment by rhabacker** [comment]
> Do your changes resolve the Issue highlighted into this thread?

How can this reproduced ? Are the normal CI running on pr affected by this issue ?

**Comment by rhabacker** [comment]
>  I'm not looking to merge any more significant changes to merge any more significant changes

The changes from this pr uses a very simple pattern: for each x in vsg_add_target_x,  a project specific target is added and a dependency to x is added. An there are two changes where PROJECT_SOURCE_DIR is used instead of CMAKE_CURRENT_SOURCE_DIR to always follow the PROJECT_xxx pattern.

**Comment by robertosfield** [comment]
On Wed, 9 Nov 2022 at 13:55, Ralf Habacker ***@***.***> wrote:

> I'm not looking to merge any more significant changes to merge any more
> significant changes
>
> The changes from this pr uses a very simple pattern: for each x in
> vsg_add_target_x, a project specific target is added and a dependency to x
> is added. An there are two changes where PROJECT_SOURCE_DIR is used instead
> of CMAKE_CURRENT_SOURCE_DIR to always follow the PROJECT_xxx pattern.
>
> I review them so I know the pattern.

At this point so close to a release I have to become more and more risk
averse.  Every change has to be tested across all platforms for as wide a
range of end user applications as we can.  Each time we introduce something
new that cycle has to start again for the whole community.

**Comment by rhabacker** [comment]
> Each time we introduce something new that cycle has to start again for the whole community.

You can also understand this as a restriction fix, so it's nothing new.

**Comment by rhabacker** [comment]
> How can this reproduced ? 

This can be reproduced with any normal build, since the documentation is not built by default. On Linux, simply run `make docs` to build the documentation.

**Comment by robertosfield** [comment]
However you want to phrase it there is a risk involved in changing build files this close to a release, and doesn't change the extra round of testing that it will require.

**Comment by rhabacker** [comment]
You can reduce the risk by adding additional tests to CI. With https://github.com/vsg-dev/VulkanSceneGraph/pull/567 and rebasing this pr you can see if document creation still works.

**Comment by robertosfield** [comment]
I will merge AFTER 1.0.0, not before. You might not appreciate the risks, but I do.
