### ISSUE TITLE
about ref_ptr operator<() function is right?

### ISSUE THREAD

**Issue by longlongwaytogo** [vsg-dev/VulkanSceneGraph#561]
**Describe the bug**
at file ref_ptr  defined this:
 bool operator<(const ref_ptr<R>& rhs) const { return (rhs._ptr < _ptr); }

I think this is wrong, because the operator object is rhs,so 
"_ptr < rhs._ptr "  will return the right result.
 
So, written like this, whether it has other reasons?

**Comment by robertosfield** [comment]
Well spotted, that looks like a copy and paste bug.  I will do review/fix this morning.
