### ISSUE TITLE
vsg_add_target_xxx macros are not working anymore in submodule/fetchcontent builds

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/VulkanSceneGraph#565]
**Describe the bug**
Since the introduction of the fetchcontent based build mode several vsg_add_target_xxx macros are disabled with submodule builds.

**To Reproduce**
1. Inspect https://github.com/vsg-dev/VulkanSceneGraph/blob/master/CMakeLists.txt#L76 or https://github.com/vsg-dev/vsgXchange/blob/master/CMakeLists.txt#L46 for example 

**Expected behavior**
The mentioned  vsg_add_target_xxx macros should be usable in a submodule build

**Desktop (please complete the following information):**
 - OS: openSUSE Leap 15.4

**Comment by robertosfield** [comment]
This is not a bug, there has been no regression of FetchContent and submodule builds as they didn't work at all till the vsg_add_targets were disabled for these types of build.  Disabling these opened the door to FetchContent and submodule builds.
