### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by fcami** [vsg-dev/VulkanSceneGraph#570]
**Describe the bug**

The project is licensed under the MIT license, but three files have different licenses:

***Apache License 2.0***
include/vsg/vk/vulkan.h

***BSD 3-Clause License***
src/vsg/utils/ResourceLimits.cpp
src/vsg/utils/ResourceLimits.h

Both the Apache License 2.0 and the BSD 3-Clause licenses are more restrictive than MIT, so I would expect at the bare minimum LICENSE.md to include an exception section. 
I am not a lawyer, and I have no idea what the implication(s)s are.

**Expected behavior**

LICENSE.md containing the list of files shipped under different licenses than the project itself.

**Comment by robertosfield** [comment]
We can add the mention of the license, but I'd prefer to resolve the issue by building new files from scratch ourselves that are MIT.

I will do a review to see how practical this might be today as it would be good to settle it all before 1.0.0.

**Comment by robertosfield** [comment]
I have resolve the GLSL licensing by removing the ResouceLimits.h and .cpp files, the defaults I recreated by hand:

https://github.com/vsg-dev/VulkanSceneGraph/compare/ResourceLimits

I need to do more testings before merging this with VSG master and the 1.0 branch,

**Comment by robertosfield** [comment]
@fcami I have have added mention of vulkan.h copyright to the LICENSE,md:

https://github.com/vsg-dev/VulkanSceneGraph/compare/LicenseModification

Does this look sufficient?

**Comment by fcami** [comment]
I am not a lawyer, but it is satisfactory to me since there aren't any discrepancies between that file and the rest of the VSG anymore. So +1.

**Comment by robertosfield** [comment]
Thanks for looking it over. #572 is now merged with VSG master.  I'll merge the VSG-1.0 branch, probably later today.
