### ISSUE TITLE
cmake target for generating `all.h` is not available in out of source builds

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/VulkanSceneGraph#575]
**Describe the bug**
An expected cmake is missing in out of source builds

**To Reproduce**
1. run the following commands on linux:
$ mkdir ~/src && cd ~/src
$ git clone https://github.com/vsg-dev/VulkanSceneGraph.git
$ cd VulkanSceneGraph
$ cmake -B ../VulkanSceneGraph-build/
$ cmake --build ../VulkanSceneGraph-build/
$ cmake --build ../VulkanSceneGraph-build/ --target build_all_h
gmake: *** No rule to build  „build_all_h“

**Expected behavior**
The cmake build target should be available in out of source builds

**Desktop (please complete the following information):**
 - OS: openSUSE Leap
 - Version 15.4

**Comment by robertosfield** [comment]
I expect I might the only one who ever runs the make build_all_h target, so I'm not sure that the restriction to only working with in-source builds is an issue.

**Comment by rhabacker** [comment]
In-source builds contain fundamental problems as they are the main reason for the cmake target 'clobber' malfunctioning

**Comment by robertosfield** [comment]
On Mon, 14 Nov 2022 at 11:15, Ralf Habacker ***@***.***>
wrote:

> In-source builds contain fundamental problems as they are the main reason
> for the cmake target 'clobber' malfunctioning
>
It worked perfectly reliably before I merged your submission. The problem
is how your submission is implemented, not in source builds.

**Comment by rhabacker** [comment]
> It worked perfectly reliably before I merged your submission. 

Which uncovered the previously hidden synchronization problem with in-source builds when dependencies are used in conjunction with git clean.

**Comment by robertosfield** [comment]
I have got this make buld_all_h working on an out of source build, the changes to the build_all_h.cmake is checked into the branch: https://github.com/vsg-dev/VulkanSceneGraph/tree/out_of_source_builds.

I have local modifications to the VulkanSceneGraph/CMakeLists.txt that are also required by haven't yet checked them in as I still have more testing and possible fixes to do. Tomorrow I'll return to this topic and finish this off.

**Comment by robertosfield** [comment]
Fixed by #591.
