### ISSUE TITLE
vsgpagedlod does not work with --osm on windows

### ISSUE THREAD

**Issue by bclay1297** [vsg-dev/VulkanSceneGraph#578]
[vsgpagedlod](url) does not work with --osm on windows.  This problem was traced back to vsgXchange curl.cpp
SSL does not work in the curl current configuration 

Added 
    curl_easy_setopt(_curl, CURLOPT_SSL_OPTIONS, (long)CURLSSLOPT_NATIVE_CA);
after[vsgpagedlod](url) does not work with --osm on windows.  This problem was traced back to vsgXchange curl.cpp
SSL does not work in the curl current configuration 

Added 
    curl_easy_setopt(_curl, CURLOPT_SSL_OPTIONS, (long)CURLSSLOPT_NATIVE_CA);
after
 line 207 - curl_easy_setopt(_curl, CURLOPT_WRITEDATA, (void*)&sstr);

I am not sure is this should be conditionally compiled for windows or if the change will work on all platforms

Bruce

**Comment by robertosfield** [comment]
I have tested out CURLOPT_SSL_OPTIONS setting under Linux and it compiles fine and doesn't look to have an adverse effects, but the final code I've opted for adds an #if block around the relevant code.  I have also made the CURLOPT_SSL_OPTIONS setting settable by:

`     options->setValue("CURLOPT_SSL_OPTIONS", uint32_t(CURLSSLOPT_NATIVE_CA));
`
The changes are checked into curl_ssl branch of vsgXchange:

[https://github.com/vsg-dev/vsgXchange/tree/curl_ssl](https://github.com/vsg-dev/vsgXchange/tree/curl_ssl)

@bclay1297 could you test this out with a https model and see if it works fine.  If it does I'll merge the vsgXchange master the respective 1.0 branch.

**Comment by bclay1297** [comment]
Robert:
  Yes it does work.

Bruce

**Comment by robertosfield** [comment]
Thanks for the testing.  Good to hear things are working.
