### ISSUE TITLE
Clobber and uninstall errors

### ISSUE THREAD

**Issue by erikgruner** [vsg-dev/VulkanSceneGraph#583]
**Describe the bug**
Code building works fine, but solution also tries to run clobber and uninstall and throws errors

**To Reproduce**
1. Build from solution

**Expected behavior**
Code building works fine, but solution also tries to run clobber and uninstall and throws errors

**Screenshots**
2>Building Custom Rule C:/Users/vsguser/Documents/VSG/VulkanSceneGraph/src/vsg/CMakeLists.txt
3>'git' is not recognized as an internal or external command,
3>operable program or batch file.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\Users\vsguser\Documents\VSG\VulkanSceneGraph\build3\CMakeFiles\69898170591a491de00d1ce4a6542ed2\clobber-vsg.rule;C:\Users\vsguser\Documents\VSG\VulkanSceneGraph\CMakeLists.txt' exited with code 9009.
3>Done building project "clobber-vsg.vcxproj" -- FAILED.
5>------ Skipped Rebuild All: Project: clobber, Configuration: Release x64 ------
5>Project not selected to build for this solution configuration 
4>CMake Error at C:/Users/vsguser/Documents/VSG/VulkanSceneGraph/cmake/uninstall.cmake:14 (message):
4>  Cannot find install manifest:
4>  "C:/Users/vsguser/Documents/VSG/VulkanSceneGraph/build3/install_manifest.txt"
4>
4>
4>C:\Program Files (x86)\Microsoft Visual Studio\2019\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\Users\vsguser\Documents\VSG\VulkanSceneGraph\build3\CMakeFiles\69898170591a491de00d1ce4a6542ed2\uninstall-vsg.rule;C:\Users\vsguser\Documents\VSG\VulkanSceneGraph\CMakeLists.txt' exited with code 1.
4>Done building project "uninstall-vsg.vcxproj" -- FAILED.

**Desktop (please complete the following information):**
 - OS:  Windows 10

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rhabacker** [comment]
> 'git' is not recognized as an internal or external command,

This requires a bug fix not adding the cmake 'clobber' target when git is not present.

**Comment by robertosfield** [comment]
On Wed, 16 Nov 2022 at 10:52, Ralf Habacker ***@***.***>
wrote:

> 'git' is not recognized as an internal or external command,
>
> This requires a bug fix not adding the cmake 'clobber' target when git is
> not present.
>
> I agree, need to only implement features that can be run.

However, I would expect Erik has git on his system so it may well be a path
issue.

I'm focused on client work today, but tomorrow I'll set aside some time to
investigate this and other outstanding Cmake issues.

**Comment by robertosfield** [comment]
I have add a FindGit and protected the make clobber and make tag-test/tag-run targets with PR #592.  This should hopefully address the clobber errors.

I will now look at the uninstall error.
