### ISSUE TITLE
Export cmake variable `INSTALL_TARGETS_DEFAULT_FLAGS` as `VSG_INSTALL_TARGETS_DEFAULT_ARGS`

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/VulkanSceneGraph#586]
**Does your feature request relate to a problem? Please describe it.**
vsg exports the cmake variable ``INSTALL_TARGETS_DEFAULT_FLAGS``, which is used in calls to add_library() in vsg-dependent projects, which looks like this
```
install(TARGETS vsgvr ${INSTALL_TARGETS_DEFAULT_FLAGS})
```
does not show that this variable is provided by vsg.

**Describe the solution you want**.
This variable should be prefixed with `VSG_` to indicate the source from which this variable is defined, making it easier to find.
Additionally, renaming this variable to `VSG_INSTALL_TARGETS_DEFAULT_ARGS` would more accurately define the purpose of this variable, which looks then as 
```
install(TARGETS vsgvr ${VSG_INSTALL_TARGETS_DEFAULT_ARGS})
```
**Describe the alternatives you considered**.
This can be left as is, but will cause developers to waste time trying to figure out where this variable came from.

**Comment by robertosfield** [comment]
I have added the settings of the old var as well with the commit: #cb2c3cbf146d8a97f08d617ba7d627a5902a2f31

With this backwards compatibility with dependent projects that still use the INSTALL_TARGETS_DEFAULT_ARGS.  This gives us the possibility of merging the the VulkanSceneGraph1-.0 branch and being part of future 1.0.1 release.

**Comment by robertosfield** [comment]
I have merge the changes with PR #593 with VSG master.  I think it should be fine to be pulled into the 1.0 branch as well.
