### ISSUE TITLE
vsg depending library example

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/VulkanSceneGraph#587]
**Does your feature request relate to a problem? Please describe it.**
There is an example of creating a vsg-based application https://github.com/vsg-dev/MyFirstVsgApplication, but not of creating a library that depends on libvsg, which would make it easier for new developers to use the cmake macros provided by vsg.

**Describe the solution you want**.
The project mentioned should also create a vsg-based library as an example, or an additional project should be added that provides such an example.

**Describe the alternatives you have considered**.
No alternative

**Comment by robertosfield** [comment]
There is vsgXchange, vsgImGui, vsgQt, vsgPoints, these are all examples of libraries that depend upon the VSG.  I am hoping programmers are grown up and able to look at the available libraries for inspiration.

**Comment by rhabacker** [comment]
> There is vsgXchange, vsgImGui, vsgQt, vsgPoints

Are these projects always up to date regarding the use of vsg macros ?

**Comment by robertosfield** [comment]
On Thu, 17 Nov 2022 at 08:45, Ralf Habacker ***@***.***>
wrote:

> There is vsgXchange, vsgImGui, vsgQt, vsgPoints
>
> Are these projects always up to date regarding the use of vsg macros ?
>
> vsgXchange will be, that should be good enough.  If you want to create
such an example feel free to create one and it on your own github,  I don't
feel creating lots of lots of small projects to illustrate small parts of
the VSG makes any sense long term.
