### ISSUE TITLE
Setting verticalAlignment on vsg::Text is offsetting depth

### ISSUE THREAD

**Issue by franciszhi** [vsg-dev/VulkanSceneGraph#601]
**Describe the bug**
Setting vsg::StandardLayout::verticalAlignment for vsg::Text is offsetting depth instead of height

**To Reproduce**
Run vsgtext from latest "master" of vsg-dev/vsgExample
![image](https://user-images.githubusercontent.com/13976376/203254949-51a73840-a7db-444f-9bbf-2e87f2e87482.png)
Rotate the camera to this view to check that three of the text are not on one plane.
![image](https://user-images.githubusercontent.com/13976376/203255023-23297306-4c31-4456-b557-64d545ea6b61.png)

**Expected behavior**
From version 0.1.6
![image](https://user-images.githubusercontent.com/13976376/203254817-d1adee2d-5d1b-453c-8084-19429ae25d28.png)
On single plane when camera is rotated.
![image](https://user-images.githubusercontent.com/13976376/203255645-da9d952d-7f98-431d-9b29-48aeba402a55.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by robertosfield** [comment]
Well that's a peculiar regression :-)

I have recreated the problem on my system.  I can only guess a typo
somewhere in the layout setup has crept in and not spotted.

**Comment by robertosfield** [comment]
I've checked in a fix: d00774f1d509df80f0454c93328755948e2a972a

The fix is in VSG master and the 1.0 branch so will be part of the 1.0.1 release when I make it.

**Comment by franciszhi** [comment]
I have built with the latest commit and it is fixed! Thank you for resolving it so quickly.
