### ISSUE TITLE
Warning about deprecated symbol in compiling on MacOs Ventura

### ISSUE THREAD

**Issue by minghia** [vsg-dev/VulkanSceneGraph#631]
**Describe the bug**
Whilst compiling on a MacBook Pro running Ventura the following message is raised:
`VulkanSceneGraph/src/vsg/platform/macos/MacOS_Window.mm:803:12: warning: 'setWantsBestResolutionOpenGLSurface:' is deprecated: first deprecated in macOS 10.14 - Use NSOpenGLView instead. [-Wdeprecated-declarations]
    [_view setWantsBestResolutionOpenGLSurface:_traits->hdpi];
           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSOpenGLView.h:47:16: note: property 'wantsBestResolutionOpenGLSurface' is declared deprecated here
@property BOOL wantsBestResolutionOpenGLSurface API_DEPRECATED("Use NSOpenGLView instead.", macos(10.7,10.14));
               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSOpenGLView.h:47:16: note: 'setWantsBestResolutionOpenGLSurface:' has been explicitly marked deprecated here`

Not sure if this is necessary after 10.14 as this is on the [https://developer.apple.com/documentation/appkit/nsview/1414938-wantsbestresolutionopenglsurface](url) entry:

> Important

For applications linked on macOS 10.15 or later, the default value of this property is true. For applications linked on macOS 10.14 or earlier, the default value of this property is false to keep binary compatibility.

**To Reproduce**
1.  Create a build directory
2. Run cmake ../VulkanSceneGraph
4. The warning message appears.

**Expected behavior**
The compilation should complete without warnings.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: MacBook Pro
 - OS: 13.0.1 (22A400)
  - Browser: N/A
 - Version N/A

**Additional context**
N/A

**Comment by robertosfield** [comment]
I don't have a macOS or iOS system, or knowledge about it so have to defer to members of the community of how best to resolve this compile warning.

@geefr, @iconiqlabs, @rainergericke, or any other devs that have Apple experience/knowledge could you reflect on the warnings and let me know what would be appropriate to do resolve this warning.  I would be good to resolve this for 1.0,2 release that I'll likely make in the next week or so.

**Comment by rainergericke** [comment]
A brute force solution is to set line 803 in a comment, so it will not be compiled. For Macos 13, 12, 11 and 10.15 the graphic resolution will be always be high density, since this is the default. It also means we are unable to set it to low density by setting the rsp. window trait in VSG. Macos 10.14 and earlier would get low resolution settings by default.

**Comment by robertosfield** [comment]
On Thu, 8 Dec 2022 at 15:25, Rainer Gericke ***@***.***>
wrote:

> A brute force solution is to set line 803 in a comment, so it will not be
> compiled. For Macos 13, 12, 11 and 10.15 the graphic resolution will be
> always be high density, since this is the default. It also means we are
> unable to set it to low density by setting the rsp. window trait in VSG.
> Macos 10.14 and earlier would get low resolution settings by default.
>
>
I'm happy to merge a PR that comments out this line if that's what Apple
users would be happy with.  I'd rather not apply the changes myself as I
don't have any way of checking there aren't any issues.

**Comment by rainergericke** [comment]
I am doing some tests with the examples my own software project. When no problems occur, I will send a PR soon.

**Comment by geefr** [comment]
(Afraid my mac knowledge is outdated, and I don't have a dev system these days..)

That sounds like a sensible approach to me though, if there's no clear way to avoid the quirk. I assume the "use NSOpenGLView instead" isn't a simple port to a newer API?
