### ISSUE TITLE
Last commit breaks build on MacOS

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/VulkanSceneGraph#639]
**Describe the bug**
MacOS compiler refuses to build:

FAILED: src/vsg/CMakeFiles/vsg.dir/Release/io/FileSystem.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DGLSLANG_EShLangRayGen -DGLSLANG_ResourceLimits_maxDualSourceDrawBuffersEXT -DGLSLANG_ResourceLimits_maxMeshViewCountEXT -DCMAKE_INTDIR=\"Release\" -I/Users/rainerge/Documents/GitHub/VulkanSceneGraph/include -I/Volumes/Ramdisk/buildVSG/include -isystem /usr/local/include -O3 -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk -fPIC -std=gnu++17 -MD -MT src/vsg/CMakeFiles/vsg.dir/Release/io/FileSystem.cpp.o -MF src/vsg/CMakeFiles/vsg.dir/Release/io/FileSystem.cpp.o.d -o src/vsg/CMakeFiles/vsg.dir/Release/io/FileSystem.cpp.o -c /Users/rainerge/Documents/GitHub/VulkanSceneGraph/src/vsg/io/FileSystem.cpp
/Users/rainerge/Documents/GitHub/VulkanSceneGraph/src/vsg/io/FileSystem.cpp:119:19: error: variable has incomplete type 'struct stat64'
    struct stat64 stbuf;
                  ^
/Users/rainerge/Documents/GitHub/VulkanSceneGraph/src/vsg/io/FileSystem.cpp:119:12: note: forward declaration of 'stat64'
    struct stat64 stbuf;
           ^
1 error generated.

**To Reproduce**
Standard cmake configuration and build

**Expected behavior**
Complete build and install

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version [13]

**Comment by robertosfield** [comment]
Fixed by #638 :-)
