### ISSUE TITLE
VK_INDEX_TYPE_NONE_NV undefined

### ISSUE THREAD

**Issue by bookface** [vsg-dev/VulkanSceneGraph#64]
VK_INDEX_TYPE_NONE_NV undefined in BindIndexBuffer.h.

**Comment by vsg-dev** [comment]
VK_INDEX_TYPE_NONE_NV is new in latest VulkanSDK.  I have a look at whether using VK_INDEX_TYPE_MAX_ENUM will suffice as a "not set".

**Comment by vsg-dev** [comment]
I have checked into master the change to VK_INDEX_TYPE_MAX_ENUM, it's not as expressive a not set parameter but should be fine:

   https://github.com/vsg-dev/VulkanSceneGraph/commit/6ace897db8cafb872334969773aa23a47a409fcd
