### ISSUE TITLE
Code cleanup. Part three. Static code analysis fix.

### ISSUE THREAD

**Issue by artemkulyk** [vsg-dev/VulkanSceneGraph#654]
**Is your feature request related to a problem? Please describe.**
Consider analysis of the attached report and fixing some types of reported issues. Some issues are false-positive. Some issues are relevant and fixing can make the code more consistent with [CppCoreGuidelines](https://github.com/isocpp/CppCoreGuidelines).

[CLion_static_code_analysis.zip](https://github.com/vsg-dev/VulkanSceneGraph/files/10209573/CLion_static_code_analysis.zip)

**Describe the solution you'd like**
Inform me if you are interesting on fixing. I can do some work on it. We need to decide what kind of issues should be fixed, and what should be ignored.

**Comment by robertosfield** [comment]
I am busy with client work so will put this to the side till I have more time later in the week.  I will then do a review and provide my thoughts then.  Please don't race ahead and make lots of changes till I've done a review.
