### ISSUE TITLE
vsg::transform() - Incorrect mapping for Z_UP -> Y_UP

### ISSUE THREAD

**Issue by geefr** [vsg-dev/VulkanSceneGraph#678]
**Description**
Assuming I understand it, I think the mapping used for `vsg::transform(vsg::CoordinateConvention::Z_UP, vsg::CoordinateConvention::Y_UP, txfMat);` is incorrect. maths_transform.cpp line 420.

Specifically it looks like the X axis is being remapped to z, when in this case it should only affect the Y/Z axes.

**Context**
I'm doing various mappings between vsg and OpenXR (y-up), and fairly sure the issue isn't in my code.

Not urgent at all - I think I need to implement some other variations of this anyway within vsgvr.

**Comment by robertosfield** [comment]
Looks like we'll need to create a test program that could serve as unit test for this issue and other transform combinations. 

Short term you could try hinting to the loaders to load in Y_UP rather than the default of Z_UP using vsg::Options::sceneCoordinateConvention set to Y_UP.

**Comment by geefr** [comment]
I should note I haven't tested the loaders, it's possible they work despite this.
(and I'm working through a bunch of other vr coordinate system issues, but don't think those are from vsg itself)

**Comment by robertosfield** [comment]
I find it useful to think about world and eye coordinate separately, loaders load models in world coordinates with whatever coordinate frame makes sense for that "world", while eye coordinates are set in stone as Y up the screen, X to the right and Z out.

The VSG defaults to Z_UP as this in the conventional typically used in vis-sim/GIS/engineering/whole earth datasets.  The Y_UP convention is a bit of throwback to 2D windowing that was reused for CLip/Eye coords.

I suspect Y_UP for world for folks coming from 2D graphics to 3D, while the Z_UP is for folks used to engineering conventions to 3D graphics.

For the VSG it doesn't really care what convention you use for your world coords, it's just boils down to the model you've loaded and how you set up the camera view matrix,  I presume in the VR libs that are applying their own convention as they want to take over the projection and view matrix for each eye.  Ideally on would insulate this from the scene graph though, so have the VR just set up the view matrix based on the convention used in the scene graph.

None of this takes us away from need to do some QA and bug fixing where required on the coordinate mappings.

**Comment by robertosfield** [comment]
I spent time today looking the vsg::transform(..) function implementation and have changes that I think address the issues, but needed a bit more time testing before checking it.  Tomorrow I'll wrap it up and get it checked in.

**Comment by robertosfield** [comment]
I have checked in a test to vsgmaths in vsgExamples and fixes to the vsg::transform(..) implementation: d93d26578e709da2c91e01ebe4b1416b10c3639b.

@geefr could you checkout VSG master and let me know whether everything is working correctly now.

**Comment by geefr** [comment]
Sure - I'm fairly confident my code has a bug, but vsg::transform looks good, should have everything I need there. Can't see any new issues in my samples running against latest vsg master (windows or android).

There are a couple of typos in vsgmaths.cpp, otherwise looks like a solid test case, runs correctly on windows.
```
diff --git a/examples/maths/vsgmaths/vsgmaths.cpp b/examples/maths/vsgmaths/vsgmaths.cpp
index 4cf1862..fc2094f 100644
--- a/examples/maths/vsgmaths/vsgmaths.cpp
+++ b/examples/maths/vsgmaths/vsgmaths.cpp
@@ -255,10 +255,10 @@ int main(int /*argc*/, char** /*argv*/)

     std::cout << "x_to_y * y_to_x = "  << x_to_y * y_to_x << std::endl;
     std::cout << "x_to_z * z_to_x = "  << x_to_z * z_to_x << std::endl;
-    std::cout << "y_to_x * y_to_x = "  << y_to_x * x_to_y << std::endl;
+    std::cout << "y_to_x * x_to_y = "  << y_to_x * x_to_y << std::endl;
     std::cout << "y_to_z * z_to_y = "  << y_to_z * z_to_y << std::endl;
     std::cout << "z_to_x * x_to_z = "  << z_to_x * x_to_z << std::endl;
-    std::cout << "z_to_y * y_to_z = "  << y_to_z * z_to_y << std::endl;
+    std::cout << "z_to_y * y_to_z = "  << z_to_y * y_to_z << std::endl;

     return 0;
 }
```

**Comment by robertosfield** [comment]
Thanks, I've applied the typo fixes to vsgmaths.
