### ISSUE TITLE
MacOS Keys vsginput

### ISSUE THREAD

**Issue by kannode** [vsg-dev/VulkanSceneGraph#689]
**Describe the bug**
Running vsginput and pressing the z on the keyboard produces the following screen shot.
<img width="1257" alt="Screenshot 2023-01-12 at 4 07 44 PM" src="https://user-images.githubusercontent.com/32265121/212181757-18a18387-d9ca-440e-9e7c-18d8b67f5126.png">
which is incorrect.

**To Reproduce**
1) on MacOs run vsginput
2) press the z key
3) the output on the screen produces 'v' which is incorrect.

**Desktop (please complete the following information):**
Darwin ares 22.2.0 Darwin Kernel - Browser [e.g. chrome, safari]

This is likely due to the _keycodeMap in MacOS_Window.mm.
The keys are a mix of ASCII characters and MacOS virtual keys.

**Comment by robertosfield** [comment]
I don't have macOS to test, but on review of the code spotted a typo and have fixed: 9efbe3135a791cdc66513d4a70d8d9ab75c146ae

Could you checked out VSG master and let me know if it the issue is now resolved.

**Comment by kannode** [comment]
Good Eye. Yes. There are more issues with the MacOS code.
 I opened PR #697 which fixes this issue(#689) and also (#696) regarding modifier keys.
