### ISSUE TITLE
Build issue on generating binary package: 'git clone of glslang failed.  ShaderCompile support disabled.'

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/VulkanSceneGraph#784]
**Describe the bug**
Building a package on openSUSE shows the mentioned issue with the current git master branch

**To Reproduce**
1. Inspect the appended build log  [_log.txt](https://github.com/vsg-dev/VulkanSceneGraph/files/11259065/_log.txt)

**Expected behavior**
Shader compile support should not be disabled

**Desktop (please complete the following information):**
 - OS: openSUSE Leap
 - Version 15.4

**Additional context**
The problem arose with the change from using git submodule to git clone with this [commit](https://github.com/vsg-dev/VulkanSceneGraph/commit/d1b4203b3776da93ff235404eb5425acf566f389). The previous solution cloned the vsg git repo on https://build.opensuse.org before building and thus contained the embedded glslang automatically, whereas the new solution clones the glslang repo during building, which does not work on the mentioned platform as there is no internet access at the time.

**Comment by rhabacker** [comment]
I have seen in the vsgvr project that there is an option `VSGVR_OPENXR_PLATFORM` to select the preferred source for the OpenXR backend (see https://github.com/geefr/vsgvr/blob/8a4f9871b3de91504c979ba82b61d0e144c5a6dd/CMakeLists.txt#L40). Perhaps a similar vsg specific cmake variable will also help with this problem.

**Comment by robertosfield** [comment]
We between a rock and hard place on this one.  Either the automatically generated tarballs created by github for releases are broken by the use of the submodule or you disable the shader compiler when do internet access is available.

The VSG_SUPPORTS_ShaderCompiler selects whether to build with glslang or not, and will automatically disable if it can't download it. The VSG's CMake support also has CMake glslang_URL and glslang_branch to help control where it's pulled from.

We now build gslang as part of the core VSG because of trying to pull glslang in as 3rd party dependency so going back to this failed before so is something I want to go back to.

Would it be possible to create a script that clones both the VSG and glslang together?

**Comment by robertosfield** [comment]
@rhabacker, with SUSE bug report, is this something that might be resolved in the near term?

**Comment by robertosfield** [comment]
@rhabacker what is the situation with glsang availability in the SUSE ecosystem?  Potentially we could do a find_package(glslang) and specify a modern version to help avoid polluting the VSG codebase with trying to handle older glslang versions that we can build the VSG against when it's compiling glslang locally.

**Comment by rhabacker** [comment]
> @rhabacker, with SUSE bug report, is this something that might be resolved in the near term?

I would need to ask - but from my previous experience I doubt that it will be solved in the near time.

**Comment by rhabacker** [comment]
> @rhabacker what is the situation with glsang availability in the SUSE ecosystem? 

The package that would be used by libvsg is https://build.opensuse.org/package/show/games/glslang. It is a maintained package, see the history on https://build.opensuse.org/package/revisions/X11:Wayland/glslang

> Potentially we could do a find_package(glslang) and specify a modern version to help avoid polluting the VSG codebase with trying to handle older glslang versions that we can build the VSG against when it's compiling glslang locally.
 
The mentioned package for Linux has version 12.1.0 and for the mingw builds [glslang](https://build.opensuse.org/package/show/home:rhabacker:branches:games:mingw64/mingw64-glslang) is available with version 11.6, but can also be updated to 12.1.0 if needed.

**Comment by rhabacker** [comment]
> > @rhabacker, with SUSE bug report, is this something that might be resolved in the near term?
> 
> I would need to ask - but from my previous experience I doubt that it will be solved in the near time.

I ran a few more tests to make sure it wasn't a configuration issue on my end and was able to work around the problem (see https://github.com/openSUSE/obs-service-set_version/issues/85#issuecomment-1521631086 for details).

**Comment by robertosfield** [comment]
Does this mean you can do build the VSG once again?
