### ISSUE TITLE
When CompileTraversal apply to vsg::view changed the context's viewID and viewDependentState,but not restore these

### ISSUE THREAD

**Issue by simwangrui** [vsg-dev/VulkanSceneGraph#799]
Hi,
 The vsg lastest version. I have two vsg::view ，each vsg::view has its own resources. I use ContextSelectionFunction to compile resources under specific view, but it crashes.I found that the viewID of the context of CompileTraversal was modified, but not restore. In addition, does context->viewDependentState also need to be restore? I try restore those after view.traverse(*this), it work ok.

void CompileTraversal::apply(View& view)
{
    for (auto& context : contexts)
    {
	auto originViewID = context->viewID;   //code I insert
	auto originViewDependentState = view.viewDependentState.get();//code I insert

        context->viewID = view.viewID;
        context->viewDependentState = view.viewDependentState.get();
        if (view.viewDependentState) view.viewDependentState->compile(*context);

        // save previous pipeline states
        auto previousOverridePipelineStates = context->overridePipelineStates;
        auto previousDefaultPipelineStates = context->defaultPipelineStates;

        // assign view specific pipeline states
        if (view.camera && view.camera->viewportState) mergeGraphicsPipelineStates(context->defaultPipelineStates, view.camera->viewportState);
        mergeGraphicsPipelineStates(context->overridePipelineStates, view.overridePipelineStates);

        view.traverse(*this);

        // restore previous pipeline states
        context->defaultPipelineStates = previousDefaultPipelineStates;
        context->overridePipelineStates = previousOverridePipelineStates;

	context->viewID = originViewID;//code I insert
	context->viewDependentState = originViewDependentState;//code I insert
    }
}

**Comment by simwangrui** [comment]
Hi，
I am very pleased to create an example to reproduce this issue, which may take some time.

**Comment by robertosfield** [comment]
Do you have nested vsg::View?  

The current implementation assumes that vsg::View will be siblings.

**Comment by simwangrui** [comment]
Hi,
I setup two view siblings.Sorry, it took a long time to simplify my application scenario, but now I can reproduce this problem in a simple scenario.In my example, dynamically replace shaders and compile these shaders.
[two_view_compile_crash.zip](https://github.com/vsg-dev/VulkanSceneGraph/files/11411326/two_view_compile_crash.zip)

**Comment by robertosfield** [comment]
Thanks for the example, I've finally got some time to look into this issue.  I've downloaded the example, created a cmake file it and on running the example it crashes after a short period.  I presume this is reproducing the issue.

I will now look into what is causing the problem.

**Comment by robertosfield** [comment]
The first change I made was to add a wait before the scene graph modification to prevent the state being modified while it was still being rendered:

			// need to wait so that previous frames have completed before we modify the Vulkan objects that would otherwise still be actively used by the GPU.
			uint64_t timeout = 1000000000; // 1second in nanoseconds
			viewer->waitForFences(0, timeout);


Then as an experiment if I replace the lines:

			reload_shaders_and_compile_view(viewer, secondary_view, graphics_pipeline2);
			reload_shaders_and_compile_scene(viewer, scenegraph, graphics_pipeline);


With:

			reload_shaders_and_compile_view(viewer, main_view, graphics_pipeline);
			reload_shaders_and_compile_view(viewer, secondary_view, graphics_pipeline2);

It works fine.  I still need to do a wider review of the code and how it's using the compile support to figure out if the usage is wrong or that the compile support needs to change as you've suggested.

**Comment by robertosfield** [comment]
It took me a while to figure out exactly what was going wrong but finally figured it out and have applied a fix to the CompileTraversal::apply(View&) to prevent it used Context that are associated with other Views.

The fix is checked into VSG master : e775af7f08a1890ef7b5ba402474dce687790835

With this fix your example works correctly.
