### ISSUE TITLE
Window resize not effective if vsg::Switch off

### ISSUE THREAD

**Issue by rolandhill** [vsg-dev/VulkanSceneGraph#807]
Hi Robert,

I've tried to write a test program to show this bug, but haven't managed to get it to manifest. Therefore, I'll go ahead and explain it in the hope that it triggers an idea at your end.

I have a scene in which multiple different objects are displayed, each in it's own branch. All objects/branches are compiled dynamically and added to the scene graph via a queue in the frame loop.

Every branch is headed by a vsg::Switch followed by a vsg::StateGroup so that I can toggle object visibility and have somewhere to put different shaders.

The viewer has several handlers enabled, including WindowResizeHandler.

The scene can be loaded via a project file. If all the vsg::Switches are on, then the scene opens perfectly in a window. You can then maximise the window and all is good.

If one of the vsg::Switches is off, then the scene opens perfectly in a window (minus the invisible object). You then maximise the window and the scene looks as expected. If you then toggle the vsg::Switch on, the branch becomes visible, but it is still using the original window size (viewport?) before the resize. See the image below. The surface with the trees should take up the entire window. Both the correct scene and the too-small surface rotate/pan etc perfectly within their own viewports(??).

I notice that the WindowResizeHandler has several 'apply()' methods, including ones for StateGroup and BindGraphicsPipeline. Could it be that something in these nodes is not getting updated because the Switch is preventing traversal? I think I saw that a traversal can override the Switch mask so that it will always be executed - I can't imagine any nodes that would want to ignore a WindowResize event.

Hopefully this has triggered something for you, otherwise, any ideas are welcome.

I'm using master VSG from 8 may 2023 on Kubuntu with Nvidia 3070Ti. 

Regards,
Roland

![Screenshot_20230510_115000](https://github.com/vsg-dev/VulkanSceneGraph/assets/2024003/a484b54b-3e57-441a-9daf-e0f704da195b)

**Comment by robertosfield** [comment]
My best guess is that the WindowResizeHandler is honoring the traversalMask & switch masks and not traversing the switched off subgraphs.

Thankfully the vsg::Visitor class has an overrideMask member to MASK_OFF by default but changing this to MASK_ALL should address this issue and force traversal of all switch children regardless of there state.  I have change the WindowResizeHanlder to use overrideMask = MASK_ALL by default with the commit: 3bfc0c8f153b028a26a0debdc6e01ada2c6ab5ab.

This commit is checked into VSG master.

**Comment by rolandhill** [comment]
Thanks, Robert. That's fixed it.

Cheers,
Roland
