### ISSUE TITLE
vsg examples fail to build on macOS 13, when vsg was build as shared library

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/VulkanSceneGraph#814]
**Describe the bug**
With the latest commit, this build problem occurs on macOS 13:

FAILED: bin/vsgarrays 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -O3 -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/opt/homebrew/lib -framework Cocoa -framework OpenGL -framework IOKit -lz examples/core/vsgarrays/CMakeFiles/vsgarrays.dir/vsgarrays.cpp.o -o bin/vsgarrays  -Wl,-rpath,/Users/rainerge/Soft/Packs/VSG/lib -Wl,-rpath,/usr/local/lib  /Users/rainerge/Soft/Packs/VSG/lib/libvsg.1.0.6.dylib  /usr/local/lib/libvulkan.dylib && :
Undefined symbols for architecture arm64:
  "vsg::Array<vsg::t_vec2<float>>::accept(vsg::Visitor&)", referenced from:
      vtable for vsg::Array<vsg::t_vec2<float>> in vsgarrays.cpp.o
  "vsg::Array<vsg::t_vec4<float>>::accept(vsg::Visitor&)", referenced from:
      vtable for vsg::Array<vsg::t_vec4<float>> in vsgarrays.cpp.o
  "vsg::Array<float>::accept(vsg::Visitor&)", referenced from:
      vtable for vsg::Array<float> in vsgarrays.cpp.o
  "vsg::Array<vsg::t_vec2<float>>::accept(vsg::ConstVisitor&) const", referenced from:
      vtable for vsg::Array<vsg::t_vec2<float>> in vsgarrays.cpp.o
  "vsg::Array<vsg::t_vec4<float>>::accept(vsg::ConstVisitor&) const", referenced from:
      vtable for vsg::Array<vsg::t_vec4<float>> in vsgarrays.cpp.o
  "vsg::Array<float>::accept(vsg::ConstVisitor&) const", referenced from:
      vtable for vsg::Array<float> in vsgarrays.cpp.o

Looks there are hidden symbols which should be exported. This problem does not appear when vsg is built as static library.

**Comment by robertosfield** [comment]
The vsg::Array<T> implementations are all template ones.  The vsg::Array::accept(Visitor&) methods are provided by [include/vsg/core/Visitor.h](https://github.com/vsg-dev/VulkanSceneGraph/include/vsg/core/Visitor.h)  so perhaps what is missing from the vsgarrays example is an include of Visitor.h.

**Comment by robertosfield** [comment]
I have added #include <vsg/core/Visitor.h> and #include <vsg/core/ConstVisitor.h> to the vsgarrays example:

https://github.com/vsg-dev/vsgExamples/commit/7ac782bd968a2ff05ba1d336c8c8542a2a50f28b

@rainergericke could you test this change out?

**Comment by rainergericke** [comment]
Thanks! This change solves the problem.

**Comment by robertosfield** [comment]
Excellent, thanks for testing.
