### ISSUE TITLE
about BindIndexBuffer

### ISSUE THREAD

**Issue by orchidshelley** [vsg-dev/VulkanSceneGraph#815]
**Describe the bug**
 I need a index buffer  used both in compute shader and vertex shader. I  created it with vsg::BufferInfo::create(); The code is below.

>   // indexBuffer

    bufferSize = sizeof(uint32_t) * indexCount;
    auto indexBuffer = vsg::createBufferAndMemory(device, bufferSize,
        VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_INDEX_BUFFER_BIT,
        VK_SHARING_MODE_EXCLUSIVE, 
        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);

    auto indexBufferInfo = vsg::BufferInfo::create();
    indexBufferInfo->buffer = indexBuffer;
    indexBufferInfo->offset = 0;
    indexBufferInfo->range = bufferSize;
    indexBufferInfo->data = vsg::ref_ptr<vsg::Data>(indices);

when I used it  in vertex shader with a index buffer, I found that BindIndexBuffer has no appropriate constructor that the parameter is "vsg::BufferInfo", but BindIndexBuffer has a public member : ref_ptr<BufferInfo> indices;

>//BindIndexBuffer 

    class VSG_DECLSPEC BindIndexBuffer : public Inherit<Command, BindIndexBuffer>
    {
    public:
        BindIndexBuffer() {}
        explicit BindIndexBuffer(ref_ptr<Data> in_indices);

        ref_ptr<BufferInfo> indices;
        ...
     }

 so I create a bindIndexBuffer with the code below:

> vsg::ref_ptr<vsg::BindIndexBuffer> bind_index_buffer = vsg::BindIndexBuffer::create();
    bind_index_buffer->indices = indexBufferInfo;
    drawCommands->addChild(bind_index_buffer);

 But if I used "bind_index_buffer->indices = indexBufferInfo", the indexType is not correct， because these is  no chance to call the function "computeIndexType" .

**Expected behavior**
So I hope BindIndexBuffer add a new constructor with parameter "vsg::BufferInfo", and in the implementation of the new constructor,  function "computeIndexType" will be called and the " indexType" will be calculated correctly.

thank you.

**Comment by robertosfield** [comment]
I will look into the issue this afternoon.  Is there a vsgExample that does something similar that i could use in testing?

**Comment by robertosfield** [comment]
I've reviewed the code and indexType being in the protected section precludes the BufferInfo usage so I have I have moved the BindIndexBuffer::indexType into public scope and added a constructor for BufferInfo: 3c748ed2245d1dca112f71fe76712826df1898ef

**Comment by orchidshelley** [comment]
Thanks a lot.
