### ISSUE TITLE
Win32_Window.h     Multiple definitions of functions

### ISSUE THREAD

**Issue by bizehao** [vsg-dev/VulkanSceneGraph#826]
I used this header file of  Win32_Window.h
```
vsg::ButtonMask getButtonMask(WPARAM wParam);
uint32_t getButtonDownEventDetail(UINT buttonMsg);
uint32_t getButtonUpEventDetail(UINT buttonMsg);
```
These functions will be defined multiple times,  Should these functions be inline function.
```
inline vsg::ButtonMask getButtonMask(WPARAM wParam);
inline  uint32_t getButtonDownEventDetail(UINT buttonMsg);
inline  uint32_t getButtonUpEventDetail(UINT buttonMsg);
```

**Comment by robertosfield** [comment]
Could you create a PR for this fix, this way I can be sure that it's working for you. Thanks.

**Comment by robertosfield** [comment]
I have checked in the following changes:

75eeacd17b0f77050772049babc10b98d1f97e88
