### ISSUE TITLE
Crash in vsgdraw sample app on macOS

### ISSUE THREAD

**Issue by olegded** [vsg-dev/VulkanSceneGraph#85]
**Describe the bug**
`vsgdraw` app is crashing on macOS v10.14.5 (18F132) in [DeviceMemory::release, line 104](https://github.com/vsg-dev/VulkanSceneGraph/blob/master/src/vsg/vk/DeviceMemory.cpp#L104)

**To Reproduce**
1. Check out latest `vsg`, `osg2vsg` and `vsgExamples` source code
2. Run CMake and select XCode as a build environment
3. Compile
4. Run `vsgdraw` sample app

**Screenshots**
Here is a screenshot from debugger:
![Crash_in_MemorySlots_release](https://user-images.githubusercontent.com/6074172/61368938-41d86080-a88f-11e9-9eb8-6dbfe2e6b566.png)

If I get it right, the `_offsetSizes` map contains only one element and
```c++
--slotBefore;
```
is causing a crash in this case.

Couldn't test it on Windows yet, no idea about Linux. I'm not sure if having only one element in this map is a mac-specific problem or not yet.

Calling `--`-operator on an iterator pointing to the one and only element in the map (and to the first one) seems to be dangerous. I'm glad to help with any kind of debugging if required.

Adding additional check to the `if`-condition (e.g. number of elements in the map or `!= begin()`) fix es the problem.

**Comment by robertosfield** [comment]
Just tried vsgdraw under Linux and didn't get a crash, which is a shame as it would make ti much easier for me to home in on the bug, fix it and confirm the fix.  

I'll have a look at the code to see if I can get an idea of what might be amiss, I'll need to get you to test any fixes though.

**Comment by olegded** [comment]
Hi Robert,

Tested it under Windows, it doesn't crash. However, I'm hitting exactly the same path as on Mac:
- `--slotBefore;` is executed
- `_offsetSizes` contains only one element.

The difference is that `--slotBefore` doesn't crash on Windows (and according to your test it doesn't crash on Linux as well).

Just did this very simple test on both Windows and Mac:
```c++
std::map<int, int> mInt;
mInt[0] = 1;
auto it = mInt.begin();
--it;
```
Result on Mac: _crash!_
Result on Windows: `it` is `end`

Decrementing single element is undefined behavior, no? (e.g. found this question on StackOverflow: https://stackoverflow.com/questions/16334988/stdmapiterator-decrement-on-single-element)

**Comment by openscenegraph** [comment]
Yesterday I added debug messages to track the problem code and reproduce the decrement of the iterator when the it points to the first element, this is without a bug and it's just chance that this sin't failing under Windows and Linux.  I should have a fix for this today.

**Comment by vsg-dev** [comment]
I have applied a fix that should resolve this iterator bug:

   https://github.com/vsg-dev/VulkanSceneGraph/commit/0a26984d41462b76013e03117a3f232ae2a8eac5

Could you please test under OSX to make sure it's working now. Thanks,

**Comment by olegded** [comment]
Works!
