### ISSUE TITLE
How can I retrieve the names of all meshes from a scene?

### ISSUE THREAD

**Issue by WdsPjm** [vsg-dev/VulkanSceneGraph#866]
How can I retrieve the names of all meshes from a scene?

**Comment by andesengineering** [comment]
You can name your objects when the scene is created and then retrieve them
with vsg's metadata.    See Robert's excellent tutorial on this:
https://vsg-dev.github.io/vsgTutorial/foundations/MetaData

**Comment by WdsPjm** [comment]
thank you
