### ISSUE TITLE
Does your library handle little/big endian changes

### ISSUE THREAD

**Issue by timprepscius** [vsg-dev/VulkanSceneGraph#89]
I'm looking through the binary file writing operations. I'm not seeing code to handle little/big endian issues.

I assume it is there... Is it?

Thanks

**Comment by vsg-dev** [comment]
There is no endian support yet.  

From my current understanding this isn't presently an issue as ARM chips with Android and iOS default to little endian like Intel/AMD do.

My plan has to be encode an endian token and test into the ReaderWriter_vsg and have a BinaryInput variant that does the endian swap.  When it becomes necessary, i.e. users are hitting up against, I'll tackle this, with a project in it's infancy you have to choose what tasks to tackle first, so I'm tackle ones that will most critical to the widest range of users.

**Comment by timprepscius** [comment]
Cool

**Comment by vsg-dev** [comment]
As a bit of explanation of what I've had in mind is for the virtual void Input::read(size_t num, int16_t* value) etc. method implementations in the endian swapped subclasses from Input to handle the low level read and swap.  

Most likely there would be BinarySwapEndianInput subclasses from BinaryInput that override these read(..) methods and passes the read operation on to the BinaryInput and then post processes by doing the endian swap.  It should be pretty straight forward to implement.  The other bit of work would be to add the endian token into the binary header and this will be done the ReaderWriter_vsg class.
