### ISSUE TITLE
vsg::AnimationPath::Mode is broken

### ISSUE THREAD

**Issue by LeeRiva** [vsg-dev/VulkanSceneGraph#930]
It seems that the animation will always repeat, regardless of the mode member's value (it's initialized to ONCE)

**To Reproduce**
Sadly there's no dedicated sample for this one.. I used the vsgBuilder example to create an animation path (using two locations, at the first and last object created by the builder, offset back a little bit so that the objects are in view), added this to an animation path handler, added this event handler to the view (replacing the trackball handler), then ran the program..

**Expected behavior**
The REPEAT and FORWARD_AND_BACK modes should work, and in ONCE mode (the default) the animation should only play, well, once.

**Cause (I think)**
I think the problem lies in the AnimationPathHandler::apply(FrameEvent& frame) function overload: here, the 'time' member gets reset if the animation's period has been exceeded (so time is always in the [0; Period()] range) and the 'start_point' gets also reset (this is causing the 'always repeat' behaviour if mode is set to ONCE).

However, the 'time' member is used as an input in the AnimationPathHandler::apply(MatrixTransform& transform) and AnimationPathHandler::apply(Camera& camera) overloads, where they call AnimationPath::computeMatrix(double time) (which in turn calls AnimationPath::computeLocation(double time)) and **this** function actually expects its time argument to be the total duration from the time the animation was started (in the REPEAT and FORWARD_AND_BACK modes), see

`if (mode == REPEAT)
{
    time = locations.begin()->first + std::fmod(time - locations.begin()->first, period());
}
else if (mode == FORWARD_AND_BACK)
{
    double p = period();
    double t = std::fmod(time - locations.begin()->first, p * 2.0);
}`

**Resolution**
A quick way to get this working (while breaking the period/framerate output however) is simply to comment out assignment to the 'frameCount', 'time' and 'start_point' members after the '// reset time back to start' comment in AnimationPathHandler::apply(FrameEvent& frame)

I think the proper way to solve this is to have a dedicated clock::time_point for the current period's starting point.. the current period's time and framecount can then be computed based on this, without having to change time (and start_point, which is used to compute time).

**Comment by robertosfield** [comment]
It's probably time we had a dedicated vsganimationpath example to illustrate how to use it and to test it.

I originally implemented vsg::AnimationPath as a quick way of puling animations paths from the OSG's osg::AnimationPath so I could test the OSG side by side with the VSG for performance testing.  I haven't touched it much since this early work.

I have had a quick look at the vsg::AnimationPath implementation.  Resetting the AnimationPathHandler::start_point looks inappropriate, instead I think there probably should be independent variables used for the frame stats reporting.

**Comment by robertosfield** [comment]
I have implemented a fix that is now checked into VSG master: f28c4d23a44b6eecf4c2ee8090e831a239743be5

I added new timing variables to AnimationPathHandler to prevent their reset at the end of animation path from affecting the animation timing.  This fixes the FORWARD_AND_BACK and ONCE Modes.  

I tested it with the follow tweak of the vsgviewer example.  I won't check these changes into vsgExample as they are a bit hacky.

$ git diff
diff --git a/examples/app/vsgviewer/vsgviewer.cpp b/examples/app/vsgviewer/vsgviewer.cpp
index 3974fda..bdae35a 100644
--- a/examples/app/vsgviewer/vsgviewer.cpp
+++ b/examples/app/vsgviewer/vsgviewer.cpp
@@ -214,6 +214,9 @@ int main(int argc, char** argv)
                 return 1;
             }
 
+            if (arguments.read("--once")) animationPath->mode = vsg::AnimationPath::ONCE;
+            if (arguments.read("--bounce")) animationPath->mode = vsg::AnimationPath::FORWARD_AND_BACK;
+
             auto animationPathHandler = vsg::AnimationPathHandler::create(camera, animationPath, viewer->start_point());
             animationPathHandler->printFrameStatsToConsole = true;
             viewer->addEventHandler(animationPathHandler);

**Comment by LeeRiva** [comment]
I can confirm that this change works for me
