### ISSUE TITLE
[Proposal] Hourglass API (w/C-API)

### ISSUE THREAD

**Issue by JeroMiya** [vsg-dev/VulkanSceneGraph#96]
**Is your feature request related to a problem? Please describe.**
- Avoid use of non-trivial types in binary interface.
- Need to be able to safely distribute vsg in dynamic library form and update independently of application binary, while avoiding ABI-related binary compatibility issues and cross-lib memory alloc/free issues.
- Enables third party language bindings (Python, .Net, Java, etc...)

**Describe the solution you'd like**
The hourglass pattern is an architecture for C++ APIs which addresses the above points by implementing the library using C++ internally, but providing only a public C-API interface, on top of which a thin C++ interface (and other language bindings) can be built. For C++, the public interface is typically a header-only thin wrapper over the C-API.

**Describe alternatives you've considered**
An alternative to this pattern is various auto-generated C-API tools for C++ libraries, allowing for a native C++ interface (with ABI/binary-interface issues mentioned above), and an auto-generated C-API interface. This does not solve the ABI issues mentioned, and typically provides much lower quality C interfaces. A hand-written C-API using the public C++ API could provide a better solution but must be kept up-to-date via a labor intensive process for a third party.

**Additional context**
See for reference (motivations, description of architecture, arguments for/against):
https://www.slideshare.net/StefanusDuToit/cpp-con-2014-hourglass-interfaces-for-c-apis

Example of this architecture in action:
https://github.com/OSVR/OSVR-Core

**Comment by vsg-dev** [comment]
The VSG is a C++17 API, it's 100% meant for performance, it's a scene graph, it's whole role is to get data to the GPU as efficiently as it can, with no extra abstraction layers between the user and the data.

Your suggestion of adopting the Hourglass pattern would *massively* change the API, in essence we'd need to throw away what we have and start from scratch building it from the ground up with this new approach. However, this "new" approach wouldn't performance as well, require more work to write and maintain, which pretty well shoots itself in the foot in terms of being competitive with the current incarnation of the VSG.

If you want a scene graph to follow your proposal you'll need to find another project, or just come up one yourself.

**Comment by JeroMiya** [comment]
No problem, just a proposal to get ideas flowing. Note that, in this particular use case, maximum theoretical throughput (e.g. to avoid overhead of an extra jump instruction/stack-copy per node-visit) is not necessarily the primary priority over the availability of ABI-safe bindings.

Any chance of a reflective API or API metadata that the main project can maintain to allow third parties to code-gen a C-API that you don't have to maintain?
