### ISSUE TITLE
Font rendering displaying artefacts

### ISSUE THREAD

**Issue by LeeRiva** [vsg-dev/VulkanSceneGraph#978]
**Describe the bug**
I see artefacts around glyphs when rendering text. The whole thing is probably a driver issue though, not sure there could/should be something done in VSG?

**To Reproduce**
I just run the vsgText and vsgTextgroup examples. The artefacts are immediately visible, when zooming in they disappear.

**Expected behavior**
No artefacts :)

**Screenshots**
![vsgTextGroup](https://github.com/vsg-dev/VulkanSceneGraph/assets/76054616/52aa3eb6-7b4d-40df-82d5-a0f7e234984b)

![vsgFonts](https://github.com/vsg-dev/VulkanSceneGraph/assets/76054616/10782e68-4f6f-4b24-b12e-62397893bb75)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - NVidia Geforce RTX 2070 with 536.99 and 537.34 (this one downloaded/installed today) drivers. I am using the default driver settings, not sure if there's something I could do to improve the situation.

**Comment by rolandhill** [comment]
Hi Lee,

FYI, there was a long discussion about this here
https://github.com/vsg-dev/VulkanSceneGraph/issues/680.

Text rendering is very sensitive to rendering order - you need to render
them last, and if they overlap then they need to be depth sorted or use
some type of order independent transparency.

Regards,
Roland

**Comment by LeeRiva** [comment]
Hi Roland,

thank you very much for your reply, my bad for not searching for this issue before. I shall
