### ISSUE TITLE
"All paths through this function will call itself" in Visitor::apply

### ISSUE THREAD

**Issue by olegded** [vsg-dev/VulkanSceneGraph#98]
clang on macOS (Apple LLVM version 10.0.1 (clang-1001.0.46.4)) generates

`All paths through this function will call itself`

warning in

```c++
void Visitor::apply(External& value)
{
    apply(static_cast<External&>(value));
}
```

**Comment by vsg-dev** [comment]
Oppps, copy and paste anti pattern strike again!  I found the same problem in the ConstVisitor as well so I've fixed both and check this into master.

https://github.com/vsg-dev/VulkanSceneGraph/commit/8ae1c30633da9399f31c8327cc419ab08a33b474
